//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFDSTC_Config.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MFDSTC_CONFIG_FORM          101
#define IDD_GENERALPAGE                 103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_SONICPAGE                   105
#define IDD_SUPPORTPAGE                 110
#define IDR_MAINFRAME                   128
#define IDR_MFDSTC_ConfigTYPE           129
#define IDD_CONNECTION_TEST             133
#define IDD_SPECIALPAGE                 139
#define IDC_PLACEHOLDER                 1000
#define IDC_MARKET                      1001
#define IDC_AWD_AUTOLOGON               1002
#define IDC_AWD_INTERFACE_DLL           1003
#define IDC_DATAPATH_PATH               1004
#define IDC_DATAPATH_FYI                1005
#define IDC_DATAPATH_REPOSITORY         1006
#define IDC_TL_USE_SONIC                1008
#define IDC_CHECK2                      1009
#define IDC_TL_RECYCLE_INTERVAL         1011
#define IDC_TL_RECYCLE_INTERVAL_SPIN    1012
#define IDC_TL_RTS_HOST                 1013
#define IDC_TL_RTS_PORT                 1014
#define IDC_TL_ZTS_PRIMARY_PROTOCOL     1015
#define IDC_TL_ZTS_PRIMARY_HOST         1016
#define IDC_TL_ZTS_PRIMARY_PORT         1017
#define IDC_TL_ZTS_BACKUP_PROTOCOL      1018
#define IDC_TL_ZTS_BACKUP_HOST          1019
#define IDC_TL_ZTS_BACKUP_PORT2         1020
#define IDC_TL_SINGLEQIDC_TL_SINGLEQ    1024
#define IDC_TL_SINGLEQ                  1024
#define IDC_TL_SINGLEQIDC_TL_MULTIQ     1025
#define IDC_TL_MULTIQ                   1025
#define IDC_TL_SINGLEQIDC_TL_AUTHQ      1026
#define IDC_TL_AUTHQ                    1026
#define IDC_TL_USERNS                   1027
#define IDC_EDIT8                       1028
#define IDC_TL_SMQUSER                  1028
#define IDC_EDIT9                       1029
#define IDC_TL_SMQPASSWORD              1029
#define IDC_TL_WAIT_TIMEOUT             1030
#define IDC_XML_DESCRIPTION             1032
#define IDC_TL_AWDQ                     1032
#define IDC_SP_LOG_ENABLE               1035
#define IDC_SP_LOG_PATH                 1036
#define IDC_SP_LOG_FILE                 1037
#define IDC_SP_LOG_LEVEL                1038
#define IDC_SP_VIEWLOG_ENABLE           1039
#define IDC_SP_VIEWLOG_PATH             1040
#define IDC_SP_VIEWLOG_APPEND           1041
#define IDC_SP_VIEWLOG_COMPLETE         1042
#define IDC_SP_VIEWLOG_RAWREQ           1043
#define IDC_SP_VIEWLOG_RAWRESP          1044
#define IDC_SP_VIEWTIME_ENABLE          1045
#define IDC_SP_VIEWTIME_PATH            1046
#define IDC_SP_VIEWTIME_SIZE            1047
#define IDC_SP_DISPLAYCONNECTIONICON    1048
#define IDC_SONIC_TEST                  1049
#define IDC_TL_WAIT_TIMEOUT_SPIN        1050
#define IDC_PB_PRIMARY_TELNET           1051
#define IDC_RTS_TEST                    1051
#define IDC_PB_CONNECT                  1053
#define IDC_PB_SINGLEQ                  1054
#define IDC_PB_MULTIQ                   1055
#define IDC_PB_AUTHQ                    1056
#define IDC_PB_AWDQ                     1057
#define IDC_ST_PRIMARY                  1058
#define IDC_ST_CONNECT                  1060
#define IDC_ST_SINGLEQ                  1061
#define IDC_ST_MULTIQ                   1062
#define IDC_ST_AUTHQ                    1063
#define IDC_ST_AWDQ                     1064
#define IDC_CONNECT_MESSAGE             1065
#define IDC_STATUS_CONNECT              1067
#define IDC_STATUS_TELNET               1068
#define IDC_STATUS_SINGLEQ              1069
#define IDC_STATUS_MULTIQ               1070
#define IDC_STATUS_AUTHQ                1071
#define IDC_ST_LAST_CHANGED_USER        1072
#define IDC_STATUS_AUTHQ2               1072
#define IDC_STATUS_AWDQ                 1072
#define IDC_LAST_CHANGED_BY             1073
#define IDC_LAST_CHANGED_DATE           1074
#define IDC_VERSION_NUMBER              1075
#define IDC_TAB1                        1077
#define IDC_SHOW_CLIENT_NAME_PANE       1078
#define IDC_SP_SHOW_CLIENT_NAME_PANE    1078
#define IDC_TX_RTS_TEST                 1079
#define IDC_SP_DISPLAY_CONDITION_NAME   1080
#define IDC_TL_SINGLE_CONNECTION        1081
#define IDC_CSI_HOST                    1082
#define IDC_CSI_PARAM                   1083
#define IDC_CSI_TYPE                    1084
#define IDC_EDIT1                       1086
#define IDC_SP_VIEWBATCH                1086
#define IDC_SP_EXCEPTION_REPORT_ENABLE  1087
#define IDC_EDIT2                       1088
#define IDC_SP_EXCEPTION_REPORT_PATH    1088
#define IDC_COMBOBOXEX1                 1091
#define IDC_SPEC_MMF                    1091
#define ID_FILE_LOADFROMREGISTRY        32771
#define ID_LOADFROMREGISTRY_PLACEHOLDER 32772
#define IDM_LOAD_FROM_REGISTRY          32773
#define IDM_LFR_PLACEHOLDER             32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
