//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ifsupp.rc
//
#define IDC_PB_PRIMARY_TELNET           1051
#define IDC_PB_CONNECT                  1053
#define IDC_PB_SINGLEQ                  1054
#define IDC_PB_MULTIQ                   1055
#define IDC_PB_AUTHQ                    1056
#define IDC_PB_AWDQ                     1057
#define IDC_ST_PRIMARY                  1058
#define IDC_ST_CONNECT                  1060
#define IDC_ST_SINGLEQ                  1061
#define IDC_ST_MULTIQ                   1062
#define IDC_ST_AUTHQ                    1063
#define IDC_ST_AWDQ                     1064
#define IDC_CONNECT_MESSAGE             1065
#define IDC_STATUS_CONNECT              1067
#define IDC_STATUS_TELNET               1068
#define IDC_STATUS_SINGLEQ              1069
#define IDC_STATUS_MULTIQ               1070
#define IDC_STATUS_AUTHQ                1071
#define IDC_STATUS_AWDQ                 1072
#define IDC_LB_COMPONENT_INFO           1112
#define IDC_SONIC_BROKER_URLS           2572
#define IDC_SECURITY_TOKEN              2572
#define IDC_RTS_HOST                    2572
#define IDC_REGISTRY_KEY                2572
#define IDC_ABOUT_MGMT_COMPANY_ID       2572
#define IDC_LOG_FILE                    2572
#define IDC_BUILD_TIME                  2572
#define IDC_LOG_LEVEL                   2624
#define IDC_SONIC_INUSE_CONNECTIONS     2626
#define IDC_SONIC_USER                  2695
#define IDC_RTS_PORT                    2695
#define IDC_SITE_CONFIG                 2695
#define IDC_ABOUT_MGMT_CLIENT_ID        2695
#define IDC_LOG_PATH                    2695
#define IDC_BUILD_LABEL                 2695
#define IDC_SONIC_PING                  2805
#define IDC_RTS_PING                    2805
#define IDC_SONIC_SINGLE_Q              3760
#define IDC_SONIC_MULTI_Q               3761
#define IDC_SONIC_TIMEOUT               3762
#define IDC_SONIC_LDAP_NS               3763
#define IDC_USING_AWD                   3763
#define IDC_SONIC_LDAP_Q                3764
#define IDC_RTS_TIMEOUT                 3764
#define IDC_SONIC_MIN_CONNECTIONS       3765
#define IDC_SONIC_LDAP_Q2               3766
#define IDC_SONIC_AWD_Q                 3766
#define IDC_LOG_ENABLE                  3769
#define IDC_SONIC_MAX_CONNECTIONS       3770
#define IDC_SONIC_COUNT_CONNECTIONS     3771
#define IDC_LOG_VIEWTIME_PATH           3771
#define IDC_SONIC_FAILED_CONNECTIONS    3772
#define IDC_LOG_VIEWLOG_ENABLE          3772
#define IDC_LOG_VIEWLOG_COMPLETE        3773
#define IDC_LOG_VIEWLOG_APPEND          3774
#define IDC_LOG_VIEWLOG_REQUEST         3775
#define IDC_LOG_VIEWLOG_RESPONSE        3776
#define IDC_LOG_VIEWLOG_PATH2           3777
#define IDC_LOG_VIEWTIME_ENABLE         3778
#define IDC_LOG_EXCEPTION_PATH          3779
#define IDC_LOG_EXCEPTION_ENABLE        3780
#define IDC_GENERAL_CWD                 3781
#define IDC_GENERAL_PID                 3782
#define IDC_SONIC_CONNECTION_LIST       3783
#define IDC_SONIC_CHECK                 3784
#define IDC_SONIC_PING_STATUS           3785
#define IDC_SONIC_CHECK_STATUS          3786
#define IDC_RTS_CHECK                   3787
#define IDC_RTS_CHECK_STATUS            3788
#define IDC_RTS_PING_STATUS             3789
#define IDC_GENERAL_MARKET              3790
#define IDC_GENERAL_VAAL_MODE           3791
#define IDC_SONIC_REUSE_CONNECTION      3795
#define IDC_LOG_DISPLAY_CONDITION_NAME  3795
#define IDC_SONIC_VIEW_BATCHES          3797
#define IDC_GENERAL_REPORT              3798
#define IDC_LB_BANDS                    3799
#define IDC_LB_MGMT_OPTIONS             3800
#define IDC_LB_SECURITY                 3801
#define IDC_ABOUT_MGMT_URL              3802
#define IDC_ABOUT_MGMT_NAME             3803
#define IDC_ST_BUILD_TIME               3804
#define IDC_ST_BUILD_LABEL              3805
#define IDC_LOG_DISPLAY_CLIENT_NAME_PANE 3806
#define IDC_ST_USING_AWD                3806
#define IDC_ST_CWD                      3807
#define IDC_ST_PID                      3808
#define IDC_ST_MARKET                   3809
#define IDC_ST_REV_NUM_                 3810
#define IDC_GENERAL_REVISION_NUM        3811
#define IDC_CHECK_DESKTOP_WEB_URL       5000
#define IDD_ABOUT_ACTIVEMQ              5000
#define IDD_ABOUT_CONNECTION_TEST       11133
#define IDD_ABOUT_MODULES               11348
#define IDD_ABOUT_REGISTRY              11349
#define IDD_ABOUT_SONIC                 11350
#define IDD_ABOUT_RTS                   11351
#define IDD_ABOUT_LOG                   11352
#define IDD_ABOUT_GENERAL               11353
#define IDD_ABOUT_MGMT                  11359
#define IDD_ABOUT_BANDS                 11360
#define IDD_ABOUT_MGMT_OPTIONS          11361
#define IDD_ABOUT_SECURITY              11362
#define IDC_LB_REVISION_INFO            61262

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        5001
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5001
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
