//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 12:17:13 PM EDT 
//


package com.ifdsgroup.ifast.desktop.web.api.dto;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}AcctBalList" minOccurs="0"/&gt;
 *         &lt;element ref="{}RequestStatus"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acctBalList",
    "requestStatus"
})
@XmlRootElement(name = "gnAcctBalAsOfResponse")
public class GnAcctBalAsOfResponse
    implements Serializable
{

    @XmlElement(name = "AcctBalList")
    protected AcctBalList acctBalList;
    @XmlElement(name = "RequestStatus", required = true)
    protected RequestStatus requestStatus;

    /**
     * Gets the value of the acctBalList property.
     * 
     * @return
     *     possible object is
     *     {@link AcctBalList }
     *     
     */
    public AcctBalList getAcctBalList() {
        return acctBalList;
    }

    /**
     * Sets the value of the acctBalList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcctBalList }
     *     
     */
    public void setAcctBalList(AcctBalList value) {
        this.acctBalList = value;
    }

    /**
     * Gets the value of the requestStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RequestStatus }
     *     
     */
    public RequestStatus getRequestStatus() {
        return requestStatus;
    }

    /**
     * Sets the value of the requestStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestStatus }
     *     
     */
    public void setRequestStatus(RequestStatus value) {
        this.requestStatus = value;
    }

}
