//Computer Generated Condition File for Module: diawd23


#ifndef DIAWD23_CONDITIONS
#define DIAWD23_CONDITIONS


#pragma message("including "__FILE__ )
#ifndef COMMONPORT_H
#include "commonport.h"
#endif

#undef DIAWD23_LINKAGE
#ifdef DIAWD23_DLL
#define DIAWD23_LINKAGE CLASS_EXPORT
#else
#define DIAWD23_LINKAGE CLASS_IMPORT
#endif

namespace CND_DIAWD23
{
   extern DIAWD23_LINKAGE const I_CHAR * DIAWD23_CONDITION;


   extern DIAWD23_LINKAGE const long DIAWD23_INIT_COM_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_CONNECT_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_LOGON_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_LOGOFF_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_RETRIEVE_AWDOBJ_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_OLE_ARRAY_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_RELATE_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_COMMENT_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_UPDATE_AWDOBJ_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_CREATE_AWDOBJ_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_OBJECT_LOCKED;
   extern DIAWD23_LINKAGE const long DIAWD23_OLE_EXCEPTION;
   extern DIAWD23_LINKAGE const long DIAWD23_CONTAINER_ALREADY_OPEN;
   extern DIAWD23_LINKAGE const long DIAWD23_CONTAINER_OPEN_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_CONTAINER_NOT_OPEN;
   extern DIAWD23_LINKAGE const long DIAWD23_CONTAINER_CLOSE_FAIL;
   extern DIAWD23_LINKAGE const long DIAWD23_CONTAINER_NOT_CLEAR;
   extern DIAWD23_LINKAGE const long DIAWD23_AWD_EXCEPTION;
   extern DIAWD23_LINKAGE const long DIAWD23_UNKNOWN_AWD_EXCEPTION;
   extern DIAWD23_LINKAGE const long DIAWD23_CREATE_AWDSRC_FAIL;
}

using namespace CND_DIAWD23;

#endif
