//Computer Generated Condition File for Module: dicbocore


#ifndef DICBOCORE_CONDITIONS
#define DICBOCORE_CONDITIONS


#pragma message("including "__FILE__ )
#ifndef COMMONPORT_H
#include "commonport.h"
#endif

#undef DICBOCORE_LINKAGE
#ifdef DICBOCORE_DLL
#define DICBOCORE_LINKAGE CLASS_EXPORT
#else
#define DICBOCORE_LINKAGE CLASS_IMPORT
#endif

namespace CND_DICBOCORE
{
   extern DICBOCORE_LINKAGE const I_CHAR * DICBOCORE_CONDITION;


   extern DICBOCORE_LINKAGE const long ERR_FIELD_READ_ONLY;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_READ_ONLY;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_PTR_ACCESS_ONLY;
   extern DICBOCORE_LINKAGE const long ERR_NO_REGISTERED_OBJECT;
   extern DICBOCORE_LINKAGE const long ERR_NO_UPDATES_TO_APPLY;
   extern DICBOCORE_LINKAGE const long ERR_INVALID_FIELD_ID;
   extern DICBOCORE_LINKAGE const long ERR_NO_VIEW_DATA_OBJECTS_REGISTERED;
   extern DICBOCORE_LINKAGE const long ERR_CBE_LABEL_INVALID_FOR_UPDATE;
   extern DICBOCORE_LINKAGE const long ERR_UNABLE_TO_RETRIEVE_LABEL_DATA;
   extern DICBOCORE_LINKAGE const long ERR_INVALID_FIELD_TAG;
   extern DICBOCORE_LINKAGE const long ERR_STRING_EXCEPTION;
   extern DICBOCORE_LINKAGE const long ERR_INVALID_METHOD_CALL;
   extern DICBOCORE_LINKAGE const long ERR_FIELD_MAX_LEN_EXCEEDED;
   extern DICBOCORE_LINKAGE const long ERR_INVALID_FIELD_TYPE;
   extern DICBOCORE_LINKAGE const long ERR_UNKNOWN_EXCEPTION;
   extern DICBOCORE_LINKAGE const long ERR_INDEX_OUT_OF_RANGE;
   extern DICBOCORE_LINKAGE const long ERR_NO_VIEW_DATA_REPEATS;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_INVALID_TYPE;
   extern DICBOCORE_LINKAGE const long ERR_FLD_NOT_VALIDATED;
   extern DICBOCORE_LINKAGE const long ERR_INVALID_OBJ_POINTER;
   extern DICBOCORE_LINKAGE const long ERR_HOLIDAY_FILE;
   extern DICBOCORE_LINKAGE const long ERR_MFDATE_INVALID;
   extern DICBOCORE_LINKAGE const long ERR_RETREIVING_DATE;
   extern DICBOCORE_LINKAGE const long ERR_INVALID_TIME;
   extern DICBOCORE_LINKAGE const long ERR_FORMAT_NOT_RECOGNIZED;
   extern DICBOCORE_LINKAGE const long ERR_VIEW_MGR;
   extern DICBOCORE_LINKAGE const long ERR_WORKORDER_CBEKEY_NOT_FOUND;
   extern DICBOCORE_LINKAGE const long ERR_WORKORDER_CBE_ALREADY_REGISTERED;
   extern DICBOCORE_LINKAGE const long ERR_WORKORDER_CBEKEY_DUPLICATED;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_PRIVATE_USE;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_COPY_ONLY;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_REQUIRED;
   extern DICBOCORE_LINKAGE const long ERR_IMPROPER_CLASS_FIELD_VALID_VALUES;
   extern DICBOCORE_LINKAGE const long ERR_FIELD_VALUE_NOT_VALID;
   extern DICBOCORE_LINKAGE const long ERR_MIN_VALUE_GREATER_THAN_MAX;
   extern DICBOCORE_LINKAGE const long ERR_FIELD_IS_UNDER_MINIMUM_ALLOWED;
   extern DICBOCORE_LINKAGE const long ERR_FIELD_IS_OVER_MAXIMUM_ALLOWED;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_NOT_COPYABLE;
   extern DICBOCORE_LINKAGE const long ERR_FIELD_CHECKPOINT_NOT_AVAILABLE;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_OWNED_BY_LIST;
   extern DICBOCORE_LINKAGE const long ERR_KEY_NOT_FOUND;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_NOT_FOUND;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_DOES_NOT_ALLOW_GROUPS;
   extern DICBOCORE_LINKAGE const long ERR_FIELD_GROUP_NOT_FOUND;
   extern DICBOCORE_LINKAGE const long ERR_INVALID_USE_OF_OFFICIAL_GROUP;
   extern DICBOCORE_LINKAGE const long ERR_INVALID_ITERATOR_POSITION;
   extern DICBOCORE_LINKAGE const long ERR_NO_ADDITIONAL_REPEAT_RECORDS;
   extern DICBOCORE_LINKAGE const long ERR_FIELD_REQUIRED;
   extern DICBOCORE_LINKAGE const long ERR_NO_DELETE_OBJECT_ALLOWED;
   extern DICBOCORE_LINKAGE const long WRN_OBJECT_DOES_NOT_ALLOW_GROUPS;
   extern DICBOCORE_LINKAGE const long ERR_INCOMPATIBLE_REGISTERED_OBJECTS;
   extern DICBOCORE_LINKAGE const long ERR_INVALID_BATCH_WORKORDER_EVENT;
   extern DICBOCORE_LINKAGE const long ERR_EVENT_MIXING_NOT_ALLOWED;
   extern DICBOCORE_LINKAGE const long ERR_SEARCH_NOT_FOUND;
   extern DICBOCORE_LINKAGE const long DICORE_DATE_INVALID;
   extern DICBOCORE_LINKAGE const long DICORE_DATE_FORMAT_NOT_RECOGNIZED;
   extern DICBOCORE_LINKAGE const long ERR_MULTIPLE_INIT_CALLS;
   extern DICBOCORE_LINKAGE const long ERR_COPY_OBJECT_NOT_INITIALIZED;
   extern DICBOCORE_LINKAGE const long ERR_OBJECT_NOT_INITIALIZED;
   extern DICBOCORE_LINKAGE const long ERR_INVALID_VIEW_LIMIT;
   extern DICBOCORE_LINKAGE const long ERR_VALIDATE_CROSS_FIELD;
}

using namespace CND_DICBOCORE;

#endif
