//Computer Generated Condition File for Module: dicore


#ifndef DICORE_CONDITIONS
#define DICORE_CONDITIONS


#pragma message("including "__FILE__ )
#ifndef COMMONPORT_H
#include "commonport.h"
#endif

#undef DICORE_LINKAGE
#ifdef DICORE_DLL
#define DICORE_LINKAGE CLASS_EXPORT
#else
#define DICORE_LINKAGE CLASS_IMPORT
#endif

namespace CND_DICORE
{
   extern DICORE_LINKAGE const I_CHAR * DICORE_CONDITION;


   extern DICORE_LINKAGE const long DILOCAL_JNI_EXCEPTION_CREATEJVM;
   extern DICORE_LINKAGE const long DILOCAL_JNI_EXCEPTION_EXECUTE;
   extern DICORE_LINKAGE const long DILOCAL_JNI_EXCEPTION_LOCATE;
   extern DICORE_LINKAGE const long DICORE_DLL_LOAD_FAIL;
   extern DICORE_LINKAGE const long DICORE_FUNCTION_LOAD_FAIL;
   extern DICORE_LINKAGE const long DICORE_EVENTSEM_CREATE_FAIL;
   extern DICORE_LINKAGE const long DICORE_EVENTSEM_OPEN_FAIL;
   extern DICORE_LINKAGE const long DICORE_EVENTSEM_SET_FAIL;
   extern DICORE_LINKAGE const long DICORE_EVENTSEM_WAIT_FAIL;
   extern DICORE_LINKAGE const long DICORE_EVENTSEM_RESET_FAIL;
   extern DICORE_LINKAGE const long DICORE_MUTEXSEM_CREATE_FAIL;
   extern DICORE_LINKAGE const long DICORE_MUTEXSEM_OPEN_FAIL;
   extern DICORE_LINKAGE const long DICORE_MUTEXSEM_RELEASE_FAIL;
   extern DICORE_LINKAGE const long DICORE_MUTEXSEM_WAIT_FAIL;
   extern DICORE_LINKAGE const long DICORE_PROCESS_CREATE_FAIL;
   extern DICORE_LINKAGE const long DICORE_PIPE_INIT_FAIL;
   extern DICORE_LINKAGE const long DICORE_OVERSIZE_BUFFER;
   extern DICORE_LINKAGE const long DICORE_BAD_PACKET;
   extern DICORE_LINKAGE const long DICORE_IPC_SYNCH_FAIL;
   extern DICORE_LINKAGE const long DICORE_VMCONNECT_FAIL;
   extern DICORE_LINKAGE const long DICORE_VMDISCONNECT_FAIL;
   extern DICORE_LINKAGE const long DICORE_VMNOTIFYSEM_FAIL;
   extern DICORE_LINKAGE const long DICORE_VMAPPREQUEST_FAIL;
   extern DICORE_LINKAGE const long DICORE_VMREADRESPONSE_FAIL;
   extern DICORE_LINKAGE const long DICORE_VMREQUEST_FAIL;
   extern DICORE_LINKAGE const long DICORE_VMREQUEST_INIT_FAIL;
   extern DICORE_LINKAGE const long DICORE_VMREQUEST_WAIT_FAIL;
   extern DICORE_LINKAGE const long DICORE_VMREQUEST_CALLBACK_ERROR_CONDITION;
   extern DICORE_LINKAGE const long DICORE_VMREQUEST_CALLBACK_CONDITIONEXCEPTION_THROWN;
   extern DICORE_LINKAGE const long DICORE_VMREQUEST_CALLBACK_UNKNOWN_EXCEPTION_THROWN;
   extern DICORE_LINKAGE const long DICORE_BUFFER_SIZE_TOO_SMALL;
   extern DICORE_LINKAGE const long DICORE_DIVIDE_BY_ZERO;
   extern DICORE_LINKAGE const long DICORE_VMAPPREQUEST_TIMEOUT;
   extern DICORE_LINKAGE const long DICORE_DELETE_KEY_FAIL;
   extern DICORE_LINKAGE const long DICORE_DELETE_VALUE_FAIL;
   extern DICORE_LINKAGE const long DICORE_SAVE_KEY_FAIL;
   extern DICORE_LINKAGE const long DICORE_SAVE_VALUE_FAIL;
   extern DICORE_LINKAGE const long DICORE_KEY_NOT_FOUND;
   extern DICORE_LINKAGE const long DICORE_OPEN_INI_FILE_FAIL;
   extern DICORE_LINKAGE const long DICORE_CANNOT_READ_DEFINITION;
   extern DICORE_LINKAGE const long DICORE_CANNOT_PERSIST_UNDEFINED_MGR;
   extern DICORE_LINKAGE const long DICORE_READ_REGISTRY_FAIL;
   extern DICORE_LINKAGE const long DICORE_PERSIST_REGISTRY_FAIL;
   extern DICORE_LINKAGE const long DICORE_LOCATION_NOT_DEFINED;
   extern DICORE_LINKAGE const long DICORE_DATAPATH_ENV_NOT_DEFINED;
   extern DICORE_LINKAGE const long DICORE_DATAPATH_REG_NOT_DEFINED;
   extern DICORE_LINKAGE const long DICORE_PROFILE_ALREAD_EXISTS;
   extern DICORE_LINKAGE const long DICORE_PARSE_IDI_MISSING_TERMINATOR;
   extern DICORE_LINKAGE const long DICORE_PARSE_IDI_MISSING_VALUE;
   extern DICORE_LINKAGE const long DICORE_PARSE_IDI_MISSING_TAG_NAME;
   extern DICORE_LINKAGE const long DICORE_PARSE_IDI_MISSING_SEPARATOR;
   extern DICORE_LINKAGE const long BASE_ALLOC_FAIL;
   extern DICORE_LINKAGE const long VIRTUAL_BASE_METHOD_NOT_SUPPORTED;
   extern DICORE_LINKAGE const long DICORE_DATE_STRING_INVALID;
   extern DICORE_LINKAGE const long DICORE_HOSTMASKS_NOT_DEFINED_IN_REGISTRY;
   extern DICORE_LINKAGE const long DICORE_VMNOTIFYWIN_FAIL;
}

using namespace CND_DICORE;

#endif
