//Computer Generated Condition File for Module: didbrkr


#ifndef DIDBRKR_CONDITIONS
#define DIDBRKR_CONDITIONS


#pragma message("including "__FILE__ )
#ifndef COMMONPORT_H
#include "commonport.h"
#endif

#undef DIDBRKR_LINKAGE
#ifdef DIDBRKR_DLL
#define DIDBRKR_LINKAGE CLASS_EXPORT
#else
#define DIDBRKR_LINKAGE CLASS_IMPORT
#endif

namespace CND_DIDBRKR
{
   extern DIDBRKR_LINKAGE const I_CHAR * DIDBRKR_CONDITION;


   extern DIDBRKR_LINKAGE const long DIDBRKR_CANT_SET_VALUES;
   extern DIDBRKR_LINKAGE const long DIDBRKR_COMPONENT_NOT_FOUND;
   extern DIDBRKR_LINKAGE const long DIDBRKR_DATA_HAS_NO_REPEATS;
   extern DIDBRKR_LINKAGE const long DIDBRKR_INDEX_OUT_OF_RANGE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_CANNOT_ASSIGN_DATA_OBJECTS;
   extern DIDBRKR_LINKAGE const long DIDBRKR_ELEMENT_NOT_FOUND;
   extern DIDBRKR_LINKAGE const long DIDBRKR_REPEAT_COUNT_ELEMENT_NOT_FOUND;
   extern DIDBRKR_LINKAGE const long DIDBRKR_KEY_NOT_FOUND;
   extern DIDBRKR_LINKAGE const long DIDBRKR_NOT_A_DATA_OBJECT;
   extern DIDBRKR_LINKAGE const long DIDBRKR_NOT_A_DATAELEMENT_OBJECT;
   extern DIDBRKR_LINKAGE const long DIDBRKR_REPEAT_INDEX_OUT_OF_RANGE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_CANNOT_ASSIGN_DATAELEMENT_OBJECTS;
   extern DIDBRKR_LINKAGE const long DIDBRKR_PROPERTIES_DONT_MATCH;
   extern DIDBRKR_LINKAGE const long DIDBRKR_PROPERTY_DOES_NOT_EXIST;
   extern DIDBRKR_LINKAGE const long DIDBRKR_PROPERTY_DOES_NOT_EXIST_AT_INDEX;
   extern DIDBRKR_LINKAGE const long DIDBRKR_CANT_OPEN_PROPERTIES_FILE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_NO_PATH_TO_PROPERTIES_FILE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_BAD_FORMAT_IN_STREAM_FILE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_ERROR_READING_STREAM_FILE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_UNEXPECTED_END_OF_STREAM_FILE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_INVALID_LINE_LENGTH;
   extern DIDBRKR_LINKAGE const long DIDBRKR_INVALID_PROPERTY_POINTER;
   extern DIDBRKR_LINKAGE const long DIDBRKR_NOT_REPEATABLE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_DUPLICATE_PROPERTIES;
   extern DIDBRKR_LINKAGE const long DIDBRKR_EXTRA_LINES_IN_PROPERTIES_FILE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_LOCALE_NOT_FOUND;
   extern DIDBRKR_LINKAGE const long DIDBRKR_DATASET_NOT_FOUND;
   extern DIDBRKR_LINKAGE const long DIDBRKR_FILE_SEEK_FAILED;
   extern DIDBRKR_LINKAGE const long DIDBRKR_I18N_MASK_FORMAT_ERROR;
   extern DIDBRKR_LINKAGE const long DIDBRKR_INVALID_REDEFINE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_REDEFINE_HAS_DUPLICATE;
   extern DIDBRKR_LINKAGE const long DIDBRKR_REDEFINE_LENGTH_MISMATCH;
   extern DIDBRKR_LINKAGE const long DIDBRKR_REDEFINE_REPEATS_NOT_ALLOWED;
   extern DIDBRKR_LINKAGE const long DIDBRKR_READ_SIZE_FAILED;
   extern DIDBRKR_LINKAGE const long DIDBRKR_TARGET_LOCALE_MISSING;
}

using namespace CND_DIDBRKR;

#endif
