//Computer Generated Condition File for Module: ditabuscore


#ifndef DITABUSCORE_CONDITIONS
#define DITABUSCORE_CONDITIONS


#pragma message("including "__FILE__ )
#ifndef COMMONPORT_H
#include "commonport.h"
#endif

#undef DITABUSCORE_LINKAGE
#ifdef DITABUSCORE_DLL
#define DITABUSCORE_LINKAGE CLASS_EXPORT
#else
#define DITABUSCORE_LINKAGE CLASS_IMPORT
#endif

namespace CND_DITABUSCORE
{
   extern DITABUSCORE_LINKAGE const I_CHAR * DITABUSCORE_CONDITION;


   extern DITABUSCORE_LINKAGE const long WRN_LINE_NUMBER;
   extern DITABUSCORE_LINKAGE const long ERR_FIELD_MUSTBE_EMPTY;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_ZIPCODE_FOR;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_STATE_COUNTRY;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_FIELD_LENGTH;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_NUMBER_OF_ADDRESS_LINES;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_ADDRESS_LINE;
   extern DITABUSCORE_LINKAGE const long ERR_CITY_NAME_REQUIRED;
   extern DITABUSCORE_LINKAGE const long ERR_CITY_NAME_NOT_ALLOWED;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_MILITARY_LOCATION;
   extern DITABUSCORE_LINKAGE const long ERR_MILITARY_LOCATION_NOT_ALLOWED;
   extern DITABUSCORE_LINKAGE const long ERR_ZIP_DLVRY_OFFICE_CDE_REQUIRED;
   extern DITABUSCORE_LINKAGE const long ERR_ZIP_DLVRY_OFFICE_CDE_NOT_ALLOWED;
   extern DITABUSCORE_LINKAGE const long ERR_ZIP_CODE_SUFFIX_REQUIRED;
   extern DITABUSCORE_LINKAGE const long ERR_ZIP_CODE_SUFFIX_NOT_ALLOWED;
   extern DITABUSCORE_LINKAGE const long ERR_ZIP_DLVRY_SEQ_NBR_REQUIRED;
   extern DITABUSCORE_LINKAGE const long ERR_ZIP_DLVRY_SEQ_NBR_NOT_ALLOWED;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_ZIP_CODE;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_ZIPCODE;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_FORMAT_TYPE_CODE;
   extern DITABUSCORE_LINKAGE const long ERR_ZIP_CODE_NOT_NUMERIC;
   extern DITABUSCORE_LINKAGE const long ERR_POSTAL_ADDRESS_NOT_FORMATTED;
   extern DITABUSCORE_LINKAGE const long ERR_STATE_COUNTRY_CODE_REQUIRED;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_STATE_COUNTRY_CODE;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_CERTIFICATION_STATUS_CODE;
   extern DITABUSCORE_LINKAGE const long ERR_FIELD_NOT_NUMERIC;
   extern DITABUSCORE_LINKAGE const long ERR_FIELD_VALUE_ZERO;
   extern DITABUSCORE_LINKAGE const long WRN_FINALIST_WRN;
   extern DITABUSCORE_LINKAGE const long WRN_S017PE_WRN;
   extern DITABUSCORE_LINKAGE const long ERR_FIELD_EMPTY;
   extern DITABUSCORE_LINKAGE const long ERR_INVALID_CITY_NAME_WRT_STATE_CODE;
}

using namespace CND_DITABUSCORE;

#endif
