apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktopweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desktopweb
  template:
    metadata:
      labels:
        app: desktopweb
    spec:
      containers:
      - name: desktopweb
        image: localhost:5000/ifds/desktopweb
        ports:
          - name: desktopweb-port
            containerPort: 8080
        env:
          - name: ifast.connector
            valueFrom:
              configMapKeyRef:
                name: desktopweb-config
                key: ifast.connector
          - name: ifast.connector.appurl
            valueFrom:
              configMapKeyRef:
                name: desktopweb-config
                key: ifast.connector.appurl
          - name: ifast.connector.procfile
            valueFrom:
              configMapKeyRef:
                name: desktopweb-config
                key: ifast.connector.procfile
          - name: jrdsp.services.url
            valueFrom:
              configMapKeyRef:
                name: desktopweb-config
                key: jrdsp.services.url                




