// Computer Generated Condition File for Module: bfdbrkr


#pragma message("including "__FILE__ )
#ifndef PLATFORM_H
#include "platform.h"
#endif


namespace CND
{
  CLASS_EXPORT const I_CHAR *BFDBRKR_CONDITION = I_( "BFDBRKR" );

  //extern CLASS_EXPORT const long ERR_MALFORMED_FILE_RESPONSE_BUFFER = 40000081;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_CONNECT_FAILED = 40000230;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_NOTIFY_FAILED = 40000231;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_CREATE_FAILED = 40000232;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_CREATE_EVENT = 40000233;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_DISCONNECT_FAILED = 40000234;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_WAITEVENT_FAILED = 40000235;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_REQUEST_FAILED = 40000236;
  //extern CLASS_EXPORT const long ERR_HOST_CONNECTION_MGR_NOT_FOUND = 40000238;
  //extern CLASS_EXPORT const long MULTYBYTE_TO_UNICODE_CONVERSION_ERROR = 40000239;
  //extern CLASS_EXPORT const long UNICODE_TO_MULTYBYTE_CONVERSION_ERROR = 40000240;
  //extern CLASS_EXPORT const long BFDBRKR_CND_VERSION = 40000276;

	extern CLASS_EXPORT const long BFDBRKR_CND_VERSION = 300001;
	extern CLASS_EXPORT const long ERR_HOST_CONNECTION_MGR_NOT_FOUND = 300002;
	extern CLASS_EXPORT const long ERR_INVALID_TRANS_STATUS = 300003;
	extern CLASS_EXPORT const long ERR_MALFORMED_FILE_RESPONSE_BUFFER = 300004;
	extern CLASS_EXPORT const long ERR_PRIVCONN_CREATE_EVENT = 300005;
	extern CLASS_EXPORT const long ERR_PRIVCONN_CREATE_FAILED = 300006;
	extern CLASS_EXPORT const long ERR_PRIVCONN_DISCONNECT_FAILED = 300007;
	extern CLASS_EXPORT const long ERR_PRIVCONN_NOTIFY_FAILED = 300008;
	extern CLASS_EXPORT const long ERR_PRIVCONN_REQUEST_FAILED = 300009;
	extern CLASS_EXPORT const long ERR_PRIVCONN_WAITEVENT_FAILED = 300010;
	extern CLASS_EXPORT const long ERR_SWITCH_SETTLEMENT_ERROR = 300011;
	extern CLASS_EXPORT const long MULTYBYTE_TO_UNICODE_CONVERSION_ERROR = 300012;
	extern CLASS_EXPORT const long UNICODE_TO_MULTYBYTE_CONVERSION_ERROR = 300013;
	extern CLASS_EXPORT const long MISSMATCHING_VIEW_LAYOUT = 300014;
}

