#include "stdafx.h"
#include <ifasthosttransactioncontainer.hpp>

extern IFASTCBO_LINKAGE TRXN_TYPE NEW_SHAREHOLDER( I_("NEW_SHAREHOLDER" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_SHAREHOLDER( I_("UPDATE_SHAREHOLDER" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ACCOUNT( I_("NEW_ACCOUNT" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ACCOUNT( I_("UPDATE_ACCOUNT" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ENTITY( I_("NEW_ENTITY" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ENTITY( I_("UPDATE_ENTITY" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ENTITY_IDS( I_("NEW_ENTITY_IDS" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ENTITY_IDS( I_("UPDATE_ENTITY_IDS" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ACCOUNT_ENTITY( I_("NEW_ACCOUNT_ENTITY" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ACCOUNT_ENTITY( I_("UPDATE_ACCOUNT_ENTITY" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ADDRESS( I_("NEW_ADDRESS" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ADDRESS( I_("UPDATE_ADDRESS" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_MAILING( I_("NEW_MAILING" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_MAILING( I_("UPDATE_MAILING" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_AS_PENSION( I_("NEW_AS_PENSION" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_AS_PENSION( I_("UPDATE_AS_PENSION" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ESOP( I_("NEW_ESOP" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ESOP( I_("UPDATE_ESOP" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_FEE_PARAM( I_("NEW_FEE_PARAM" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_FEE_PARAM( I_("UPDATE_FEE_PARAM" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_SETTLEMENT( I_("UPDATE_SETTLEMENT" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_MAILING_OVERRIDE( I_("NEW_MAILING_OVERRIDE" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_MAILING_OVERRIDE( I_("UPDATE_MAILING_OVERRIDE" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ACCOUNT_CATEGORY( I_("NEW_ACCOUNT_CATEGORY" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ACCOUNT_CATEGORY( I_("UPDATE_ACCOUNT_CATEGORY" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE CLONE_ACCOUNT( I_("CLONE_ACCOUNT" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ACCOUNT_GUARNT_GUARD_OPTN( I_("UPDATE_ACCOUNT_GUARNT_GUARD_OPTN" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ACCOUNT_GUARNT_GUARD_OPTN( I_("NEW_ACCOUNT_GUARNT_GUARD_OPTN" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ACCOUNT_REGULATORY_DETAILS( I_("NEW_ACCOUNTT_REGULATORY_DETAILS" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ACCOUNT_REGULATORY_DETAILS( I_("UPDATE_ACCOUNTT_REGULATORY_DETAILS" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ENTITY_REGULATORY_DETAILS( I_("NEW_ENTITY_REGULATORY_DETAILS" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ENTITY_REGULATORY_DETAILS( I_("UPDATE_ENTITY_REGULATORY_DETAILS" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ENTITY_REGULATORY_JURIS_DETAILS( I_("NEW_ENTITY_REGULATORY_JURIS_DETAILS" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ENTITY_REGULATORY_JURIS_DETAILS( I_("UPDATE_ENTITY_REGULATORY_JURIS_DETAILS" ) );
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_TRADEVRIFICATION( I_("UPDATE_TRADEVRIFICATION" ) ); 
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ENTITY_RISK( I_("NEW_ENTITY_RISK" ) ); 
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ENTITY_RISK( I_("UPDATE_ENTITY_RISK" ) ); 

//******************************************************************************
//              Revision Control Entries
//******************************************************************************
//
// $Log:   Y:/VCS/BF iFAST/ifastcbo/ifasthosttransactioncontainer.cpp-arc  $
// 
//    Rev 1.5   Sep 17 2010 07:53:54   kitticha
// PETP0173756 FN02 Don't Bust the Rules.
//

