#include "stdafx.h"

CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACB( I_("OBJ_TYPE_ACB" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACCOUNTENTITY( I_( "OBJ_TYPE_ACCOUNTENTITY" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACCOUNTENTITY_UPDATE( I_( "OBJ_TYPE_ACCOUNTENTITY_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACCOUNT_MAILING( I_( "OBJ_TYPE_ACCOUNT_MAILING" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACCSHRNUMCHECK( I_( "OBJ_TYPE_ACCSHRNUMCHECK" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACCTMAILING_UPDATE( I_( "OBJ_TYPE_ACCTMAILING_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACC_DISTRIB( I_( "OBJ_TYPE_ACC_DISTRIB" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACQFEEINQUIRY( I_( "OBJ_TYPE_ACQFEEINQUIRY" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACTIVE_BATCH( I_( "OBJ_TYPE_ACTIVE_BATCH" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ADDRESS( I_( "OBJ_TYPE_ADDRESS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ADDRESSBOOK_UPDATE( I_( "OBJ_TYPE_ADDRESSBOOK_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ADDRESSES_ENTITY( I_( "OBJ_TYPE_ADDRESSES_ENTITY" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ADDRESS_SEARCH( I_( "OBJ_TYPE_ADDRESS_SEARCH" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ADDRESS_TYPE_LIST( I_( "OBJ_TYPE_ADDRESS_TYPE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_AGENT( I_( "OBJ_TYPE_AGENT" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ALLOCATIONS( I_( "OBJ_TYPE_ALLOCATIONS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ALLOCATIONS_UPDATE( I_( "OBJ_TYPE_ALLOCATIONS_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ANALYSIS_CODE_LIST( I_( "OBJ_TYPE_ANALYSIS_CODE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_AUMATICTRANSFER_UPDATE( I_( "OBJ_TYPE_AUMATICTRANSFER_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_AUTOTRANSFER( I_( "OBJ_TYPE_AUTOTRANSFER" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_BANKING_UPDATE( I_( "OBJ_TYPE_BANKING_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_BANKLIST( I_( "OBJ_TYPE_BANKLIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_BANK_INSTR( I_( "OBJ_TYPE_BANK_INSTR" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_BANK_INSTRUCTION( I_( "OBJ_TYPE_BANK_INSTRUCTION" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_BOOKTYPE_LIST( I_( "OBJ_TYPE_BOOKTYPE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_BRANCH( I_( "OBJ_TYPE_BRANCH" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_BROKER( I_( "OBJ_TYPE_BROKER" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_CERTIFICATE( I_( "OBJ_TYPE_CERTIFICATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_CHEQUE( I_( "OBJ_TYPE_CHEQUE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_CLIENT_BANK_INSTRUCTIONS_LIST( I_( "OBJ_TYPE_CLIENT_BANK_INSTRUCTIONS_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_COA_NAVIG( I_( "OBJ_TYPE_COA_NAVIG" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_CONTRACTINFO( I_( "OBJ_TYPE_CONTRACTINFO" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_CONTRACT_UPDATE( I_( "OBJ_TYPE_CONTRACT_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_CURRENCYLIST( I_( "OBJ_TYPE_CURRENCYLIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_CURRENCY_LIST( I_( "OBJ_TYPE_CURRENCY_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DATE_TIME( I_( "OBJ_TYPE_DATE_TIME" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DATE_VALIDATION( I_( "OBJ_TYPE_DATE_VALIDATION" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DEMOGRAPHICS( I_( "OBJ_TYPE_DEMOGRAPHICS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DEMOGRAPHICS_UPDATE( I_( "OBJ_TYPE_DEMOGRAPHICS_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DEPOSIT( I_( "OBJ_TYPE_DEPOSIT" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DISTRIBUTIONS_UPDATE( I_( "OBJ_TYPE_DISTRIBUTIONS_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DISTRIBUTOR_REPOSITORY( I_( "OBJ_TYPE_DISTRIBUTOR_REPOSITORY" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FINANCIAL_INSTITUTION_REPOSITORY( I_( "OBJ_TYPE_FINANCIAL_INSTITUTION_REPOSITORY" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FINANCIAL_INSTITUTION_LIST( I_( "OBJ_TYPE_FINANCIAL_INSTITUTION_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FINANCIAL_INSTITUTION_TRANSIT_LIST( I_( "OBJ_TYPE_FINANCIAL_INSTITUTION_TRANSIT_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ENTITY( I_( "OBJ_TYPE_ENTITY" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ENTITY_ADDRESS( I_( "OBJ_TYPE_ENTITY_ADDRESS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ENTITYADDRESS_UPDATE( I_( "OBJ_TYPE_ENTITYADDRESS_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ENTITYSEARCHID_UPDATE( I_( "OBJ_TYPE_ENTITYSEARCHID_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ENTITY_IDS( I_( "OBJ_TYPE_ENTITY_IDS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ENTITY_SEARCH( I_( "OBJ_TYPE_ENTITY_SEARCH" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ENTITY_UPDATE( I_( "OBJ_TYPE_ENTITY_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ERR_MSG_RULES( I_( "OBJ_TYPE_ERR_MSG_RULES" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_EXCH_RATE( I_( "OBJ_TYPE_EXCH_RATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FREE_UNIT( I_( "OBJ_TYPE_FREE_UNIT" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND( I_( "OBJ_TYPE_FUND" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_BANK_LIST( I_( "OBJ_TYPE_FUND_BANK_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUNDTYPE_LIST( I_( "OBJ_TYPE_FUNDTYPE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_DETAIL( I_( "OBJ_TYPE_FUND_DETAIL" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_DETAILS( I_( "OBJ_TYPE_FUND_DETAILS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_INFO( I_( "OBJ_TYPE_FUND_INFO" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_LIST( I_( "OBJ_TYPE_FUND_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_MASTER( I_( "OBJ_TYPE_FUND_MASTER" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_ORIGIN_EXCEPTION_LIST( I_( "OBJ_TYPE_FUND_ORIGIN_EXCEPTION_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_PRICE_LIST( I_( "OBJ_TYPE_FUND_PRICE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_TO( I_( "OBJ_TYPE_FUND_TO" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_GROUP( I_( "OBJ_TYPE_GROUP" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_GROUPFUNDLIST( I_( "OBJ_TYPE_GROUPFUNDLIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_GUARANTEEINFO( I_( "OBJ_TYPE_GUARANTEEINFO" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_HISTORICAL_ACCOUNT( I_( "OBJ_TYPE_HISTORICAL_ACCOUNT" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_HISTORICAL_MARKET_VALUE( I_( "OBJ_TYPE_HISTORICAL_MARKET_VALUE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_HYPOTHETICALRED( I_( "OBJ_TYPE_HYPOTHETICALRED" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_INTEREST_ACCRUAL( I_( "OBJ_TYPE_INTEREST_ACCRUAL" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_INTERMEDIARY( I_( "OBJ_TYPE_INTERMEDIARY" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_JADVISORSUMM( I_( "OBJ_TYPE_JADVISORSUMM" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_JADVISORTRANS( I_( "OBJ_TYPE_JADVISORTRANS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_JFUNDINDIV( I_( "OBJ_TYPE_JFUNDINDIV" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_JSHRSUMM( I_( "OBJ_TYPE_JSHRSUMM" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_LANGUAGE_LIST( I_( "OBJ_TYPE_LANGUAGE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_LEGAL_ENTITY_LIST( I_( "OBJ_TYPE_LEGAL_ENTITY_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_LIP_RATE_EXIST( I_( "OBJ_TYPE_LIP_RATE_EXIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MARITAL_STATUS_LIST( I_( "OBJ_TYPE_MARITAL_STATUS_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MARKETINGCODE_LIST( I_( "OBJ_TYPE_MARKETINGCODE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MASTER_CONTRACT( I_( "OBJ_TYPE_MASTER_CONTRACT" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MC_ORG_EVENT( I_( "OBJ_TYPE_MC_ORG_EVENT" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MC_TRN_TYPE( I_( "OBJ_TYPE_MC_TRN_TYPE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MFACCOUNT ( I_( "OBJ_TYPE_MFACCOUNT " ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MFACCOUNT_HOLDINGS( I_( "OBJ_TYPE_MFACCOUNT_HOLDINGS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MFACCOUNT_UPDATE( I_( "OBJ_TYPE_MFACCOUNT_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MGMTCO( I_( "OBJ_TYPE_MGMTCO" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MGMT_CO_OPTIONS( I_( "OBJ_TYPE_MGMT_CO_OPTIONS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MINMAX( I_( "OBJ_TYPE_MINMAX" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_NOMINEE_INTER_ADDRESS( I_( "OBJ_TYPE_NOMINEE_INTER_ADDRESS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PASSWORD( I_( "OBJ_TYPE_PASSWORD" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PENDING_TRADE( I_( "OBJ_TYPE_PENDING_TRADE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PENDING_TRADE_DETAILS( I_( "OBJ_TYPE_PENDING_TRADE_DETAILS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PERSISTENCE_START( I_( "OBJ_TYPE_PERSISTENCE_START" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PERSISTENCE_STOP( I_( "OBJ_TYPE_PERSISTENCE_STOP" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PHONE_NUMBER_TYPE_LIST( I_( "OBJ_TYPE_PHONE_NUMBER_TYPE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PLAN_MANAGER( I_( "OBJ_TYPE_PLAN_MANAGER" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PREFIX_TYPE_LIST( I_( "OBJ_TYPE_PREFIX_TYPE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PRICETYPE_LIST( I_( "OBJ_TYPE_PRICETYPE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PT_ALLOCATIONS( I_( "OBJ_TYPE_PT_ALLOCATIONS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PURCHASE( I_( "OBJ_TYPE_PURCHASE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_RECIPIENT_TYPE( I_( "OBJ_TYPE_RECIPIENT_TYPE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_REDCODEBYTAXTYPE( I_( "OBJ_TYPE_REDCODEBYTAXTYPE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_REMARKS( I_( "OBJ_TYPE_REMARKS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_REMARKS_UPDATE( I_( "OBJ_TYPE_REMARKS_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_RESPINFO( I_( "OBJ_TYPE_RESPINFO" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_RESPTRANSACTIONS_DETAILS( I_( "OBJ_TYPE_RESPTRANSACTIONS_DETAILS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_RRIF_LIF_LRIF_ALLOC( I_( "OBJ_TYPE_RRIF_LIF_LRIF_ALLOC" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_RRIF_LIF_LRIF_INFO( I_( "OBJ_TYPE_RRIF_LIF_LRIF_INFO" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_RRIF_LIF_LRIF_INFO_UPDATE( I_( "OBJ_TYPE_RRIF_LIF_LRIF_INFO_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_RRIF_LIF_LRIF_PAYMENT_CALC( I_( "OBJ_TYPE_RRIF_LIF_LRIF_PAYMENT_CALC" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SEQ_FUND_VALIDATION( I_( "OBJ_TYPE_SEQ_FUND_VALIDATION" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SETTLEMENT_LOCATION_ACCTLVL_LIST( I_("OBJ_TYPE_SETTLEMENT_LOCATION_ACCTLVL_LIST") );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SETTLEMENT_LOCATION_SYSLVL_LIST( I_("OBJ_TYPE_SETTLEMENT_LOCATION_SYSLVL_LIST") );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SETTLEMENT_UPDATE( I_( "OBJ_TYPE_SETTLEMENT_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SHAREHOLDER( I_( "OBJ_TYPE_SHAREHOLDER" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SHAREHOLDER_UPDATE( I_( "OBJ_TYPE_SHAREHOLDER_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SUBSCRIPTION_LIST( I_( "OBJ_TYPE_SUBSCRIPTION_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SUBSCRIPTION_UPDATE( I_( "OBJ_TYPE_SUBSCRIPTION_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SUBSCRIPTION_VALIDATION_LIST( I_( "OBJ_TYPE_SUBSCRIPTION_VALIDATION_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SYSTEMATIC( I_( "OBJ_TYPE_SYSTEMATIC" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SYSTEMATICS_UPDATE( I_( "OBJ_TYPE_SYSTEMATICS_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SYSTEMATIC_ALLOCATIONS( I_( "OBJ_TYPE_SYSTEMATIC_ALLOCATIONS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TAXRATES( I_( "OBJ_TYPE_TAXRATES" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TAXTYPE_RULE( I_( "OBJ_TYPE_TAXTYPE_RULE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TRADES_LIST( I_( "OBJ_TYPE_TRADES_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TRANSACTIONS( I_( "OBJ_TYPE_TRANSACTIONS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TRANSACTIONS_DETAILS( I_( "OBJ_TYPE_TRANSACTIONS_DETAILS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TRANSACTION_BANK_INSTRUCTION( I_( "OBJ_TYPE_TRANSACTION_BANK_INSTRUCTION" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TRANSACTION_DETAILS( I_( "OBJ_TYPE_TRANSACTION_DETAILS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TRANSLATION( I_( "OBJ_TYPE_TRANSLATION" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TRANS_NUM( I_( "OBJ_TYPE_TRANS_NUM" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_USER_ACCESS( I_( "OBJ_TYPE_USER_ACCESS" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_VERIFICATIONCONF( I_( "OBJ_TYPE_VERIFICATIONCONF" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_WHERE_USED( I_( "OBJ_TYPE_WHERE_USED" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SETTLEMENT_SEARCH( I_( "OBJ_TYPE_SETTLEMENT_SEARCH" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_AMS_GLOBAL( I_( "OBJ_TYPE_AMS_GLOBAL" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_REPORT ( I_( "OBJ_TYPE_REPORT" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FEEPARAM_SYSTEM ( I_( "OBJ_TYPE_FEEPARAM_SYSTEM" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FEEPARAM_SYS_UPDATE ( I_( "OBJ_TYPE_FEEPARAM_SYSTEM_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PROTECTED_FUND_LIST( I_( "OBJ_TYPE_PROTECTED_FUND_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MKT_INDEX_MASTER( I_( "OBJ_TYPE_MKT_INDEX_MASTER" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_RESET_INSTR( I_( "OBJ_TYPE_RESET_INSTR" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_HISTORICAL_INFO_LIST( I_( "OBJ_TYPE_HISTORICAL_INFO_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MKT_INDEX_VALUES( I_( "OBJ_TYPE_MKT_INDEX_VALUES" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_BROKER_AMS_SEARCH( I_( "OBJ_TYPE_BROKER_AMS_SEARCH" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_REDEMPTION_VALIDATION( I_( "OBJ_TYPE_REDEMPTION_VALIDATION" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MANUAL_DIVIDEND_LIST( I_("OBJ_TYPE_MANUAL_DIVIDEND_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_BANK_INSTRUCTIONS_LIST_REPOSITORY( I_("OBJ_TYPE_FUND_BANK_INSTRUCTIONS_LIST_REPOSITORY" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DISTRIBUTOR_BANK_INSTR( I_("OBJ_TYPE_DISTRIBUTOR_BANK_INSTR" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PAY_TO_ENTITY_LIST( I_("OBJ_TYPE_PAY_TO_ENTITY_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PAYMENT_INSTRUCTIONS_LIST( I_("OBJ_TYPE_PAYMENT_INSTRUCTIONS_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DAILY_TRANSACTIONS_FEES_REPOSITORY( I_("OBJ_TYPE_DAILY_TRANSACTIONS_FEES_REPOSITORY" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DAILY_TRANSACTIONS_FEE_LIST( I_("OBJ_TYPE_DAILY_TRANSACTIONS_FEE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SHR_FUND_SPONSOR_AGREEMENT_LIST( I_("OBJ_TYPE_SHR_FUND_SPONSOR_AGREEMENT_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TAX_EXEMPT_AUTHORIZATION_LIST( I_("OBJ_TYPE_TAX_EXEMPT_AUTHORIZATION_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FEE_MODEL_LIST( I_("OBJ_TYPE_FEE_MODEL_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_SPONSOR_FEE_MODEL_LIST( I_("OBJ_TYPE_FUND_SPONSOR_FEE_MODEL_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_REMARK_CONTAINER( I_("OBJ_TYPE_REMARK_CONTAINER" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FUND_BROKER_LIST( I_("OBJ_TYPE_FUND_BROKER_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_AGGREGATED_ORDER_LIST( I_("OBJ_TYPE_AGGREGATED_ORDER_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SHR_FUND_BROKER_LIST( I_("OBJ_TYPE_SHR_FUND_BROKER_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MSG_PROCESS_LIST( I_("OBJ_TYPE_MSG_PROCESS_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MSG_ACTIVITY_LIST( I_("OBJ_TYPE_MSG_ACTIVITY_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MSG_EVENT_LIST( I_("OBJ_TYPE_MSG_EVENT_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MSG_DETAIL_LIST( I_("OBJ_TYPE_MSG_DETAIL_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_MSG_ENVELOPE_LIST( I_("OBJ_TYPE_MSG_ENVELOPE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FILE_SEARCH( I_("OBJ_TYPE_FILE_SEARCH" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TRANS_CANCEL( I_("OBJ_TYPE_TRANS_CANCEL" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_USER_DEF_MAT_LIST( I_("OBJ_TYPE_USER_DEF_MAT_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_USER_DEF_MAT_LIST_UPDATE( I_("OBJ_TYPE_USER_DEF_MAT_LIST_UPDATE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_CONFIRM_REPRINT( I_("OBJ_TYPE_CONFIRM_REPRINT" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_BULK_CANCEL( I_("OBJ_TYPE_BULK_CANCEL" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_SAVINGS_DIRECTIVE( I_("OBJ_TYPE_SAVINGS_DIRECTIVE" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TRANS_HIST_DILUTION_ALLOC_LIST( I_("OBJ_TYPE_TRANS_HIST_DILUTION_ALLOC_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_AGENCY_NEGATIVE_COMMISSION( I_("OBJ_TYPE_AGENCY_NEGATIVE_COMMISSION" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_RRIF_UNUSED_MAX_AMOUNT( I_("OBJ_TYPE_RRIF_UNUSED_MAX_AMOUNT" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_PAYMENT_INSTRUCTION_VALIDATION( I_("OBJ_TYPE_PAYMENT_INSTRUCTION_VALIDATION" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_CLONE_ACCOUNT( I_("OBJ_TYPE_CLONE_ACCOUNT" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_DISTRIB_OPTIONS( I_("OBJ_TYPE_DISTRIB_OPTIONS" ) ); 
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_AMS_ACCT_LEVEL( I_("OBJ_TYPE_AMS_ACCT_LEVEL" ) ); 
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FREQUENCY( I_("OBJ_TYPE_FREQUENCY" ) ); 
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACCT_SETTLEMENT_RULE( I_("OBJ_TYPE_ACCT_SETTLEMENT_RULE" ) ); 
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_CHEQUE_LIST( I_("OBJ_TYPE_CHEQUE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_INVESTMENT_HISTORY( I_("OBJ_TYPE_INVESTMENT_HISTORY" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_REG_AGENT_BANKLIST(I_("OBJ_TYPE_REG_AGENT_BANKLIST"));
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_AGENT_BANK_INSTRUCTIONS_LIST_REPOSITORY(I_("OBJ_TYPE_AGENT_BANK_INSTRUCTIONS_LIST_REPOSITORY"));
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_HOLDING_COMP ( I_( "OBJ_TYPE_HOLDING_COMP" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_FIN_INST_REG_DETL_LIST ( I_( "OBJ_TYPE_FIN_INST_REG_DETL_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACCT_REG_DETAILS_LIST ( I_( "OBJ_TYPE_ACCT_REG_DETAILS_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_TRADEVERIFICATION_LIST ( I_( "OBJ_TYPE_TRADEVERIFICATION_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_ACCT_ROUNDING_RULE_LIST ( I_( "OBJ_TYPE_ACCT_ROUNDING_RULE_LIST" ) );
CLASS_EXPORT BF_OBJ_TYPE OBJ_TYPE_BROKERCUTOFF_LIST ( I_( "OBJ_TYPE_BROKERCUTOFF_LIST" ) );

//*****************************************************************************
// Revision Control Entries
//*****************************************************************************
//
// $Log:   Y:/VCS/BF iFAST/ifastcbo/ifastcboids.cpp-arc  $
// 
//    Rev 1.48   Apr 03 2012 22:08:52   wp040039
// PETP0187485-Registartion Agent  Banking
// 
//    Rev 1.47   Nov 18 2011 18:41:10   wp040100
// P0186477/FN03 - GIA - Investment History Changes
// 
//    Rev 1.46   Sep 08 2008 15:46:28   jankovii
// PET 5517 FN71 - Stale Cheque.
// 
//    Rev 1.45   Mar 11 2008 20:11:50   daechach
// PET2385FN02&07 - Account Level Settlement Periods and Currency Holiday - Check in for Build.
// 
//    Rev 1.44   Jun 20 2007 12:07:12   porteanm
// PET2360 FN02 - Added AMS acct level and Frequency support.
// 
//    Rev 1.43   Jun 14 2007 11:40:46   porteanm
// PET 2360 FN48 - Cleanup.
// 
//    Rev 1.42   Jun 14 2007 11:38:20   porteanm
// PET 2360 FN48 - GAPS 48 - BKK.
// 
//    Rev 1.41   Nov 08 2006 17:29:34   popescu
// PET 2281/FN 01- copy account for TA 
// 
//    Rev 1.40   Oct 19 2006 17:49:38   ZHANGCEL
// PET 2212 FN13 -- Edit check for Redemption/Distribution pair
// 
//    Rev 1.39   Sep 06 2006 11:07:00   porteanm
// PET2216 FN35 - RRIF Locked-In products - RRIF Unused Amt.
// 
//    Rev 1.38   May 31 2006 17:55:46   porteanm
// PET2132 FN03 - Edit check for Negative Commission.
// 
//    Rev 1.37   Dec 13 2005 19:17:42   porteanm
// Incident 421704 - gap - TranshistDilutionAlloc update support.
// 
//    Rev 1.36   Nov 29 2005 15:27:08   AGUILAAM
// PET1228_FN02: EUSD Phase 2
// 
//    Rev 1.35   Nov 05 2005 14:36:18   porteanm
// PET 1286 FN01 - Bulk Cancellation.
// 
//    Rev 1.34   May 25 2005 14:59:24   porteanm
// PET OPC Confirm Reprint support.
// 
//    Rev 1.33   Mar 06 2005 21:30:10   hernando
// PET1024 FN02 - Added USER_DEF_MAT_LIST and USER_DEF_MAT_LIST_UPDATE.
// 
//    Rev 1.32   Mar 03 2005 12:02:24   Fengyong
// PET1117 FN5 - Add transaction cancellation
// 
//    Rev 1.31   Feb 24 2005 17:30:16   ZHANGCEL
// PET1117- FN66-68 - Added MSG_ENELOPE_LIST AND FILE_SEARCH
// 
//    Rev 1.30   Feb 20 2005 16:43:00   hernando
// PET1117 FN66-68 - Added MSG_PROCESS_LIST, MSG_ACTIVITY_LIST, MSG_EVENT_LIST, and MSG_DETAIL_LIST.
// 
//    Rev 1.29   Nov 14 2004 14:48:22   purdyech
// PET910 - .NET Conversion
// 
//    Rev 1.28   Nov 04 2004 11:23:14   VADEANUM
// PET1117 FN08 - Shareholder Fund Broker support.
// 
//    Rev 1.27   Nov 04 2004 11:05:14   ZHANGCEL
// PET1117/08 Add new object type for the Aggregated Order
// 
//    Rev 1.26   Oct 14 2004 11:27:12   VADEANUM
// Synched up with 1.24.1.0. for Yingbao
// 
//    Rev 1.25   Oct 08 2004 17:10:30   FENGYONG
// PET1117 FN54 - FundBroker static
// 
//    Rev 1.24   Aug 13 2004 17:10:42   YINGBAOL
// PEt1117:FN5 Add new Object type fot fee model
// 
//    Rev 1.23   Aug 06 2004 17:29:38   ZHANGCEL
// PET 1082 FNrlc -- Tax Exempt Authorization support
// 
//    Rev 1.22   Jul 26 2004 10:29:04   VADEANUM
// PET1117 FN01 - Shareholder Static Data support.
// 
//    Rev 1.21   Jan 28 2004 14:05:50   popescu
// PET 859, FN23, Added DailyTransactionsFees corresponding files and ids:
// DailyTransactionsFeeList.cpp +hpp
// DailyTransactionsFee.cpp +hpp
// DailyTransactionsFeesRepository.cpp +hpp
// DSTCDailyTransactionsFeesTrxnBuilder.cpp +hpp
// 
//    Rev 1.20   Nov 07 2003 16:09:58   HERNANDO
// Added OBJ_TYPE_SETTLEMENT_LOCATION_ACCTLVL_LIST and OBJ_TYPE_SETTLEMENT_LOCATION_SYSLVL_LIST.
// 
//    Rev 1.19   Oct 24 2003 17:20:14   popescu
// CIBC PET 809, FN 13
// 
//    Rev 1.18   Oct 04 2003 16:00:22   popescu
// CIBC PET 809, FN 13;
// also cleaned-up BankSearch and BankList objects,
// replaced with FinancialInstitutionList
// 
//    Rev 1.17   Jul 01 2003 18:09:44   popescu
// Added the payment instruction dialog, process and CBO's, as well as the DistributorRepository builder
// 
//    Rev 1.16   Jun 27 2003 18:13:48   popescu
// Pay To Entity feature, dialog, process and CBO
// 
//    Rev 1.15   May 31 2003 11:55:06   popescu
// RRIF bank work
// 
//    Rev 1.14   May 23 2003 14:39:12   HERNANDO
// Added OBJ_TYPE_MANUAL_DIVIDEND_LIST.
// 
//    Rev 1.13   May 02 2003 18:15:46   ZHANGCEL
// PTS 10016099: added OBJ_TYPE_RECEMPTION_VALIDATION
// 
//    Rev 1.12   Mar 03 2003 17:24:08   FENGYONG
// Add brokerlevel AMS
// 
//    Rev 1.11   Jan 29 2003 12:12:06   HERNANDO
// Added OBJ_TYPE_MARKET_INDEX_VALUES.
// 
//    Rev 1.10   Jan 26 2003 16:12:34   popescu
// Historical Info ids
// 
//    Rev 1.9   Jan 26 2003 15:31:20   HSUCHIN
// added reset instructions
// 
//    Rev 1.8   Jan 23 2003 08:54:54   HERNANDO
// Added OBJ_TYPE_MARKET_INDEX_MASTER.
// 
//    Rev 1.7   Jan 10 2003 10:22:52   popescu
// new ids for protected fund cbo
// 
//    Rev 1.6   Jan 09 2003 14:38:36   popescu
// Second revision, make things compilable
// 
//    Rev 1.5   Jan 09 2003 10:10:30   YINGBAOL
// add OBJ_TYPE_FEEPARAM_SYSTEM etc.
// 
//    Rev 1.4   Nov 27 2002 11:44:22   HSUCHIN
// added new key for reports
// 
//    Rev 1.3   Nov 19 2002 16:21:18   YINGBAOL
// Object_type_AMS_Global
// 
//    Rev 1.2   Nov 18 2002 14:02:52   PURDYECH
// BF_OBJ_TYPE semantics had a little change ...
// 
//    Rev 1.1   Nov 18 2002 10:54:34   PURDYECH
// BFObjectKey changes.
//
