#pragma once

#include <bfcbo\hosttransactioncontainer.hpp>

#undef IFASTCBO_LINKAGE
#ifdef IFASTCBO_DLL
   #define IFASTCBO_LINKAGE CLASS_EXPORT
#else
   #define IFASTCBO_LINKAGE CLASS_IMPORT
#endif

// Add new extern references
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_SHAREHOLDER;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_SHAREHOLDER;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ACCOUNT;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ACCOUNT;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ENTITY;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ENTITY;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ENTITY_IDS;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ENTITY_IDS;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ACCOUNT_ENTITY;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ACCOUNT_ENTITY;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ADDRESS;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ADDRESS;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_MAILING;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_MAILING;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_AS_PENSION;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_AS_PENSION;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ESOP;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ESOP;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_FEE_PARAM;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_FEE_PARAM;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_SETTLEMENT;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_MAILING_OVERRIDE;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_MAILING_OVERRIDE;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ACCOUNT_CATEGORY;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ACCOUNT_CATEGORY;
extern IFASTCBO_LINKAGE TRXN_TYPE CLONE_ACCOUNT;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ACCOUNT_GUARNT_GUARD_OPTN;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ACCOUNT_GUARNT_GUARD_OPTN;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ACCOUNT_REGULATORY_DETAILS;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ACCOUNT_REGULATORY_DETAILS;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ENTITY_REGULATORY_DETAILS;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ENTITY_REGULATORY_DETAILS;
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ENTITY_REGULATORY_JURIS_DETAILS;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ENTITY_REGULATORY_JURIS_DETAILS;
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_TRADEVRIFICATION; 
extern IFASTCBO_LINKAGE TRXN_TYPE NEW_ENTITY_RISK; 
extern IFASTCBO_LINKAGE TRXN_TYPE UPDATE_ENTITY_RISK; 
//******************************************************************************
//              Revision Control Entries
//******************************************************************************
//
// $Log:   Y:/VCS/BF iFAST/ifastcbo/ifasthosttransactioncontainer.hpp-arc  $
//
//   Rev 1.5   Sep 17 2010 07:54:36   kitticha
//PETP0173756 FN02 Don't Bust the Rules.
//

