// Computer Generated Condition File for Module: bfconmgr


#pragma message("including "__FILE__ )
#ifndef PLATFORM_H
#include "platform.h"
#endif


namespace CND
{
  CLASS_EXPORT const I_CHAR *BFCONMGR_CONDITION = I_( "BFCONMGR" );

  //extern CLASS_EXPORT const long ERR_PRIVCONN_CONNECT_FAILED = 40000059;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_NOTIFY_FAILED = 40000060;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_CREATE_FAILED = 40000061;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_CREATE_EVENT = 40000062;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_DISCONNECT_FAILED = 40000063;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_WAITEVENT_FAILED = 40000064;
  //extern CLASS_EXPORT const long ERR_PRIVCONN_REQUEST_FAILED = 40000065;
  //extern CLASS_EXPORT const long ERR_HOST_CONNECTION_MGR_NOT_FOUND = 40000074;
  //extern CLASS_EXPORT const long ERR_VMCONNECTION_CREATE_EVENT = 40000084;
  //extern CLASS_EXPORT const long ERR_VMCONNECTION_CREATE_FAILED = 40000085;
  //extern CLASS_EXPORT const long ERR_VMCONNECTION_CONNECT_FAILED = 40000086;
  //extern CLASS_EXPORT const long ERR_VMCONNECTION_NOTIFY_FAILED = 40000087;
  //extern CLASS_EXPORT const long ERR_VMCONNECTION_DISCONNECT_FAILED = 40000088;
  //extern CLASS_EXPORT const long ERR_VMCONNECTION_REQUEST_FAILED = 40000089;
  //extern CLASS_EXPORT const long ERR_VMCONNECTION_WAITEVENT_FAILED = 40000090;
  //extern CLASS_EXPORT const long ERR_VM = 40000091;
  //extern CLASS_EXPORT const long BFCONMGR_CND_VERSION = 40000277;

	extern CLASS_EXPORT const long BFCONMGR_CND_VERSION = 100001;
	extern CLASS_EXPORT const long ERR_HOST_CONNECTION_MGR_NOT_FOUND = 100002;
	extern CLASS_EXPORT const long ERR_PRIVCONN_CONNECT_FAILED = 100003;
	extern CLASS_EXPORT const long ERR_PRIVCONN_CREATE_EVENT = 100004;
	extern CLASS_EXPORT const long ERR_PRIVCONN_DISCONNECT_FAILED = 100005;
	extern CLASS_EXPORT const long ERR_PRIVCONN_NOTIFY_FAILED = 100006;
	extern CLASS_EXPORT const long ERR_PRIVCONN_REQUEST_FAILED = 100007;
	extern CLASS_EXPORT const long ERR_VM = 100008;
	extern CLASS_EXPORT const long ERR_VMCONNECTION_CONNECT_FAILED = 100009;
	extern CLASS_EXPORT const long ERR_VMCONNECTION_CREATE_EVENT = 100010;
	extern CLASS_EXPORT const long ERR_VMCONNECTION_CREATE_FAILED = 100011;
	extern CLASS_EXPORT const long ERR_VMCONNECTION_DISCONNECT_FAILED = 100012;
	extern CLASS_EXPORT const long ERR_VMCONNECTION_NOTIFY_FAILED = 100013;
	extern CLASS_EXPORT const long ERR_VMCONNECTION_REQUEST_FAILED = 100014;
	extern CLASS_EXPORT const long ERR_VMCONNECTION_WAITEVENT_FAILED = 100015;

    // Defined in bfdbrkr module, but used here as well
	extern CLASS_EXPORT const long ERR_PRIVCONN_CREATE_FAILED = 300006;
	extern CLASS_EXPORT const long ERR_PRIVCONN_WAITEVENT_FAILED = 300010;
}

