// Computer Generated Condition File for Module: bpbase


#pragma message("including "__FILE__ )
#ifndef PLATFORM_H
#include "platform.h"
#endif


namespace CND
{
  CLASS_EXPORT const I_CHAR *BPBASE_CONDITION = I_( "BPBASE" );

  //extern CLASS_EXPORT const long BP_ERR_CANNOT_SET_CBO = 40000034;
  //extern CLASS_EXPORT const long BP_ERR_CBO_NOT_SET = 40000035;
  //extern CLASS_EXPORT const long BP_ERR_COMMAND_NOT_FOUND = 40000036;
  //extern CLASS_EXPORT const long BP_ERR_COULD_NOT_GET_SUBSESSION = 40000037;
  //extern CLASS_EXPORT const long BP_ERR_DUPLICATE_DISPATCHER = 40000038;
  //extern CLASS_EXPORT const long BP_ERR_DUPLICATE_KEY_IN_FIELD_DETAILS = 40000039;
  //extern CLASS_EXPORT const long BP_ERR_FIELD_DEFINED_IN_LIST_AND_CBO = 40000040;
  //extern CLASS_EXPORT const long BP_ERR_FIELD_NOT_FOUND = 40000041;
  //extern CLASS_EXPORT const long BP_ERR_GETFIELD_FAILED = 40000042;
  //extern CLASS_EXPORT const long BP_ERR_ID_OUT_OF_RANGE = 40000043;
  //extern CLASS_EXPORT const long BP_ERR_ID_OUT_OF_RANGE_FOR_FIELD = 40000044;
  //extern CLASS_EXPORT const long BP_ERR_INVALID_METHOD_CALL = 40000045;
  //extern CLASS_EXPORT const long BP_ERR_ITEM_NOT_VALID = 40000046;
  //extern CLASS_EXPORT const long BP_ERR_LIST_NOT_FOUND = 40000047;
  //extern CLASS_EXPORT const long BP_ERR_LIST_NOT_VALID = 40000048;
  //extern CLASS_EXPORT const long BP_ERR_MUST_RUN_MODAL = 40000049;
  //extern CLASS_EXPORT const long BP_ERR_MUST_RUN_MODELESS = 40000050;
  //extern CLASS_EXPORT const long BP_ERR_NO_DATA_AREA = 40000051;
  //extern CLASS_EXPORT const long BP_ERR_NO_FIELD_MATCH = 40000052;
  //extern CLASS_EXPORT const long BP_ERR_NO_PARENT_EXISTS = 40000053;
  //extern CLASS_EXPORT const long BP_ERR_SETFIELD_FAILED = 40000054;
  //extern CLASS_EXPORT const long BP_ERR_UNKNOWN_EXCEPTION = 40000055;
  //extern CLASS_EXPORT const long BP_ERR_USER_CHANGE_PASSWORD = 40000056;
  //extern CLASS_EXPORT const long BP_NO_OF_DAYS_PRIOR_TO_CHANGE_PASSWORD = 40000057;
  //extern CLASS_EXPORT const long BPBASE_CND_VERSION = 40000273;
  //extern CLASS_EXPORT const long BP_ERR_SEH_EXCEPTION = 40000282;

	extern CLASS_EXPORT const long BP_ERR_CANNOT_SET_CBO = 500001;
	extern CLASS_EXPORT const long BP_ERR_CBO_NOT_SET = 500002;
	extern CLASS_EXPORT const long BP_ERR_COMMAND_NOT_FOUND = 500003;
	extern CLASS_EXPORT const long BP_ERR_COULD_NOT_GET_SUBSESSION = 500004;
	extern CLASS_EXPORT const long BP_ERR_DUPLICATE_DISPATCHER = 500005;
	extern CLASS_EXPORT const long BP_ERR_DUPLICATE_KEY_IN_FIELD_DETAILS = 500006;
	extern CLASS_EXPORT const long BP_ERR_FIELD_DEFINED_IN_LIST_AND_CBO = 500007;
	extern CLASS_EXPORT const long BP_ERR_FIELD_NOT_FOUND = 500008;
	extern CLASS_EXPORT const long BP_ERR_GETFIELD_FAILED = 500009;
	extern CLASS_EXPORT const long BP_ERR_ID_OUT_OF_RANGE = 500010;
	extern CLASS_EXPORT const long BP_ERR_ID_OUT_OF_RANGE_FOR_FIELD = 500011;
	extern CLASS_EXPORT const long BP_ERR_INVALID_METHOD_CALL = 500012;
	extern CLASS_EXPORT const long BP_ERR_ITEM_NOT_VALID = 500013;
	extern CLASS_EXPORT const long BP_ERR_LIST_NOT_FOUND = 500014;
	extern CLASS_EXPORT const long BP_ERR_LIST_NOT_VALID = 500015;
	extern CLASS_EXPORT const long BP_ERR_MUST_RUN_MODAL = 500016;
	extern CLASS_EXPORT const long BP_ERR_MUST_RUN_MODELESS = 500017;
	extern CLASS_EXPORT const long BP_ERR_NO_DATA_AREA = 500018;
	extern CLASS_EXPORT const long BP_ERR_NO_FIELD_MATCH = 500019;
	extern CLASS_EXPORT const long BP_ERR_NO_PARENT_EXISTS = 500020;
	extern CLASS_EXPORT const long BP_ERR_SEH_EXCEPTION = 500021;
	extern CLASS_EXPORT const long BP_ERR_SETFIELD_FAILED = 500022;
	extern CLASS_EXPORT const long BP_ERR_UNKNOWN_EXCEPTION = 500023;
	extern CLASS_EXPORT const long BP_ERR_USER_CHANGE_PASSWORD = 500024;
	extern CLASS_EXPORT const long BP_NO_OF_DAYS_PRIOR_TO_CHANGE_PASSWORD = 500025;
	extern CLASS_EXPORT const long BPBASE_CND_VERSION = 500026;
}

