// Field IDs and DataIDs for DataSet DSTC0474.REQRepeat_Record
// ViewsGenerator: This file was generated by ViewsGenerator - Version 1.0.0.0
// ViewsGenerator: Generated on : Friday, November 04, 2016 12:10:01


#pragma once
// include the repeat section header file (if applicable)

namespace ifds
{
    extern __declspec(dllimport) const BFDataId DSTC0474_REQRepeat_Record;
    extern __declspec(dllimport) const BFTextFieldId AllocRunMode;
    extern __declspec(dllimport) const BFTextFieldId RegTransferAllocUUID;
    extern __declspec(dllimport) const BFTextFieldId FundCode;
    extern __declspec(dllimport) const BFTextFieldId ClassCode;
    extern __declspec(dllimport) const BFDecimalFieldId AllocAmount;
    extern __declspec(dllimport) const BFDecimalFieldId Version;
    extern __declspec(dllimport) const BFDecimalFieldId Commission;
}
