// Field IDs and DataIDs for DataSet DSTC0337.VWRepeat_Record
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#pragma once
// include the repeat section header file (if applicable)
namespace ifds
{
   extern __declspec(dllimport) const BFDataId DSTC0337_VWRepeat_Record;
   extern __declspec(dllimport) const BFNumericFieldId TransNum;
   extern __declspec(dllimport) const BFTextFieldId RvCode;
   extern __declspec(dllimport) const BFTextFieldId OnStmt;
   extern __declspec(dllimport) const BFTextFieldId Accountable;
   extern __declspec(dllimport) const BFTextFieldId ConfirmRequired;
   extern __declspec(dllimport) const BFTextFieldId CancelCheque;
   extern __declspec(dllimport) const BFTextFieldId Remarks1;
   extern __declspec(dllimport) const BFTextFieldId Remarks2;
   extern __declspec(dllimport) const BFTextFieldId Remarks3;
   extern __declspec(dllimport) const BFTextFieldId Batch;
   extern __declspec(dllimport) const BFDecimalFieldId Trace;
   extern __declspec(dllimport) const BFTextFieldId TransType;
   extern __declspec(dllimport) const BFTextFieldId TranStatus;
   extern __declspec(dllimport) const BFTextFieldId Username;
   extern __declspec(dllimport) const BFTextFieldId ModUser;
   extern __declspec(dllimport) const BFDateFieldId ModDate;
   extern __declspec(dllimport) const BFTextFieldId VerifiedBy;
   extern __declspec(dllimport) const BFDateFieldId VerifyDate;
   extern __declspec(dllimport) const BFDateFieldId ProcessDate;
   extern __declspec(dllimport) const BFNumericFieldId TransId;
   extern __declspec(dllimport) const BFDecimalFieldId Version;
   extern __declspec(dllimport) const BFTextFieldId ModPermission;
   extern __declspec(dllimport) const BFTextFieldId CancellationType;
   extern __declspec(dllimport) const BFDateFieldId TradeDate;
   extern __declspec(dllimport) const BFTextFieldId Fund;
   extern __declspec(dllimport) const BFTextFieldId Class;
   extern __declspec(dllimport) const BFTextFieldId Rebook;
   extern __declspec(dllimport) const BFTextFieldId FundISIN;
   extern __declspec(dllimport) const BFTextFieldId FundWKN;
   extern __declspec(dllimport) const BFDecimalFieldId TradeAdjustID;
   extern __declspec(dllimport) const BFTextFieldId MCHFileIndicator;
   extern __declspec(dllimport) const BFTextFieldId SecRecFileIndicator;
   extern __declspec(dllimport) const BFTextFieldId RbkMCHFileIndicator;
   extern __declspec(dllimport) const BFTextFieldId RbkSecRecFileIndicator;
   extern __declspec(dllimport) const BFTextFieldId ESGSettle;
   extern __declspec(dllimport) const BFTextFieldId RefundPayType;
   extern __declspec(dllimport) const BFTextFieldId RefundOption;
   extern __declspec(dllimport) const BFDateFieldId EventReceiptDate;
   extern __declspec(dllimport) const BFTextFieldId EventReceiptTime;
}

