// Field IDs and DataIDs for DataSet DSTC0239.VWRepeat_Record
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#pragma once
// include the repeat section header file (if applicable)
namespace ifds
{
   extern __declspec(dllimport) const BFDataId DSTC0239_VWRepeat_Record;
   extern __declspec(dllimport) const BFIntegerFieldId ContractID;
   extern __declspec(dllimport) const BFDateFieldId EffectiveDate;
   extern __declspec(dllimport) const BFDateFieldId MaturityDate;
   extern __declspec(dllimport) const BFDecimalFieldId GuarAmt;
   extern __declspec(dllimport) const BFDecimalFieldId GuarUnits;
   extern __declspec(dllimport) const BFNumericFieldId TransId;
   extern __declspec(dllimport) const BFDecimalFieldId TransAmt;
   extern __declspec(dllimport) const BFDecimalFieldId TransUnits;
   extern __declspec(dllimport) const BFIntegerFieldId ResetID;
   extern __declspec(dllimport) const BFDecimalFieldId InstrAmt;
   extern __declspec(dllimport) const BFDateFieldId ContractGapDate;
   extern __declspec(dllimport) const BFDateFieldId ModDate;
   extern __declspec(dllimport) const BFTextFieldId ModUser;
   extern __declspec(dllimport) const BFTextFieldId Username;
   extern __declspec(dllimport) const BFDateFieldId ProcessDate;
   extern __declspec(dllimport) const BFTextFieldId FundCode;
   extern __declspec(dllimport) const BFTextFieldId ClassCode;
   extern __declspec(dllimport) const BFIntegerFieldId ProtContractRId;
   extern __declspec(dllimport) const BFDecimalFieldId MktValue;
   extern __declspec(dllimport) const BFDecimalFieldId GainOrLossAmt;
}

