// Field IDs and DataIDs for DataSet DSTC0475.REQRepeat_Record
// ViewsGenerator: This file was generated by ViewsGenerator - Version 1.0.0.0
// ViewsGenerator: Generated on : Wednesday, December 07, 2016 10:56:22


#pragma once
// include the repeat section header file (if applicable)

namespace ifds
{
    extern __declspec(dllimport) const BFDataId DSTC0475_REQRepeat_Record;
    extern __declspec(dllimport) const BFNumericFieldId ErrorCode;
    extern __declspec(dllimport) const BFTextFieldId ErrorDesc;
    extern __declspec(dllimport) const BFTextFieldId EWI;
    extern __declspec(dllimport) const BFTextFieldId Username;
}
