// Field IDs and DataIDs for DataSet DSTC0061.VWRepeat_Record
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#pragma once
// include the repeat section header file (if applicable)
namespace ifds
{
   extern __declspec(dllimport) const BFDataId DSTC0061_VWRepeat_Record;
   extern __declspec(dllimport) const BFNumericFieldId AccountNum;
   extern __declspec(dllimport) const BFTextFieldId EntityType;
   extern __declspec(dllimport) const BFTextFieldId EntityTypeDesc;
   extern __declspec(dllimport) const BFNumericFieldId ShrNum;
   extern __declspec(dllimport) const BFTextFieldId TaxTypeDesc;
   extern __declspec(dllimport) const BFTextFieldId AcctTypeDesc;
   extern __declspec(dllimport) const BFTextFieldId AcctStatusDesc;
   extern __declspec(dllimport) const BFTextFieldId CurrencyName;
   extern __declspec(dllimport) const BFDecimalFieldId AccountBalance;
   extern __declspec(dllimport) const BFDecimalFieldId EntityTypeSeq;
   extern __declspec(dllimport) const BFTextFieldId AcctDesignation;
   extern __declspec(dllimport) const BFTextFieldId TaxType;
   extern __declspec(dllimport) const BFTextFieldId AcctType;
   extern __declspec(dllimport) const BFTextFieldId AcctStatus;
   extern __declspec(dllimport) const BFTextFieldId Currency;
   extern __declspec(dllimport) const BFTextFieldId RegistrationInfo;
   extern __declspec(dllimport) const BFTextFieldId WhereUse;
   extern __declspec(dllimport) const BFTextFieldId WhereUseCode;
   extern __declspec(dllimport) const BFNumericFieldId RecId;
   extern __declspec(dllimport) const BFDecimalFieldId Version;
   extern __declspec(dllimport) const BFDateFieldId EffectiveDate;
   extern __declspec(dllimport) const BFDateFieldId StopDate;
   extern __declspec(dllimport) const BFNumericFieldId EntityId;
}

