// Field IDs and DataIDs for DataSet DSTC0004.VW
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:58 2015


#pragma once
// include the repeat section header file (if applicable)
#include <ifastdataimpl/dse_dstc0004_vwrepeat_record.hpp>
namespace ifds
{
   extern __declspec(dllimport) const BFDataId DSTC0004_VW;
   extern __declspec(dllimport) const BFTextFieldId MoreAvailable;
   extern __declspec(dllimport) const BFTextFieldId NextKey;
   extern __declspec(dllimport) const BFTextFieldId VerifyReqExist;
   extern __declspec(dllimport) const BFNumericFieldId RepeatCount;
}

