// Field IDs and DataIDs for DataSet DSTC0126.VWRepeat_Record
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#pragma once
// include the repeat section header file (if applicable)
namespace ifds
{
   extern __declspec(dllimport) const BFDataId DSTC0126_VWRepeat_Record;
   extern __declspec(dllimport) const BFTextFieldId FundGroupType;
   extern __declspec(dllimport) const BFTextFieldId FundGroupCode;
   extern __declspec(dllimport) const BFTextFieldId FundCode;
   extern __declspec(dllimport) const BFTextFieldId ClassCode;
   extern __declspec(dllimport) const BFTextFieldId ClassReq;
   extern __declspec(dllimport) const BFTextFieldId FundList;
   extern __declspec(dllimport) const BFTextFieldId BankAcctExist;
   extern __declspec(dllimport) const BFTextFieldId BankAcctCurrency;
}

