// Field IDs and DataIDs for DataSet DSTC0299.VWRepeat_Record
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#pragma once
// include the repeat section header file (if applicable)
namespace ifds
{
   extern __declspec(dllimport) const BFDataId DSTC0299_VWRepeat_Record;
   extern __declspec(dllimport) const BFTextFieldId FundGroup;
   extern __declspec(dllimport) const BFTextFieldId DistribCoopAgrmnt;
   extern __declspec(dllimport) const BFTextFieldId Username;
   extern __declspec(dllimport) const BFDateFieldId ProcessDate;
   extern __declspec(dllimport) const BFTextFieldId ModUser;
   extern __declspec(dllimport) const BFDateFieldId ModDate;
   extern __declspec(dllimport) const BFDateFieldId EffectiveDate;
   extern __declspec(dllimport) const BFTextFieldId FundGroupDesc;
   extern __declspec(dllimport) const BFNumericFieldId RecId;
   extern __declspec(dllimport) const BFDecimalFieldId Version;
}

