// Field IDs and DataIDs for DataSet DSTC0143.VW
// ViewsGenerator: This file was generated by ViewsGenerator - Version 1.0.0.0
// ViewsGenerator: Generated on : Friday, January 18, 2019 14:49:33


#pragma once
// include the repeat section header file (if applicable)
namespace ifds
{
    extern __declspec(dllimport) const BFDataId DSTC0143_VW;
    extern __declspec(dllimport) const BFTextFieldId CurrLIPSetup;
    extern __declspec(dllimport) const BFDecimalFieldId MaxPensionEarning;
    extern __declspec(dllimport) const BFTextFieldId AmountOver;
    extern __declspec(dllimport) const BFTextFieldId UnitHeld;
    extern __declspec(dllimport) const BFTextFieldId FeeDfnExist;
    extern __declspec(dllimport) const BFDecimalFieldId MaxRedFee;
    extern __declspec(dllimport) const BFTextFieldId LLPValMsg;
    extern __declspec(dllimport) const BFTextFieldId TransExist;
    extern __declspec(dllimport) const BFTextFieldId MinWithAgeErr1;
    extern __declspec(dllimport) const BFTextFieldId MinWithAgeErr2;
    extern __declspec(dllimport) const BFTextFieldId PenInfoErr;
    extern __declspec(dllimport) const BFTextFieldId TaxTypeRulErr;
    extern __declspec(dllimport) const BFDecimalFieldId AmtSysCalc;
    extern __declspec(dllimport) const BFTextFieldId RRIFDetlErr;
    extern __declspec(dllimport) const BFTextFieldId LowRemainBal;
    extern __declspec(dllimport) const BFDecimalFieldId RemAmtPayFirst;
    extern __declspec(dllimport) const BFTextFieldId AmntOverMax;
    extern __declspec(dllimport) const BFTextFieldId EurCurrMstr;
    extern __declspec(dllimport) const BFTextFieldId RedCodesErr;
    extern __declspec(dllimport) const BFTextFieldId FundExist;
    extern __declspec(dllimport) const BFDecimalFieldId FundUnits;
    extern __declspec(dllimport) const BFDecimalFieldId ProvRate;
    extern __declspec(dllimport) const BFDecimalFieldId FedRate;
    extern __declspec(dllimport) const BFDecimalFieldId LSIFUnitsAvail;
    extern __declspec(dllimport) const BFTextFieldId AmtOverMin;
    extern __declspec(dllimport) const BFTextFieldId GrossNetType;
}

