// Field IDs and DataIDs for DataSet DSTC0458.VWRepeat_Record
// ViewsGenerator: This file was generated by ViewsGenerator - Version 1.0.0.0
// ViewsGenerator: Generated on : Friday, February 17, 2017 04:37:47


#pragma once
// include the repeat section header file (if applicable)

namespace ifds
{
    extern __declspec(dllimport) const BFDataId DSTC0458_VWRepeat_Record;
    extern __declspec(dllimport) const BFTextFieldId EntRegJurisDetlUUID;
    extern __declspec(dllimport) const BFNumericFieldId EntityId;
    extern __declspec(dllimport) const BFTextFieldId EntityType;
    extern __declspec(dllimport) const BFTextFieldId FirstName;
    extern __declspec(dllimport) const BFTextFieldId LastName;
    extern __declspec(dllimport) const BFTextFieldId FATCACode;
    extern __declspec(dllimport) const BFTextFieldId TaxJuris;
    extern __declspec(dllimport) const BFTextFieldId TaxPayerStat;
    extern __declspec(dllimport) const BFTextFieldId AutoResetTaxPayerStat;
    extern __declspec(dllimport) const BFDateFieldId TaxPayerStartDate;
    extern __declspec(dllimport) const BFDateFieldId TaxPayerStopDate;
    extern __declspec(dllimport) const BFDecimalFieldId Version;
    extern __declspec(dllimport) const BFDecimalFieldId EntRegJurisDetlRId;
    extern __declspec(dllimport) const BFDateFieldId ProcessDate;
    extern __declspec(dllimport) const BFTextFieldId Username;
    extern __declspec(dllimport) const BFDateFieldId ModDate;
    extern __declspec(dllimport) const BFTextFieldId ModUser;
    extern __declspec(dllimport) const BFTextFieldId FATCAConsent;
    extern __declspec(dllimport) const BFTextFieldId TPSReason;
    extern __declspec(dllimport) const BFTextFieldId NoTINReason;
}
