// Field IDs and DataIDs for DataSet DSTC0405.VWRepeat_Record
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#pragma once
// include the repeat section header file (if applicable)
namespace ifds
{
   extern __declspec(dllimport) const BFDataId DSTC0405_VWRepeat_Record;
   extern __declspec(dllimport) const BFIntegerFieldId WarnCode;
   extern __declspec(dllimport) const BFTextFieldId WarnParam1;
   extern __declspec(dllimport) const BFTextFieldId WarnParam2;
}

