// Field IDs and DataIDs for DataSet DSTC0480.VWRepeat_Record
// ViewsGenerator: This file was generated by ViewsGenerator - Version 1.0.0.0
// ViewsGenerator: Generated on : Thursday, March 30, 2017 10:00:06


#pragma once
// include the repeat section header file (if applicable)

namespace ifds
{
    extern __declspec(dllimport) const BFDataId DSTC0480_VWRepeat_Record;
    extern __declspec(dllimport) const BFTextFieldId RoundFlg;
    extern __declspec(dllimport) const BFTextFieldId RecalcMthd;
    extern __declspec(dllimport) const BFIntegerFieldId UnitsPrecisionAcct;
    extern __declspec(dllimport) const BFDateFieldId StartDate;
    extern __declspec(dllimport) const BFDateFieldId StopDate;
    extern __declspec(dllimport) const BFTextFieldId Username;
    extern __declspec(dllimport) const BFTextFieldId ModUser;
    extern __declspec(dllimport) const BFDateFieldId ModDate;
    extern __declspec(dllimport) const BFTextFieldId AcctRndRulesUUID;
}
