// Field IDs and DataIDs for DataSet DSTC0390.REQRepeat_Record
// ViewsGenerator: This file was generated by ViewsGenerator - Version 1.0.0.0
// ViewsGenerator: Generated on : Thursday, February 23, 2017 03:48:34


#pragma once
// include the repeat section header file (if applicable)

namespace ifds
{
    extern __declspec(dllimport) const BFDataId DSTC0390_REQRepeat_Record;
    extern __declspec(dllimport) const BFTextFieldId RegDocId;
    extern __declspec(dllimport) const BFTextFieldId RegDocStatus;
    extern __declspec(dllimport) const BFDateFieldId DocReceivedDate;
    extern __declspec(dllimport) const BFTextFieldId RegDocRemarks;
    extern __declspec(dllimport) const BFNumericFieldId RecId;
    extern __declspec(dllimport) const BFTextFieldId RunMode;
    extern __declspec(dllimport) const BFDateFieldId EffectiveDate;
    extern __declspec(dllimport) const BFDateFieldId ExpireDate;
    extern __declspec(dllimport) const BFDateFieldId RequestDate;
    extern __declspec(dllimport) const BFTextFieldId RefNum;
    extern __declspec(dllimport) const BFTextFieldId AcctDocListUUID;
    extern __declspec(dllimport) const BFTextFieldId RegDocComplyRule;
    extern __declspec(dllimport) const BFTextFieldId RegDocJurisdiction;
    extern __declspec(dllimport) const BFTextFieldId TransmitMode;
    extern __declspec(dllimport) const BFTextFieldId IDMethod;
    extern __declspec(dllimport) const BFTextFieldId CountryOfIssue;
    extern __declspec(dllimport) const BFDateFieldId VerifiedDate;
    extern __declspec(dllimport) const BFTextFieldId DocSource;
}
