// Field IDs and DataIDs for DataSet DSTC0467.VWRepeat_Record
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#pragma once
// include the repeat section header file (if applicable)
namespace ifds
{
   extern __declspec(dllimport) const BFDataId DSTC0467_VWRepeat_Record;
   extern __declspec(dllimport) const BFTextFieldId AssetType;
   extern __declspec(dllimport) const BFTextFieldId RESPNotlType;
   extern __declspec(dllimport) const BFTextFieldId GrantDescription;
   extern __declspec(dllimport) const BFTextFieldId RESPNotlGroup;
   extern __declspec(dllimport) const BFTextFieldId TaxJurisAtGrantRequest;
   extern __declspec(dllimport) const BFTextFieldId TaxJurisAtGrantRedeem;
   extern __declspec(dllimport) const BFTextFieldId ResidencyAtGrantRequest;
   extern __declspec(dllimport) const BFTextFieldId ResidencyAtGrantRedeem;
   extern __declspec(dllimport) const BFIntegerFieldId BenefStartAgeForAsset;
   extern __declspec(dllimport) const BFIntegerFieldId BenefEndAgeForAsset;
   extern __declspec(dllimport) const BFTextFieldId AgeCalcMethod;
   extern __declspec(dllimport) const BFTextFieldId GrantFrequency;
   extern __declspec(dllimport) const BFTextFieldId GrantRequestType;
   extern __declspec(dllimport) const BFTextFieldId SiblingRequired;
   extern __declspec(dllimport) const BFTextFieldId ShareAsset;
   extern __declspec(dllimport) const BFTextFieldId DepletionMethod;
   extern __declspec(dllimport) const BFTextFieldId AutoGrantReturn;
   extern __declspec(dllimport) const BFDateFieldId GrantStartDate;
   extern __declspec(dllimport) const BFDateFieldId GrantEndDate;
   extern __declspec(dllimport) const BFTextFieldId GrantGBCD;
}

