// BFDataImpl implementation file for DataSet DSTC0486.VWRepeat_Record
// ViewsGenerator: This file was generated by ViewsGenerator - Version 1.0.0.0
// ViewsGenerator: Generated on : Monday, July 02, 2018 11:08:31


#include "stdafx.h"
#include <bfdata/bfdataimpl.hpp>
#include "dsi_dstc0486_vwrepeat_record.h"


// This function creates an instance of dsi_DSTC0486_VWRepeat_Record
// The function is required by the factory class as that class may choke the compiler
// with excessive symbols if all of the required header files needed to be #include'd
BFDataImpl* create_dsi_DSTC0486_VWRepeat_Record() { return new dsi_DSTC0486_VWRepeat_Record; }

dsi_DSTC0486_VWRepeat_Record::dsi_DSTC0486_VWRepeat_Record()
: BFDataImpl( 40007878 )
, RejErrNum_( ifds::RejErrNum, &ifds::s_FldProp_RejErrNum )
, RejFundCode_( ifds::RejFundCode, &ifds::s_FldProp_RejFundCode )
{
    cFields_ = 2;
    memset( &aFlds_[0], 0x00, sizeof( aFlds_ ) );
}

dsi_DSTC0486_VWRepeat_Record::~dsi_DSTC0486_VWRepeat_Record()
{
}

BFDataImpl* dsi_DSTC0486_VWRepeat_Record::clone()
{
    dsi_DSTC0486_VWRepeat_Record* p = new dsi_DSTC0486_VWRepeat_Record;
    p->RejErrNum_ = RejErrNum_;
    p->RejFundCode_ = RejFundCode_;
    return(p);
}

BFDataField* dsi_DSTC0486_VWRepeat_Record::getElement( const BFFieldId& id )
{
    switch( id.getId() ) {
        case 40005654: return ( &RejErrNum_ ); break; // RejErrNum
        case 40007873: return ( &RejFundCode_ ); break; // RejFundCode
    }
    return( NULL );
}

const BFDataField* dsi_DSTC0486_VWRepeat_Record::getElement( const BFFieldId& id ) const
{
   return( ( const_cast< dsi_DSTC0486_VWRepeat_Record* >(this) )->getElement( id ) );
}

BFDataField* dsi_DSTC0486_VWRepeat_Record::getElementByIndex( unsigned int iField )
{
    if ( iField >=0 && iField < 2 )
    {
        BFDataField* pField = aFlds_[iField];
        if( NULL == pField )
        {
            switch(iField)
            {
                case 0: aFlds_[0] = &RejErrNum_; break;
                case 1: aFlds_[1] = &RejFundCode_; break;
            }
            pField = aFlds_[iField];
            if( NULL == pField ) return( NULL );
        }
        return( pField );
    }
    return( NULL );
}

const BFDataField* dsi_DSTC0486_VWRepeat_Record::getElementByIndex( unsigned int iField ) const
{
    return( ( const_cast< dsi_DSTC0486_VWRepeat_Record* >(this) )->getElementByIndex( iField ) );
}

unsigned long dsi_DSTC0486_VWRepeat_Record::getLargestDefinedField( void ) const
{
    return( 60 );
}

unsigned long dsi_DSTC0486_VWRepeat_Record::getDefinedByteLength( void ) const
{
    return( 70 * sizeof( I_CHAR ) );
}

bool dsi_DSTC0486_VWRepeat_Record::exists( const BFFieldId& id ) const
{
    return dsi_DSTC0486_VWRepeat_Record::fieldExists( id );
}

bool dsi_DSTC0486_VWRepeat_Record::fieldExists( const BFFieldId& id )
{
    switch( id.getId() )
    {
        case 40005654: return ( true );
        case 40007873: return ( true );
    }
    return false;
}

