// BFDataImpl header file for DataSet DSTC0196.REQRepeat_Record
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#pragma once
#include <commonport.h>
#include <clientlocale.hpp>

#undef IFAST_DATAIMPL_LINKAGE
#ifdef IFAST_DATAIMPL_DLL
   #define IFAST_DATAIMPL_LINKAGE CLASS_EXPORT
#else
   #define IFAST_DATAIMPL_LINKAGE CLASS_IMPORT
#endif

namespace ifds
{
   //Field Externs
   extern const BFTextFieldId ScaleRunMode;
   extern const BFDecimalFieldId ScaleRate;
   extern const BFDecimalFieldId UpperBound;
   extern const BFDecimalFieldId LowerBound;
   extern const BFDecimalFieldId Level;
   extern const BFDateFieldId EffectiveDate;
   extern const BFDecimalFieldId ScaleDetlRid;

   //Property Externs
   extern const BFDataFieldProperties s_FldProp_ScaleRunMode;
   extern const BFDataFieldProperties s_FldProp_ScaleRate;
   extern const BFDataFieldProperties s_FldProp_UpperBound;
   extern const BFDataFieldProperties s_FldProp_LowerBound;
   extern const BFDataFieldProperties s_FldProp_Level;
   extern const BFDataFieldProperties s_FldProp_EffectiveDate;
   extern const BFDataFieldProperties s_FldProp_ScaleDetlRid;
}


class dsi_DSTC0196_REQRepeat_Record : public BFDataImpl 
{
public:
   // Constructors
   dsi_DSTC0196_REQRepeat_Record();
   virtual ~dsi_DSTC0196_REQRepeat_Record();

   virtual BFDataImpl* clone();

   virtual BFDataField* getElement( const BFFieldId& id );
   virtual const BFDataField* getElement( const BFFieldId& id ) const;
   virtual BFDataField* getElementByIndex( unsigned int iField );
   virtual const BFDataField* getElementByIndex( unsigned int iField ) const;


   virtual unsigned long getLargestDefinedField( void ) const;
   virtual unsigned long getDefinedByteLength( void ) const;
   virtual bool exists( const BFFieldId& id ) const;
   static bool fieldExists( const BFFieldId& id );

private:
   BFDataField* aFlds_[7];
   // Field Declarations
   BFTextField_60 ScaleRunMode_;
   BFDecimalField ScaleRate_;
   BFDecimalField UpperBound_;
   BFDecimalField LowerBound_;
   BFDecimalField Level_;
   BFDateField EffectiveDate_;
   BFDecimalField ScaleDetlRid_;

};
