// BFDataImpl header file for DataSet DSTC0367.VW
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#pragma once
#include <commonport.h>
#include <clientlocale.hpp>

#undef IFAST_DATAIMPL_LINKAGE
#ifdef IFAST_DATAIMPL_DLL
   #define IFAST_DATAIMPL_LINKAGE CLASS_EXPORT
#else
   #define IFAST_DATAIMPL_LINKAGE CLASS_IMPORT
#endif

namespace ifds
{
   //Field Externs
   extern const BFIntegerFieldId CriticalAge1;
   extern const BFIntegerFieldId CriticalAge2;
   extern const BFIntegerFieldId CriticalAge3;
   extern const BFIntegerFieldId BailOutAge1;
   extern const BFIntegerFieldId BailOutAge2;
   extern const BFIntegerFieldId BailOutAge3;
   extern const BFIntegerFieldId LegalAgeCalcType;
   extern const BFIntegerFieldId LegalMaxAge;
   extern const BFIntegerFieldId NumOfYears;
   extern const BFIntegerFieldId AltNumOfYears;

   //Property Externs
   extern const BFDataFieldProperties s_FldProp_CriticalAge1;
   extern const BFDataFieldProperties s_FldProp_CriticalAge2;
   extern const BFDataFieldProperties s_FldProp_CriticalAge3;
   extern const BFDataFieldProperties s_FldProp_BailOutAge1;
   extern const BFDataFieldProperties s_FldProp_BailOutAge2;
   extern const BFDataFieldProperties s_FldProp_BailOutAge3;
   extern const BFDataFieldProperties s_FldProp_LegalAgeCalcType;
   extern const BFDataFieldProperties s_FldProp_LegalMaxAge;
   extern const BFDataFieldProperties s_FldProp_NumOfYears;
   extern const BFDataFieldProperties s_FldProp_AltNumOfYears;
}


class dsi_DSTC0367_VW : public BFDataImpl 
{
public:
   // Constructors
   dsi_DSTC0367_VW();
   virtual ~dsi_DSTC0367_VW();

   virtual BFDataImpl* clone();

   virtual BFDataField* getElement( const BFFieldId& id );
   virtual const BFDataField* getElement( const BFFieldId& id ) const;
   virtual BFDataField* getElementByIndex( unsigned int iField );
   virtual const BFDataField* getElementByIndex( unsigned int iField ) const;


   virtual unsigned long getLargestDefinedField( void ) const;
   virtual unsigned long getDefinedByteLength( void ) const;
   virtual bool exists( const BFFieldId& id ) const;
   static bool fieldExists( const BFFieldId& id );

private:
   BFDataField* aFlds_[10];
   // Field Declarations
   BFIntegerField CriticalAge1_;
   BFIntegerField CriticalAge2_;
   BFIntegerField CriticalAge3_;
   BFIntegerField BailOutAge1_;
   BFIntegerField BailOutAge2_;
   BFIntegerField BailOutAge3_;
   BFIntegerField LegalAgeCalcType_;
   BFIntegerField LegalMaxAge_;
   BFIntegerField NumOfYears_;
   BFIntegerField AltNumOfYears_;

};
