// BFDataImpl implementation file for DataSet DSTC0429.REQ
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#include "stdafx.h"




#include <bfdata/bfdataimpl.hpp>
#include "dsi_dstc0429_req.h"


// This function creates an instance of dsi_DSTC0429_REQ
// The function is required by the factory class as that class may choke the compiler
// with excessive symbols if all of the required header files needed to be #include'd
BFDataImpl* create_dsi_DSTC0429_REQ() { return new dsi_DSTC0429_REQ; }

dsi_DSTC0429_REQ::dsi_DSTC0429_REQ()
: BFDataImpl( 40006594, 40006595 )
, SessionId_( ifds::SessionId, &ifds::s_FldProp_SessionId )
, User_Id_( ifds::User_Id, &ifds::s_FldProp_User_Id )
, LanguageCode_( ifds::LanguageCode, &ifds::s_FldProp_LanguageCode )
, CompanyId_( ifds::CompanyId, &ifds::s_FldProp_CompanyId )
, Track_( ifds::Track, &ifds::s_FldProp_Track )
, Activity_( ifds::Activity, &ifds::s_FldProp_Activity )
, MatSwpInstructionType_( ifds::MatSwpInstructionType, &ifds::s_FldProp_MatSwpInstructionType )
, AccountNum_( ifds::AccountNum, &ifds::s_FldProp_AccountNum )
, Fund_( ifds::Fund, &ifds::s_FldProp_Fund )
, Class_( ifds::Class, &ifds::s_FldProp_Class )
, SplitType_( ifds::SplitType, &ifds::s_FldProp_SplitType )
, EffectiveDate_( ifds::EffectiveDate, &ifds::s_FldProp_EffectiveDate )
, TransNum_( ifds::TransNum, &ifds::s_FldProp_TransNum )
, CashSweepBal_( ifds::CashSweepBal, &ifds::s_FldProp_CashSweepBal )
, SelectedAmt_( ifds::SelectedAmt, &ifds::s_FldProp_SelectedAmt )
, GoodBad_( ifds::GoodBad, &ifds::s_FldProp_GoodBad )
, TransSeq_( ifds::TransSeq, &ifds::s_FldProp_TransSeq )
, ProcType_( ifds::ProcType, &ifds::s_FldProp_ProcType )
, TransId_( ifds::TransId, &ifds::s_FldProp_TransId )
, IntInvestId_( ifds::IntInvestId, &ifds::s_FldProp_IntInvestId )
, RepeatCount_( ifds::RepeatCount, &ifds::s_FldProp_RepeatCount )
{
   cFields_ = 21;
   memset( &aFlds_[0], 0x00, sizeof( aFlds_ ) );
}

dsi_DSTC0429_REQ::~dsi_DSTC0429_REQ()
{
}

BFDataImpl* dsi_DSTC0429_REQ::clone()
{
   dsi_DSTC0429_REQ* p = new dsi_DSTC0429_REQ;
   p->SessionId_ = SessionId_;
   p->User_Id_ = User_Id_;
   p->LanguageCode_ = LanguageCode_;
   p->CompanyId_ = CompanyId_;
   p->Track_ = Track_;
   p->Activity_ = Activity_;
   p->MatSwpInstructionType_ = MatSwpInstructionType_;
   p->AccountNum_ = AccountNum_;
   p->Fund_ = Fund_;
   p->Class_ = Class_;
   p->SplitType_ = SplitType_;
   p->EffectiveDate_ = EffectiveDate_;
   p->TransNum_ = TransNum_;
   p->CashSweepBal_ = CashSweepBal_;
   p->SelectedAmt_ = SelectedAmt_;
   p->GoodBad_ = GoodBad_;
   p->TransSeq_ = TransSeq_;
   p->ProcType_ = ProcType_;
   p->TransId_ = TransId_;
   p->IntInvestId_ = IntInvestId_;
   p->RepeatCount_ = RepeatCount_;
   return(p);
}

BFDataField* dsi_DSTC0429_REQ::getElement( const BFFieldId& id )
{
   switch( id.getId() ) {
      case 40000005: return ( &SessionId_ ); break; // SessionId
      case 40000002: return ( &User_Id_ ); break; // User_Id
      case 40000030: return ( &LanguageCode_ ); break; // LanguageCode
      case 40000031: return ( &CompanyId_ ); break; // CompanyId
      case 40002065: return ( &Track_ ); break; // Track
      case 40002066: return ( &Activity_ ); break; // Activity
      case 40006562: return ( &MatSwpInstructionType_ ); break; // MatSwpInstructionType
      case 40000040: return ( &AccountNum_ ); break; // AccountNum
      case 40002227: return ( &Fund_ ); break; // Fund
      case 40002228: return ( &Class_ ); break; // Class
      case 40006544: return ( &SplitType_ ); break; // SplitType
      case 40000327: return ( &EffectiveDate_ ); break; // EffectiveDate
      case 40000096: return ( &TransNum_ ); break; // TransNum
      case 40006545: return ( &CashSweepBal_ ); break; // CashSweepBal
      case 40006546: return ( &SelectedAmt_ ); break; // SelectedAmt
      case 40000496: return ( &GoodBad_ ); break; // GoodBad
      case 40002217: return ( &TransSeq_ ); break; // TransSeq
      case 40006702: return ( &ProcType_ ); break; // ProcType
      case 40000063: return ( &TransId_ ); break; // TransId
      case 40006548: return ( &IntInvestId_ ); break; // IntInvestId
      case 40000120: return ( &RepeatCount_ ); break; // RepeatCount
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0429_REQ::getElement( const BFFieldId& id ) const
{
   return( ( const_cast< dsi_DSTC0429_REQ* >(this) )->getElement( id ) );
}

BFDataField* dsi_DSTC0429_REQ::getElementByIndex( unsigned int iField )
{
   if ( iField >=0 && iField < 21 )
   {
      BFDataField* pField = aFlds_[iField];
      if( NULL == pField )
      {
         switch(iField)
         {
            case 0: aFlds_[0] = &SessionId_; break;
            case 1: aFlds_[1] = &User_Id_; break;
            case 2: aFlds_[2] = &LanguageCode_; break;
            case 3: aFlds_[3] = &CompanyId_; break;
            case 4: aFlds_[4] = &Track_; break;
            case 5: aFlds_[5] = &Activity_; break;
            case 6: aFlds_[6] = &MatSwpInstructionType_; break;
            case 7: aFlds_[7] = &AccountNum_; break;
            case 8: aFlds_[8] = &Fund_; break;
            case 9: aFlds_[9] = &Class_; break;
            case 10: aFlds_[10] = &SplitType_; break;
            case 11: aFlds_[11] = &EffectiveDate_; break;
            case 12: aFlds_[12] = &TransNum_; break;
            case 13: aFlds_[13] = &CashSweepBal_; break;
            case 14: aFlds_[14] = &SelectedAmt_; break;
            case 15: aFlds_[15] = &GoodBad_; break;
            case 16: aFlds_[16] = &TransSeq_; break;
            case 17: aFlds_[17] = &ProcType_; break;
            case 18: aFlds_[18] = &TransId_; break;
            case 19: aFlds_[19] = &IntInvestId_; break;
            case 20: aFlds_[20] = &RepeatCount_; break;
         }
         pField = aFlds_[iField];
         if( NULL == pField ) return( NULL );
      }
      return( pField );
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0429_REQ::getElementByIndex( unsigned int iField ) const
{
   return( ( const_cast< dsi_DSTC0429_REQ* >(this) )->getElementByIndex( iField ) );
}

unsigned long dsi_DSTC0429_REQ::getLargestDefinedField( void ) const
{
   return( 60 );
}

unsigned long dsi_DSTC0429_REQ::getDefinedByteLength( void ) const
{
   return( 778 * sizeof( I_CHAR ) );
}

bool dsi_DSTC0429_REQ::exists( const BFFieldId& id ) const
{
   return dsi_DSTC0429_REQ::fieldExists( id );
}

bool dsi_DSTC0429_REQ::fieldExists( const BFFieldId& id )
{
   switch( id.getId() )
   {
      case 40000005: return( true );
      case 40000002: return( true );
      case 40000030: return( true );
      case 40000031: return( true );
      case 40002065: return( true );
      case 40002066: return( true );
      case 40006562: return( true );
      case 40000040: return( true );
      case 40002227: return( true );
      case 40002228: return( true );
      case 40006544: return( true );
      case 40000327: return( true );
      case 40000096: return( true );
      case 40006545: return( true );
      case 40006546: return( true );
      case 40000496: return( true );
      case 40002217: return( true );
      case 40006702: return( true );
      case 40000063: return( true );
      case 40006548: return( true );
      case 40000120: return( true );
   }
   return false;
}

