// BFDataImpl implementation file for DataSet DSTC0230.REQ
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#include "stdafx.h"




#include <bfdata/bfdataimpl.hpp>
#include "dsi_dstc0230_req.h"


// This function creates an instance of dsi_DSTC0230_REQ
// The function is required by the factory class as that class may choke the compiler
// with excessive symbols if all of the required header files needed to be #include'd
BFDataImpl* create_dsi_DSTC0230_REQ() { return new dsi_DSTC0230_REQ; }

dsi_DSTC0230_REQ::dsi_DSTC0230_REQ()
: BFDataImpl( 40003573 )
, SessionId_( ifds::SessionId, &ifds::s_FldProp_SessionId )
, User_Id_( ifds::User_Id, &ifds::s_FldProp_User_Id )
, LanguageCode_( ifds::LanguageCode, &ifds::s_FldProp_LanguageCode )
, CompanyId_( ifds::CompanyId, &ifds::s_FldProp_CompanyId )
, Track_( ifds::Track, &ifds::s_FldProp_Track )
, Activity_( ifds::Activity, &ifds::s_FldProp_Activity )
, SysFeeSearchType_( ifds::SysFeeSearchType, &ifds::s_FldProp_SysFeeSearchType )
, BrokerCode_( ifds::BrokerCode, &ifds::s_FldProp_BrokerCode )
, FundCode_( ifds::FundCode, &ifds::s_FldProp_FundCode )
, ClassCode_( ifds::ClassCode, &ifds::s_FldProp_ClassCode )
, CommGroup_( ifds::CommGroup, &ifds::s_FldProp_CommGroup )
, FeeCode_( ifds::FeeCode, &ifds::s_FldProp_FeeCode )
, ShGroup_( ifds::ShGroup, &ifds::s_FldProp_ShGroup )
, OverrideRepeats_( ifds::OverrideRepeats, &ifds::s_FldProp_OverrideRepeats )
, NextKey_( ifds::NextKey, &ifds::s_FldProp_NextKey )
, BranchCode_( ifds::BranchCode, &ifds::s_FldProp_BranchCode )
, SlsrepCode_( ifds::SlsrepCode, &ifds::s_FldProp_SlsrepCode )
, FamilyCode_( ifds::FamilyCode, &ifds::s_FldProp_FamilyCode )
, FundFromCode_( ifds::FundFromCode, &ifds::s_FldProp_FundFromCode )
, ClassFromCode_( ifds::ClassFromCode, &ifds::s_FldProp_ClassFromCode )
, DefaultFeeCode_( ifds::DefaultFeeCode, &ifds::s_FldProp_DefaultFeeCode )
, FeeModelCode_( ifds::FeeModelCode, &ifds::s_FldProp_FeeModelCode )
, AsofDate_( ifds::AsofDate, &ifds::s_FldProp_AsofDate )
{
   cFields_ = 23;
   memset( &aFlds_[0], 0x00, sizeof( aFlds_ ) );
}

dsi_DSTC0230_REQ::~dsi_DSTC0230_REQ()
{
}

BFDataImpl* dsi_DSTC0230_REQ::clone()
{
   dsi_DSTC0230_REQ* p = new dsi_DSTC0230_REQ;
   p->SessionId_ = SessionId_;
   p->User_Id_ = User_Id_;
   p->LanguageCode_ = LanguageCode_;
   p->CompanyId_ = CompanyId_;
   p->Track_ = Track_;
   p->Activity_ = Activity_;
   p->SysFeeSearchType_ = SysFeeSearchType_;
   p->BrokerCode_ = BrokerCode_;
   p->FundCode_ = FundCode_;
   p->ClassCode_ = ClassCode_;
   p->CommGroup_ = CommGroup_;
   p->FeeCode_ = FeeCode_;
   p->ShGroup_ = ShGroup_;
   p->OverrideRepeats_ = OverrideRepeats_;
   p->NextKey_ = NextKey_;
   p->BranchCode_ = BranchCode_;
   p->SlsrepCode_ = SlsrepCode_;
   p->FamilyCode_ = FamilyCode_;
   p->FundFromCode_ = FundFromCode_;
   p->ClassFromCode_ = ClassFromCode_;
   p->DefaultFeeCode_ = DefaultFeeCode_;
   p->FeeModelCode_ = FeeModelCode_;
   p->AsofDate_ = AsofDate_;
   return(p);
}

BFDataField* dsi_DSTC0230_REQ::getElement( const BFFieldId& id )
{
   switch( id.getId() ) {
      case 40000005: return ( &SessionId_ ); break; // SessionId
      case 40000002: return ( &User_Id_ ); break; // User_Id
      case 40000030: return ( &LanguageCode_ ); break; // LanguageCode
      case 40000031: return ( &CompanyId_ ); break; // CompanyId
      case 40002065: return ( &Track_ ); break; // Track
      case 40002066: return ( &Activity_ ); break; // Activity
      case 40003646: return ( &SysFeeSearchType_ ); break; // SysFeeSearchType
      case 40000044: return ( &BrokerCode_ ); break; // BrokerCode
      case 40000049: return ( &FundCode_ ); break; // FundCode
      case 40000050: return ( &ClassCode_ ); break; // ClassCode
      case 40003519: return ( &CommGroup_ ); break; // CommGroup
      case 40002917: return ( &FeeCode_ ); break; // FeeCode
      case 40003574: return ( &ShGroup_ ); break; // ShGroup
      case 40002139: return ( &OverrideRepeats_ ); break; // OverrideRepeats
      case 40000029: return ( &NextKey_ ); break; // NextKey
      case 40000045: return ( &BranchCode_ ); break; // BranchCode
      case 40000656: return ( &SlsrepCode_ ); break; // SlsrepCode
      case 40000802: return ( &FamilyCode_ ); break; // FamilyCode
      case 40002915: return ( &FundFromCode_ ); break; // FundFromCode
      case 40002916: return ( &ClassFromCode_ ); break; // ClassFromCode
      case 40003953: return ( &DefaultFeeCode_ ); break; // DefaultFeeCode
      case 40004584: return ( &FeeModelCode_ ); break; // FeeModelCode
      case 40000061: return ( &AsofDate_ ); break; // AsofDate
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0230_REQ::getElement( const BFFieldId& id ) const
{
   return( ( const_cast< dsi_DSTC0230_REQ* >(this) )->getElement( id ) );
}

BFDataField* dsi_DSTC0230_REQ::getElementByIndex( unsigned int iField )
{
   if ( iField >=0 && iField < 23 )
   {
      BFDataField* pField = aFlds_[iField];
      if( NULL == pField )
      {
         switch(iField)
         {
            case 0: aFlds_[0] = &SessionId_; break;
            case 1: aFlds_[1] = &User_Id_; break;
            case 2: aFlds_[2] = &LanguageCode_; break;
            case 3: aFlds_[3] = &CompanyId_; break;
            case 4: aFlds_[4] = &Track_; break;
            case 5: aFlds_[5] = &Activity_; break;
            case 6: aFlds_[6] = &SysFeeSearchType_; break;
            case 7: aFlds_[7] = &BrokerCode_; break;
            case 8: aFlds_[8] = &FundCode_; break;
            case 9: aFlds_[9] = &ClassCode_; break;
            case 10: aFlds_[10] = &CommGroup_; break;
            case 11: aFlds_[11] = &FeeCode_; break;
            case 12: aFlds_[12] = &ShGroup_; break;
            case 13: aFlds_[13] = &OverrideRepeats_; break;
            case 14: aFlds_[14] = &NextKey_; break;
            case 15: aFlds_[15] = &BranchCode_; break;
            case 16: aFlds_[16] = &SlsrepCode_; break;
            case 17: aFlds_[17] = &FamilyCode_; break;
            case 18: aFlds_[18] = &FundFromCode_; break;
            case 19: aFlds_[19] = &ClassFromCode_; break;
            case 20: aFlds_[20] = &DefaultFeeCode_; break;
            case 21: aFlds_[21] = &FeeModelCode_; break;
            case 22: aFlds_[22] = &AsofDate_; break;
         }
         pField = aFlds_[iField];
         if( NULL == pField ) return( NULL );
      }
      return( pField );
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0230_REQ::getElementByIndex( unsigned int iField ) const
{
   return( ( const_cast< dsi_DSTC0230_REQ* >(this) )->getElementByIndex( iField ) );
}

unsigned long dsi_DSTC0230_REQ::getLargestDefinedField( void ) const
{
   return( 200 );
}

unsigned long dsi_DSTC0230_REQ::getDefinedByteLength( void ) const
{
   return( 1426 * sizeof( I_CHAR ) );
}

bool dsi_DSTC0230_REQ::exists( const BFFieldId& id ) const
{
   return dsi_DSTC0230_REQ::fieldExists( id );
}

bool dsi_DSTC0230_REQ::fieldExists( const BFFieldId& id )
{
   switch( id.getId() )
   {
      case 40000005: return( true );
      case 40000002: return( true );
      case 40000030: return( true );
      case 40000031: return( true );
      case 40002065: return( true );
      case 40002066: return( true );
      case 40003646: return( true );
      case 40000044: return( true );
      case 40000049: return( true );
      case 40000050: return( true );
      case 40003519: return( true );
      case 40002917: return( true );
      case 40003574: return( true );
      case 40002139: return( true );
      case 40000029: return( true );
      case 40000045: return( true );
      case 40000656: return( true );
      case 40000802: return( true );
      case 40002915: return( true );
      case 40002916: return( true );
      case 40003953: return( true );
      case 40004584: return( true );
      case 40000061: return( true );
   }
   return false;
}

