// BFDataImpl implementation file for DataSet DSTC0196.REQ
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#include "stdafx.h"




#include <bfdata/bfdataimpl.hpp>
#include "dsi_dstc0196_req.h"


// This function creates an instance of dsi_DSTC0196_REQ
// The function is required by the factory class as that class may choke the compiler
// with excessive symbols if all of the required header files needed to be #include'd
BFDataImpl* create_dsi_DSTC0196_REQ() { return new dsi_DSTC0196_REQ; }

dsi_DSTC0196_REQ::dsi_DSTC0196_REQ()
: BFDataImpl( 40002928, 40002929 )
, SessionId_( ifds::SessionId, &ifds::s_FldProp_SessionId )
, User_Id_( ifds::User_Id, &ifds::s_FldProp_User_Id )
, LanguageCode_( ifds::LanguageCode, &ifds::s_FldProp_LanguageCode )
, CompanyId_( ifds::CompanyId, &ifds::s_FldProp_CompanyId )
, AccountNum_( ifds::AccountNum, &ifds::s_FldProp_AccountNum )
, Track_( ifds::Track, &ifds::s_FldProp_Track )
, Activity_( ifds::Activity, &ifds::s_FldProp_Activity )
, AcctFeeParamId_( ifds::AcctFeeParamId, &ifds::s_FldProp_AcctFeeParamId )
, FeeCode_( ifds::FeeCode, &ifds::s_FldProp_FeeCode )
, EffectiveDate_( ifds::EffectiveDate, &ifds::s_FldProp_EffectiveDate )
, StopDate_( ifds::StopDate, &ifds::s_FldProp_StopDate )
, ParamFeeType_( ifds::ParamFeeType, &ifds::s_FldProp_ParamFeeType )
, Rate_( ifds::Rate, &ifds::s_FldProp_Rate )
, MinFee_( ifds::MinFee, &ifds::s_FldProp_MinFee )
, MaxFee_( ifds::MaxFee, &ifds::s_FldProp_MaxFee )
, FundCode_( ifds::FundCode, &ifds::s_FldProp_FundCode )
, ClassCode_( ifds::ClassCode, &ifds::s_FldProp_ClassCode )
, FundFromCode_( ifds::FundFromCode, &ifds::s_FldProp_FundFromCode )
, ClassFromCode_( ifds::ClassFromCode, &ifds::s_FldProp_ClassFromCode )
, RunMode_( ifds::RunMode, &ifds::s_FldProp_RunMode )
, ProcessDate_( ifds::ProcessDate, &ifds::s_FldProp_ProcessDate )
, ModDate_( ifds::ModDate, &ifds::s_FldProp_ModDate )
, Username_( ifds::Username, &ifds::s_FldProp_Username )
, ModUser_( ifds::ModUser, &ifds::s_FldProp_ModUser )
, CommGroup_( ifds::CommGroup, &ifds::s_FldProp_CommGroup )
, BasedOn_( ifds::BasedOn, &ifds::s_FldProp_BasedOn )
, RepeatCount_( ifds::RepeatCount, &ifds::s_FldProp_RepeatCount )
{
   cFields_ = 27;
   memset( &aFlds_[0], 0x00, sizeof( aFlds_ ) );
}

dsi_DSTC0196_REQ::~dsi_DSTC0196_REQ()
{
}

BFDataImpl* dsi_DSTC0196_REQ::clone()
{
   dsi_DSTC0196_REQ* p = new dsi_DSTC0196_REQ;
   p->SessionId_ = SessionId_;
   p->User_Id_ = User_Id_;
   p->LanguageCode_ = LanguageCode_;
   p->CompanyId_ = CompanyId_;
   p->AccountNum_ = AccountNum_;
   p->Track_ = Track_;
   p->Activity_ = Activity_;
   p->AcctFeeParamId_ = AcctFeeParamId_;
   p->FeeCode_ = FeeCode_;
   p->EffectiveDate_ = EffectiveDate_;
   p->StopDate_ = StopDate_;
   p->ParamFeeType_ = ParamFeeType_;
   p->Rate_ = Rate_;
   p->MinFee_ = MinFee_;
   p->MaxFee_ = MaxFee_;
   p->FundCode_ = FundCode_;
   p->ClassCode_ = ClassCode_;
   p->FundFromCode_ = FundFromCode_;
   p->ClassFromCode_ = ClassFromCode_;
   p->RunMode_ = RunMode_;
   p->ProcessDate_ = ProcessDate_;
   p->ModDate_ = ModDate_;
   p->Username_ = Username_;
   p->ModUser_ = ModUser_;
   p->CommGroup_ = CommGroup_;
   p->BasedOn_ = BasedOn_;
   p->RepeatCount_ = RepeatCount_;
   return(p);
}

BFDataField* dsi_DSTC0196_REQ::getElement( const BFFieldId& id )
{
   switch( id.getId() ) {
      case 40000005: return ( &SessionId_ ); break; // SessionId
      case 40000002: return ( &User_Id_ ); break; // User_Id
      case 40000030: return ( &LanguageCode_ ); break; // LanguageCode
      case 40000031: return ( &CompanyId_ ); break; // CompanyId
      case 40000040: return ( &AccountNum_ ); break; // AccountNum
      case 40002065: return ( &Track_ ); break; // Track
      case 40002066: return ( &Activity_ ); break; // Activity
      case 40002914: return ( &AcctFeeParamId_ ); break; // AcctFeeParamId
      case 40002917: return ( &FeeCode_ ); break; // FeeCode
      case 40000327: return ( &EffectiveDate_ ); break; // EffectiveDate
      case 40000279: return ( &StopDate_ ); break; // StopDate
      case 40002945: return ( &ParamFeeType_ ); break; // ParamFeeType
      case 40002919: return ( &Rate_ ); break; // Rate
      case 40002899: return ( &MinFee_ ); break; // MinFee
      case 40001674: return ( &MaxFee_ ); break; // MaxFee
      case 40000049: return ( &FundCode_ ); break; // FundCode
      case 40000050: return ( &ClassCode_ ); break; // ClassCode
      case 40002915: return ( &FundFromCode_ ); break; // FundFromCode
      case 40002916: return ( &ClassFromCode_ ); break; // ClassFromCode
      case 40000990: return ( &RunMode_ ); break; // RunMode
      case 40000216: return ( &ProcessDate_ ); break; // ProcessDate
      case 40000217: return ( &ModDate_ ); break; // ModDate
      case 40000117: return ( &Username_ ); break; // Username
      case 40000218: return ( &ModUser_ ); break; // ModUser
      case 40003519: return ( &CommGroup_ ); break; // CommGroup
      case 40003580: return ( &BasedOn_ ); break; // BasedOn
      case 40000120: return ( &RepeatCount_ ); break; // RepeatCount
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0196_REQ::getElement( const BFFieldId& id ) const
{
   return( ( const_cast< dsi_DSTC0196_REQ* >(this) )->getElement( id ) );
}

BFDataField* dsi_DSTC0196_REQ::getElementByIndex( unsigned int iField )
{
   if ( iField >=0 && iField < 27 )
   {
      BFDataField* pField = aFlds_[iField];
      if( NULL == pField )
      {
         switch(iField)
         {
            case 0: aFlds_[0] = &SessionId_; break;
            case 1: aFlds_[1] = &User_Id_; break;
            case 2: aFlds_[2] = &LanguageCode_; break;
            case 3: aFlds_[3] = &CompanyId_; break;
            case 4: aFlds_[4] = &AccountNum_; break;
            case 5: aFlds_[5] = &Track_; break;
            case 6: aFlds_[6] = &Activity_; break;
            case 7: aFlds_[7] = &AcctFeeParamId_; break;
            case 8: aFlds_[8] = &FeeCode_; break;
            case 9: aFlds_[9] = &EffectiveDate_; break;
            case 10: aFlds_[10] = &StopDate_; break;
            case 11: aFlds_[11] = &ParamFeeType_; break;
            case 12: aFlds_[12] = &Rate_; break;
            case 13: aFlds_[13] = &MinFee_; break;
            case 14: aFlds_[14] = &MaxFee_; break;
            case 15: aFlds_[15] = &FundCode_; break;
            case 16: aFlds_[16] = &ClassCode_; break;
            case 17: aFlds_[17] = &FundFromCode_; break;
            case 18: aFlds_[18] = &ClassFromCode_; break;
            case 19: aFlds_[19] = &RunMode_; break;
            case 20: aFlds_[20] = &ProcessDate_; break;
            case 21: aFlds_[21] = &ModDate_; break;
            case 22: aFlds_[22] = &Username_; break;
            case 23: aFlds_[23] = &ModUser_; break;
            case 24: aFlds_[24] = &CommGroup_; break;
            case 25: aFlds_[25] = &BasedOn_; break;
            case 26: aFlds_[26] = &RepeatCount_; break;
         }
         pField = aFlds_[iField];
         if( NULL == pField ) return( NULL );
      }
      return( pField );
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0196_REQ::getElementByIndex( unsigned int iField ) const
{
   return( ( const_cast< dsi_DSTC0196_REQ* >(this) )->getElementByIndex( iField ) );
}

unsigned long dsi_DSTC0196_REQ::getLargestDefinedField( void ) const
{
   return( 200 );
}

unsigned long dsi_DSTC0196_REQ::getDefinedByteLength( void ) const
{
   return( 1280 * sizeof( I_CHAR ) );
}

bool dsi_DSTC0196_REQ::exists( const BFFieldId& id ) const
{
   return dsi_DSTC0196_REQ::fieldExists( id );
}

bool dsi_DSTC0196_REQ::fieldExists( const BFFieldId& id )
{
   switch( id.getId() )
   {
      case 40000005: return( true );
      case 40000002: return( true );
      case 40000030: return( true );
      case 40000031: return( true );
      case 40000040: return( true );
      case 40002065: return( true );
      case 40002066: return( true );
      case 40002914: return( true );
      case 40002917: return( true );
      case 40000327: return( true );
      case 40000279: return( true );
      case 40002945: return( true );
      case 40002919: return( true );
      case 40002899: return( true );
      case 40001674: return( true );
      case 40000049: return( true );
      case 40000050: return( true );
      case 40002915: return( true );
      case 40002916: return( true );
      case 40000990: return( true );
      case 40000216: return( true );
      case 40000217: return( true );
      case 40000117: return( true );
      case 40000218: return( true );
      case 40003519: return( true );
      case 40003580: return( true );
      case 40000120: return( true );
   }
   return false;
}

