// BFDataImpl implementation file for DataSet DSTC0145.REQRepeat_Record
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#include "stdafx.h"




#include <bfdata/bfdataimpl.hpp>
#include "dsi_dstc0145_reqrepeat_record.h"


// This function creates an instance of dsi_DSTC0145_REQRepeat_Record
// The function is required by the factory class as that class may choke the compiler
// with excessive symbols if all of the required header files needed to be #include'd
BFDataImpl* create_dsi_DSTC0145_REQRepeat_Record() { return new dsi_DSTC0145_REQRepeat_Record; }

dsi_DSTC0145_REQRepeat_Record::dsi_DSTC0145_REQRepeat_Record()
: BFDataImpl( 40001882 )
, UpdType_( ifds::UpdType, &ifds::s_FldProp_UpdType )
, TableTag_( ifds::TableTag, &ifds::s_FldProp_TableTag )
, Repeating1_( ifds::Repeating1, &ifds::s_FldProp_Repeating1 )
, Repeating2_( ifds::Repeating2, &ifds::s_FldProp_Repeating2 )
, Repeating3_( ifds::Repeating3, &ifds::s_FldProp_Repeating3 )
, Repeating4_( ifds::Repeating4, &ifds::s_FldProp_Repeating4 )
, Repeating5_( ifds::Repeating5, &ifds::s_FldProp_Repeating5 )
, Repeating6_( ifds::Repeating6, &ifds::s_FldProp_Repeating6 )
, Repeating7_( ifds::Repeating7, &ifds::s_FldProp_Repeating7 )
, Repeating8_( ifds::Repeating8, &ifds::s_FldProp_Repeating8 )
, Repeating9_( ifds::Repeating9, &ifds::s_FldProp_Repeating9 )
, Repeating10_( ifds::Repeating10, &ifds::s_FldProp_Repeating10 )
, Repeating11_( ifds::Repeating11, &ifds::s_FldProp_Repeating11 )
, Repeating12_( ifds::Repeating12, &ifds::s_FldProp_Repeating12 )
, Repeating13_( ifds::Repeating13, &ifds::s_FldProp_Repeating13 )
, Repeating14_( ifds::Repeating14, &ifds::s_FldProp_Repeating14 )
, Repeating15_( ifds::Repeating15, &ifds::s_FldProp_Repeating15 )
, Repeating16_( ifds::Repeating16, &ifds::s_FldProp_Repeating16 )
, Repeating17_( ifds::Repeating17, &ifds::s_FldProp_Repeating17 )
, Repeating18_( ifds::Repeating18, &ifds::s_FldProp_Repeating18 )
, Repeating19_( ifds::Repeating19, &ifds::s_FldProp_Repeating19 )
, Repeating20_( ifds::Repeating20, &ifds::s_FldProp_Repeating20 )
, Repeating21_( ifds::Repeating21, &ifds::s_FldProp_Repeating21 )
, Repeating22_( ifds::Repeating22, &ifds::s_FldProp_Repeating22 )
, Repeating23_( ifds::Repeating23, &ifds::s_FldProp_Repeating23 )
, Repeating24_( ifds::Repeating24, &ifds::s_FldProp_Repeating24 )
, Repeating25_( ifds::Repeating25, &ifds::s_FldProp_Repeating25 )
, Repeating26_( ifds::Repeating26, &ifds::s_FldProp_Repeating26 )
, Repeating27_( ifds::Repeating27, &ifds::s_FldProp_Repeating27 )
, Repeating28_( ifds::Repeating28, &ifds::s_FldProp_Repeating28 )
, Repeating29_( ifds::Repeating29, &ifds::s_FldProp_Repeating29 )
, Repeating30_( ifds::Repeating30, &ifds::s_FldProp_Repeating30 )
, Repeating31_( ifds::Repeating31, &ifds::s_FldProp_Repeating31 )
, Repeating32_( ifds::Repeating32, &ifds::s_FldProp_Repeating32 )
, Repeating33_( ifds::Repeating33, &ifds::s_FldProp_Repeating33 )
, Repeating34_( ifds::Repeating34, &ifds::s_FldProp_Repeating34 )
, Repeating35_( ifds::Repeating35, &ifds::s_FldProp_Repeating35 )
{
   cFields_ = 37;
   memset( &aFlds_[0], 0x00, sizeof( aFlds_ ) );
}

dsi_DSTC0145_REQRepeat_Record::~dsi_DSTC0145_REQRepeat_Record()
{
}

BFDataImpl* dsi_DSTC0145_REQRepeat_Record::clone()
{
   dsi_DSTC0145_REQRepeat_Record* p = new dsi_DSTC0145_REQRepeat_Record;
   p->UpdType_ = UpdType_;
   p->TableTag_ = TableTag_;
   p->Repeating1_ = Repeating1_;
   p->Repeating2_ = Repeating2_;
   p->Repeating3_ = Repeating3_;
   p->Repeating4_ = Repeating4_;
   p->Repeating5_ = Repeating5_;
   p->Repeating6_ = Repeating6_;
   p->Repeating7_ = Repeating7_;
   p->Repeating8_ = Repeating8_;
   p->Repeating9_ = Repeating9_;
   p->Repeating10_ = Repeating10_;
   p->Repeating11_ = Repeating11_;
   p->Repeating12_ = Repeating12_;
   p->Repeating13_ = Repeating13_;
   p->Repeating14_ = Repeating14_;
   p->Repeating15_ = Repeating15_;
   p->Repeating16_ = Repeating16_;
   p->Repeating17_ = Repeating17_;
   p->Repeating18_ = Repeating18_;
   p->Repeating19_ = Repeating19_;
   p->Repeating20_ = Repeating20_;
   p->Repeating21_ = Repeating21_;
   p->Repeating22_ = Repeating22_;
   p->Repeating23_ = Repeating23_;
   p->Repeating24_ = Repeating24_;
   p->Repeating25_ = Repeating25_;
   p->Repeating26_ = Repeating26_;
   p->Repeating27_ = Repeating27_;
   p->Repeating28_ = Repeating28_;
   p->Repeating29_ = Repeating29_;
   p->Repeating30_ = Repeating30_;
   p->Repeating31_ = Repeating31_;
   p->Repeating32_ = Repeating32_;
   p->Repeating33_ = Repeating33_;
   p->Repeating34_ = Repeating34_;
   p->Repeating35_ = Repeating35_;
   return(p);
}

BFDataField* dsi_DSTC0145_REQRepeat_Record::getElement( const BFFieldId& id )
{
   switch( id.getId() ) {
      case 40001842: return ( &UpdType_ ); break; // UpdType
      case 40001843: return ( &TableTag_ ); break; // TableTag
      case 40001844: return ( &Repeating1_ ); break; // Repeating1
      case 40001845: return ( &Repeating2_ ); break; // Repeating2
      case 40001846: return ( &Repeating3_ ); break; // Repeating3
      case 40001847: return ( &Repeating4_ ); break; // Repeating4
      case 40001848: return ( &Repeating5_ ); break; // Repeating5
      case 40001849: return ( &Repeating6_ ); break; // Repeating6
      case 40001850: return ( &Repeating7_ ); break; // Repeating7
      case 40001851: return ( &Repeating8_ ); break; // Repeating8
      case 40001852: return ( &Repeating9_ ); break; // Repeating9
      case 40001853: return ( &Repeating10_ ); break; // Repeating10
      case 40001854: return ( &Repeating11_ ); break; // Repeating11
      case 40001855: return ( &Repeating12_ ); break; // Repeating12
      case 40001856: return ( &Repeating13_ ); break; // Repeating13
      case 40001857: return ( &Repeating14_ ); break; // Repeating14
      case 40001858: return ( &Repeating15_ ); break; // Repeating15
      case 40001859: return ( &Repeating16_ ); break; // Repeating16
      case 40001860: return ( &Repeating17_ ); break; // Repeating17
      case 40001861: return ( &Repeating18_ ); break; // Repeating18
      case 40001862: return ( &Repeating19_ ); break; // Repeating19
      case 40001863: return ( &Repeating20_ ); break; // Repeating20
      case 40001864: return ( &Repeating21_ ); break; // Repeating21
      case 40001865: return ( &Repeating22_ ); break; // Repeating22
      case 40001866: return ( &Repeating23_ ); break; // Repeating23
      case 40001867: return ( &Repeating24_ ); break; // Repeating24
      case 40001868: return ( &Repeating25_ ); break; // Repeating25
      case 40001869: return ( &Repeating26_ ); break; // Repeating26
      case 40001870: return ( &Repeating27_ ); break; // Repeating27
      case 40001871: return ( &Repeating28_ ); break; // Repeating28
      case 40001872: return ( &Repeating29_ ); break; // Repeating29
      case 40001873: return ( &Repeating30_ ); break; // Repeating30
      case 40001874: return ( &Repeating31_ ); break; // Repeating31
      case 40001875: return ( &Repeating32_ ); break; // Repeating32
      case 40001876: return ( &Repeating33_ ); break; // Repeating33
      case 40001877: return ( &Repeating34_ ); break; // Repeating34
      case 40001878: return ( &Repeating35_ ); break; // Repeating35
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0145_REQRepeat_Record::getElement( const BFFieldId& id ) const
{
   return( ( const_cast< dsi_DSTC0145_REQRepeat_Record* >(this) )->getElement( id ) );
}

BFDataField* dsi_DSTC0145_REQRepeat_Record::getElementByIndex( unsigned int iField )
{
   if ( iField >=0 && iField < 37 )
   {
      BFDataField* pField = aFlds_[iField];
      if( NULL == pField )
      {
         switch(iField)
         {
            case 0: aFlds_[0] = &UpdType_; break;
            case 1: aFlds_[1] = &TableTag_; break;
            case 2: aFlds_[2] = &Repeating1_; break;
            case 3: aFlds_[3] = &Repeating2_; break;
            case 4: aFlds_[4] = &Repeating3_; break;
            case 5: aFlds_[5] = &Repeating4_; break;
            case 6: aFlds_[6] = &Repeating5_; break;
            case 7: aFlds_[7] = &Repeating6_; break;
            case 8: aFlds_[8] = &Repeating7_; break;
            case 9: aFlds_[9] = &Repeating8_; break;
            case 10: aFlds_[10] = &Repeating9_; break;
            case 11: aFlds_[11] = &Repeating10_; break;
            case 12: aFlds_[12] = &Repeating11_; break;
            case 13: aFlds_[13] = &Repeating12_; break;
            case 14: aFlds_[14] = &Repeating13_; break;
            case 15: aFlds_[15] = &Repeating14_; break;
            case 16: aFlds_[16] = &Repeating15_; break;
            case 17: aFlds_[17] = &Repeating16_; break;
            case 18: aFlds_[18] = &Repeating17_; break;
            case 19: aFlds_[19] = &Repeating18_; break;
            case 20: aFlds_[20] = &Repeating19_; break;
            case 21: aFlds_[21] = &Repeating20_; break;
            case 22: aFlds_[22] = &Repeating21_; break;
            case 23: aFlds_[23] = &Repeating22_; break;
            case 24: aFlds_[24] = &Repeating23_; break;
            case 25: aFlds_[25] = &Repeating24_; break;
            case 26: aFlds_[26] = &Repeating25_; break;
            case 27: aFlds_[27] = &Repeating26_; break;
            case 28: aFlds_[28] = &Repeating27_; break;
            case 29: aFlds_[29] = &Repeating28_; break;
            case 30: aFlds_[30] = &Repeating29_; break;
            case 31: aFlds_[31] = &Repeating30_; break;
            case 32: aFlds_[32] = &Repeating31_; break;
            case 33: aFlds_[33] = &Repeating32_; break;
            case 34: aFlds_[34] = &Repeating33_; break;
            case 35: aFlds_[35] = &Repeating34_; break;
            case 36: aFlds_[36] = &Repeating35_; break;
         }
         pField = aFlds_[iField];
         if( NULL == pField ) return( NULL );
      }
      return( pField );
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0145_REQRepeat_Record::getElementByIndex( unsigned int iField ) const
{
   return( ( const_cast< dsi_DSTC0145_REQRepeat_Record* >(this) )->getElementByIndex( iField ) );
}

unsigned long dsi_DSTC0145_REQRepeat_Record::getLargestDefinedField( void ) const
{
   return( 90 );
}

unsigned long dsi_DSTC0145_REQRepeat_Record::getDefinedByteLength( void ) const
{
   return( 2250 * sizeof( I_CHAR ) );
}

bool dsi_DSTC0145_REQRepeat_Record::exists( const BFFieldId& id ) const
{
   return dsi_DSTC0145_REQRepeat_Record::fieldExists( id );
}

bool dsi_DSTC0145_REQRepeat_Record::fieldExists( const BFFieldId& id )
{
   switch( id.getId() )
   {
      case 40001842: return( true );
      case 40001843: return( true );
      case 40001844: return( true );
      case 40001845: return( true );
      case 40001846: return( true );
      case 40001847: return( true );
      case 40001848: return( true );
      case 40001849: return( true );
      case 40001850: return( true );
      case 40001851: return( true );
      case 40001852: return( true );
      case 40001853: return( true );
      case 40001854: return( true );
      case 40001855: return( true );
      case 40001856: return( true );
      case 40001857: return( true );
      case 40001858: return( true );
      case 40001859: return( true );
      case 40001860: return( true );
      case 40001861: return( true );
      case 40001862: return( true );
      case 40001863: return( true );
      case 40001864: return( true );
      case 40001865: return( true );
      case 40001866: return( true );
      case 40001867: return( true );
      case 40001868: return( true );
      case 40001869: return( true );
      case 40001870: return( true );
      case 40001871: return( true );
      case 40001872: return( true );
      case 40001873: return( true );
      case 40001874: return( true );
      case 40001875: return( true );
      case 40001876: return( true );
      case 40001877: return( true );
      case 40001878: return( true );
   }
   return false;
}

