// BFDataImpl implementation file for DataSet DSTC0356.VW
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#include "stdafx.h"




#include <bfdata/bfdataimpl.hpp>
#include "dsi_dstc0356_vw.h"


// This function creates an instance of dsi_DSTC0356_VW
// The function is required by the factory class as that class may choke the compiler
// with excessive symbols if all of the required header files needed to be #include'd
BFDataImpl* create_dsi_DSTC0356_VW() { return new dsi_DSTC0356_VW; }

dsi_DSTC0356_VW::dsi_DSTC0356_VW()
: BFDataImpl( 40005331 )
, AccountNum_( ifds::AccountNum, &ifds::s_FldProp_AccountNum )
, ShareholderNum_( ifds::ShareholderNum, &ifds::s_FldProp_ShareholderNum )
{
   cFields_ = 2;
   memset( &aFlds_[0], 0x00, sizeof( aFlds_ ) );
}

dsi_DSTC0356_VW::~dsi_DSTC0356_VW()
{
}

BFDataImpl* dsi_DSTC0356_VW::clone()
{
   dsi_DSTC0356_VW* p = new dsi_DSTC0356_VW;
   p->AccountNum_ = AccountNum_;
   p->ShareholderNum_ = ShareholderNum_;
   return(p);
}

BFDataField* dsi_DSTC0356_VW::getElement( const BFFieldId& id )
{
   switch( id.getId() ) {
      case 40000040: return ( &AccountNum_ ); break; // AccountNum
      case 40000038: return ( &ShareholderNum_ ); break; // ShareholderNum
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0356_VW::getElement( const BFFieldId& id ) const
{
   return( ( const_cast< dsi_DSTC0356_VW* >(this) )->getElement( id ) );
}

BFDataField* dsi_DSTC0356_VW::getElementByIndex( unsigned int iField )
{
   if ( iField >=0 && iField < 2 )
   {
      BFDataField* pField = aFlds_[iField];
      if( NULL == pField )
      {
         switch(iField)
         {
            case 0: aFlds_[0] = &AccountNum_; break;
            case 1: aFlds_[1] = &ShareholderNum_; break;
         }
         pField = aFlds_[iField];
         if( NULL == pField ) return( NULL );
      }
      return( pField );
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0356_VW::getElementByIndex( unsigned int iField ) const
{
   return( ( const_cast< dsi_DSTC0356_VW* >(this) )->getElementByIndex( iField ) );
}

unsigned long dsi_DSTC0356_VW::getLargestDefinedField( void ) const
{
   return( 17 );
}

unsigned long dsi_DSTC0356_VW::getDefinedByteLength( void ) const
{
   return( 27 * sizeof( I_CHAR ) );
}

bool dsi_DSTC0356_VW::exists( const BFFieldId& id ) const
{
   return dsi_DSTC0356_VW::fieldExists( id );
}

bool dsi_DSTC0356_VW::fieldExists( const BFFieldId& id )
{
   switch( id.getId() )
   {
      case 40000040: return( true );
      case 40000038: return( true );
   }
   return false;
}

