// BFDataImpl implementation file for DataSet DSTC0189.REQ
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#include "stdafx.h"




#include <bfdata/bfdataimpl.hpp>
#include "dsi_dstc0189_req.h"


// This function creates an instance of dsi_DSTC0189_REQ
// The function is required by the factory class as that class may choke the compiler
// with excessive symbols if all of the required header files needed to be #include'd
BFDataImpl* create_dsi_DSTC0189_REQ() { return new dsi_DSTC0189_REQ; }

dsi_DSTC0189_REQ::dsi_DSTC0189_REQ()
: BFDataImpl( 40002838 )
, User_Id_( ifds::User_Id, &ifds::s_FldProp_User_Id )
, CompanyId_( ifds::CompanyId, &ifds::s_FldProp_CompanyId )
, LanguageCode_( ifds::LanguageCode, &ifds::s_FldProp_LanguageCode )
, Currency_( ifds::Currency, &ifds::s_FldProp_Currency )
, Track_( ifds::Track, &ifds::s_FldProp_Track )
, Activity_( ifds::Activity, &ifds::s_FldProp_Activity )
, SecurityQuestion_( ifds::SecurityQuestion, &ifds::s_FldProp_SecurityQuestion )
, SecurityAnswer_( ifds::SecurityAnswer, &ifds::s_FldProp_SecurityAnswer )
, Mode_( ifds::Mode, &ifds::s_FldProp_Mode )
{
   cFields_ = 9;
   memset( &aFlds_[0], 0x00, sizeof( aFlds_ ) );
}

dsi_DSTC0189_REQ::~dsi_DSTC0189_REQ()
{
}

BFDataImpl* dsi_DSTC0189_REQ::clone()
{
   dsi_DSTC0189_REQ* p = new dsi_DSTC0189_REQ;
   p->User_Id_ = User_Id_;
   p->CompanyId_ = CompanyId_;
   p->LanguageCode_ = LanguageCode_;
   p->Currency_ = Currency_;
   p->Track_ = Track_;
   p->Activity_ = Activity_;
   p->SecurityQuestion_ = SecurityQuestion_;
   p->SecurityAnswer_ = SecurityAnswer_;
   p->Mode_ = Mode_;
   return(p);
}

BFDataField* dsi_DSTC0189_REQ::getElement( const BFFieldId& id )
{
   switch( id.getId() ) {
      case 40000002: return ( &User_Id_ ); break; // User_Id
      case 40000031: return ( &CompanyId_ ); break; // CompanyId
      case 40000030: return ( &LanguageCode_ ); break; // LanguageCode
      case 40000180: return ( &Currency_ ); break; // Currency
      case 40002065: return ( &Track_ ); break; // Track
      case 40002066: return ( &Activity_ ); break; // Activity
      case 40002839: return ( &SecurityQuestion_ ); break; // SecurityQuestion
      case 40002840: return ( &SecurityAnswer_ ); break; // SecurityAnswer
      case 40002845: return ( &Mode_ ); break; // Mode
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0189_REQ::getElement( const BFFieldId& id ) const
{
   return( ( const_cast< dsi_DSTC0189_REQ* >(this) )->getElement( id ) );
}

BFDataField* dsi_DSTC0189_REQ::getElementByIndex( unsigned int iField )
{
   if ( iField >=0 && iField < 9 )
   {
      BFDataField* pField = aFlds_[iField];
      if( NULL == pField )
      {
         switch(iField)
         {
            case 0: aFlds_[0] = &User_Id_; break;
            case 1: aFlds_[1] = &CompanyId_; break;
            case 2: aFlds_[2] = &LanguageCode_; break;
            case 3: aFlds_[3] = &Currency_; break;
            case 4: aFlds_[4] = &Track_; break;
            case 5: aFlds_[5] = &Activity_; break;
            case 6: aFlds_[6] = &SecurityQuestion_; break;
            case 7: aFlds_[7] = &SecurityAnswer_; break;
            case 8: aFlds_[8] = &Mode_; break;
         }
         pField = aFlds_[iField];
         if( NULL == pField ) return( NULL );
      }
      return( pField );
   }
   return( NULL );
}

const BFDataField* dsi_DSTC0189_REQ::getElementByIndex( unsigned int iField ) const
{
   return( ( const_cast< dsi_DSTC0189_REQ* >(this) )->getElementByIndex( iField ) );
}

unsigned long dsi_DSTC0189_REQ::getLargestDefinedField( void ) const
{
   return( 200 );
}

unsigned long dsi_DSTC0189_REQ::getDefinedByteLength( void ) const
{
   return( 621 * sizeof( I_CHAR ) );
}

bool dsi_DSTC0189_REQ::exists( const BFFieldId& id ) const
{
   return dsi_DSTC0189_REQ::fieldExists( id );
}

bool dsi_DSTC0189_REQ::fieldExists( const BFFieldId& id )
{
   switch( id.getId() )
   {
      case 40000002: return( true );
      case 40000031: return( true );
      case 40000030: return( true );
      case 40000180: return( true );
      case 40002065: return( true );
      case 40002066: return( true );
      case 40002839: return( true );
      case 40002840: return( true );
      case 40002845: return( true );
   }
   return false;
}

