// BFDataImpl header file for DataSet DSTC0337.VWRepeat_Record
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:59 2015


#pragma once
#include <commonport.h>
#include <clientlocale.hpp>

#undef IFAST_DATAIMPL_LINKAGE
#ifdef IFAST_DATAIMPL_DLL
   #define IFAST_DATAIMPL_LINKAGE CLASS_EXPORT
#else
   #define IFAST_DATAIMPL_LINKAGE CLASS_IMPORT
#endif

namespace ifds
{
   //Field Externs
   extern const BFNumericFieldId TransNum;
   extern const BFTextFieldId RvCode;
   extern const BFTextFieldId OnStmt;
   extern const BFTextFieldId Accountable;
   extern const BFTextFieldId ConfirmRequired;
   extern const BFTextFieldId CancelCheque;
   extern const BFTextFieldId Remarks1;
   extern const BFTextFieldId Remarks2;
   extern const BFTextFieldId Remarks3;
   extern const BFTextFieldId Batch;
   extern const BFDecimalFieldId Trace;
   extern const BFTextFieldId TransType;
   extern const BFTextFieldId TranStatus;
   extern const BFTextFieldId Username;
   extern const BFTextFieldId ModUser;
   extern const BFDateFieldId ModDate;
   extern const BFTextFieldId VerifiedBy;
   extern const BFDateFieldId VerifyDate;
   extern const BFDateFieldId ProcessDate;
   extern const BFNumericFieldId TransId;
   extern const BFDecimalFieldId Version;
   extern const BFTextFieldId ModPermission;
   extern const BFTextFieldId CancellationType;
   extern const BFDateFieldId TradeDate;
   extern const BFTextFieldId Fund;
   extern const BFTextFieldId Class;
   extern const BFTextFieldId Rebook;
   extern const BFTextFieldId FundISIN;
   extern const BFTextFieldId FundWKN;
   extern const BFDecimalFieldId TradeAdjustID;
   extern const BFTextFieldId MCHFileIndicator;
   extern const BFTextFieldId SecRecFileIndicator;
   extern const BFTextFieldId RbkMCHFileIndicator;
   extern const BFTextFieldId RbkSecRecFileIndicator;
   extern const BFTextFieldId ESGSettle;
   extern const BFTextFieldId RefundPayType;
   extern const BFTextFieldId RefundOption;
   extern const BFDateFieldId EventReceiptDate;
   extern const BFTextFieldId EventReceiptTime;

   //Property Externs
   extern const BFDataFieldProperties s_FldProp_TransNum;
   extern const BFDataFieldProperties s_FldProp_RvCode;
   extern const BFDataFieldProperties s_FldProp_OnStmt;
   extern const BFDataFieldProperties s_FldProp_Accountable;
   extern const BFDataFieldProperties s_FldProp_ConfirmRequired;
   extern const BFDataFieldProperties s_FldProp_CancelCheque;
   extern const BFDataFieldProperties s_FldProp_Remarks1;
   extern const BFDataFieldProperties s_FldProp_Remarks2;
   extern const BFDataFieldProperties s_FldProp_Remarks3;
   extern const BFDataFieldProperties s_FldProp_Batch;
   extern const BFDataFieldProperties s_FldProp_Trace;
   extern const BFDataFieldProperties s_FldProp_TransType;
   extern const BFDataFieldProperties s_FldProp_TranStatus;
   extern const BFDataFieldProperties s_FldProp_Username;
   extern const BFDataFieldProperties s_FldProp_ModUser;
   extern const BFDataFieldProperties s_FldProp_ModDate;
   extern const BFDataFieldProperties s_FldProp_VerifiedBy;
   extern const BFDataFieldProperties s_FldProp_VerifyDate;
   extern const BFDataFieldProperties s_FldProp_ProcessDate;
   extern const BFDataFieldProperties s_FldProp_TransId;
   extern const BFDataFieldProperties s_FldProp_Version;
   extern const BFDataFieldProperties s_FldProp_ModPermission;
   extern const BFDataFieldProperties s_FldProp_CancellationType;
   extern const BFDataFieldProperties s_FldProp_TradeDate;
   extern const BFDataFieldProperties s_FldProp_Fund;
   extern const BFDataFieldProperties s_FldProp_Class;
   extern const BFDataFieldProperties s_FldProp_Rebook;
   extern const BFDataFieldProperties s_FldProp_FundISIN;
   extern const BFDataFieldProperties s_FldProp_FundWKN;
   extern const BFDataFieldProperties s_FldProp_TradeAdjustID;
   extern const BFDataFieldProperties s_FldProp_MCHFileIndicator;
   extern const BFDataFieldProperties s_FldProp_SecRecFileIndicator;
   extern const BFDataFieldProperties s_FldProp_RbkMCHFileIndicator;
   extern const BFDataFieldProperties s_FldProp_RbkSecRecFileIndicator;
   extern const BFDataFieldProperties s_FldProp_ESGSettle;
   extern const BFDataFieldProperties s_FldProp_RefundPayType;
   extern const BFDataFieldProperties s_FldProp_RefundOption;
   extern const BFDataFieldProperties s_FldProp_EventReceiptDate;
   extern const BFDataFieldProperties s_FldProp_EventReceiptTime;
}


class dsi_DSTC0337_VWRepeat_Record : public BFDataImpl 
{
public:
   // Constructors
   dsi_DSTC0337_VWRepeat_Record();
   virtual ~dsi_DSTC0337_VWRepeat_Record();

   virtual BFDataImpl* clone();

   virtual BFDataField* getElement( const BFFieldId& id );
   virtual const BFDataField* getElement( const BFFieldId& id ) const;
   virtual BFDataField* getElementByIndex( unsigned int iField );
   virtual const BFDataField* getElementByIndex( unsigned int iField ) const;


   virtual unsigned long getLargestDefinedField( void ) const;
   virtual unsigned long getDefinedByteLength( void ) const;
   virtual bool exists( const BFFieldId& id ) const;
   static bool fieldExists( const BFFieldId& id );

private:
   BFDataField* aFlds_[39];
   // Field Declarations
   BFNumericField TransNum_;
   BFTextField_60 RvCode_;
   BFTextField_1 OnStmt_;
   BFTextField_60 Accountable_;
   BFTextField_1 ConfirmRequired_;
   BFTextField_1 CancelCheque_;
   BFTextField<50> Remarks1_;
   BFTextField<50> Remarks2_;
   BFTextField<50> Remarks3_;
   BFTextField_60 Batch_;
   BFDecimalField Trace_;
   BFTextField_60 TransType_;
   BFTextField<5> TranStatus_;
   BFTextField_60 Username_;
   BFTextField_60 ModUser_;
   BFDateField ModDate_;
   BFTextField_60 VerifiedBy_;
   BFDateField VerifyDate_;
   BFDateField ProcessDate_;
   BFNumericField TransId_;
   BFDecimalField Version_;
   BFTextField_1 ModPermission_;
   BFTextField_60 CancellationType_;
   BFDateField TradeDate_;
   BFTextField_60 Fund_;
   BFTextField_60 Class_;
   BFTextField_2 Rebook_;
   BFTextField_60 FundISIN_;
   BFTextField_60 FundWKN_;
   BFDecimalField TradeAdjustID_;
   BFTextField_60 MCHFileIndicator_;
   BFTextField_60 SecRecFileIndicator_;
   BFTextField_60 RbkMCHFileIndicator_;
   BFTextField_60 RbkSecRecFileIndicator_;
   BFTextField_60 ESGSettle_;
   BFTextField_60 RefundPayType_;
   BFTextField_60 RefundOption_;
   BFDateField EventReceiptDate_;
   BFTextField<8> EventReceiptTime_;

};
