// BFSubstitution objects
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:58 2015


#include "stdafx.h"
#include <commonport.h>
#include <clientlocale.hpp>

namespace ifds
{
   extern const BFSubstitutionSet SubSet_Empty;
   // Chooser function for Substitution set CIB_InvHorizonSet.
   extern const BFSubstitutionSet SubSet_002_450_001_000_000;
   extern const BFSubstitutionSet SubSet_002_450_003_000_000;
   extern const BFSubstitutionSet SubSet_002_450_005_000_000;
   extern const BFSubstitutionSet SubSet_002_450_007_000_000;
   extern const BFSubstitutionSet SubSet_002_450_008_000_000;
   extern const BFSubstitutionSet SubSet_002_450_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_450( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_450_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_450_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_450_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_450_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_450_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_450_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_450_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set CIB_RiskToleranceSet.
   extern const BFSubstitutionSet SubSet_002_451_001_000_000;
   extern const BFSubstitutionSet SubSet_002_451_003_000_000;
   extern const BFSubstitutionSet SubSet_002_451_005_000_000;
   extern const BFSubstitutionSet SubSet_002_451_007_000_000;
   extern const BFSubstitutionSet SubSet_002_451_008_000_000;
   extern const BFSubstitutionSet SubSet_002_451_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_451( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_451_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_451_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_451_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_451_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_451_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_451_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_451_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set CIB_InvObjSet.
   extern const BFSubstitutionSet SubSet_002_452_001_000_000;
   extern const BFSubstitutionSet SubSet_002_452_003_000_000;
   extern const BFSubstitutionSet SubSet_002_452_005_000_000;
   extern const BFSubstitutionSet SubSet_002_452_007_000_000;
   extern const BFSubstitutionSet SubSet_002_452_008_000_000;
   extern const BFSubstitutionSet SubSet_002_452_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_452( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_452_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_452_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_452_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_452_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_452_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_452_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_452_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set CIB_InvPhilosophySet.
   extern const BFSubstitutionSet SubSet_002_453_001_000_000;
   extern const BFSubstitutionSet SubSet_002_453_003_000_000;
   extern const BFSubstitutionSet SubSet_002_453_005_000_000;
   extern const BFSubstitutionSet SubSet_002_453_007_000_000;
   extern const BFSubstitutionSet SubSet_002_453_008_000_000;
   extern const BFSubstitutionSet SubSet_002_453_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_453( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_453_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_453_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_453_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_453_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_453_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_453_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_453_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set CIB_SAMFinHealthSet.
   extern const BFSubstitutionSet SubSet_002_454_001_000_000;
   extern const BFSubstitutionSet SubSet_002_454_003_000_000;
   extern const BFSubstitutionSet SubSet_002_454_005_000_000;
   extern const BFSubstitutionSet SubSet_002_454_007_000_000;
   extern const BFSubstitutionSet SubSet_002_454_008_000_000;
   extern const BFSubstitutionSet SubSet_002_454_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_454( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_454_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_454_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_454_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_454_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_454_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_454_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_454_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BankInstrComboSetDefaultNoRRIF.
   extern const BFSubstitutionSet SubSet_002_455_001_000_000;
   extern const BFSubstitutionSet SubSet_002_455_003_000_000;
   extern const BFSubstitutionSet SubSet_002_455_005_000_000;
   extern const BFSubstitutionSet SubSet_002_455_007_000_000;
   extern const BFSubstitutionSet SubSet_002_455_008_000_000;
   extern const BFSubstitutionSet SubSet_002_455_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_455( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_455_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_455_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_455_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_455_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_455_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_455_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_455_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BankInstrComboSetTransaction.
   extern const BFSubstitutionSet SubSet_002_456_001_000_000;
   extern const BFSubstitutionSet SubSet_002_456_003_000_000;
   extern const BFSubstitutionSet SubSet_002_456_005_000_000;
   extern const BFSubstitutionSet SubSet_002_456_007_000_000;
   extern const BFSubstitutionSet SubSet_002_456_008_000_000;
   extern const BFSubstitutionSet SubSet_002_456_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_456( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_456_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_456_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_456_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_456_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_456_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_456_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_456_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BankInstrComboSetPendingTransaction.
   extern const BFSubstitutionSet SubSet_002_457_001_000_000;
   extern const BFSubstitutionSet SubSet_002_457_003_000_000;
   extern const BFSubstitutionSet SubSet_002_457_005_000_000;
   extern const BFSubstitutionSet SubSet_002_457_007_000_000;
   extern const BFSubstitutionSet SubSet_002_457_008_000_000;
   extern const BFSubstitutionSet SubSet_002_457_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_457( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_457_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_457_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_457_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_457_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_457_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_457_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_457_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BankInstrComboSetTrade.
   extern const BFSubstitutionSet SubSet_002_458_001_000_000;
   extern const BFSubstitutionSet SubSet_002_458_003_000_000;
   extern const BFSubstitutionSet SubSet_002_458_005_000_000;
   extern const BFSubstitutionSet SubSet_002_458_007_000_000;
   extern const BFSubstitutionSet SubSet_002_458_008_000_000;
   extern const BFSubstitutionSet SubSet_002_458_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_458( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_458_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_458_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_458_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_458_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_458_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_458_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_458_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BankInstrComboSetClient.
   extern const BFSubstitutionSet SubSet_002_459_001_000_000;
   extern const BFSubstitutionSet SubSet_002_459_003_000_000;
   extern const BFSubstitutionSet SubSet_002_459_005_000_000;
   extern const BFSubstitutionSet SubSet_002_459_007_000_000;
   extern const BFSubstitutionSet SubSet_002_459_008_000_000;
   extern const BFSubstitutionSet SubSet_002_459_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_459( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_459_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_459_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_459_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_459_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_459_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_459_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_459_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BankInstrComboSetFund.
   extern const BFSubstitutionSet SubSet_002_460_001_000_000;
   extern const BFSubstitutionSet SubSet_002_460_003_000_000;
   extern const BFSubstitutionSet SubSet_002_460_005_000_000;
   extern const BFSubstitutionSet SubSet_002_460_007_000_000;
   extern const BFSubstitutionSet SubSet_002_460_008_000_000;
   extern const BFSubstitutionSet SubSet_002_460_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_460( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_460_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_460_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_460_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_460_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_460_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_460_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_460_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BankInstrComboSetSettlement.
   extern const BFSubstitutionSet SubSet_002_461_001_000_000;
   extern const BFSubstitutionSet SubSet_002_461_003_000_000;
   extern const BFSubstitutionSet SubSet_002_461_005_000_000;
   extern const BFSubstitutionSet SubSet_002_461_007_000_000;
   extern const BFSubstitutionSet SubSet_002_461_008_000_000;
   extern const BFSubstitutionSet SubSet_002_461_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_461( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_461_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_461_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_461_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_461_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_461_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_461_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_461_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BrokerFeaturesSearchCriteriaSet.
   extern const BFSubstitutionSet SubSet_002_462_001_000_000;
   extern const BFSubstitutionSet SubSet_002_462_003_000_000;
   extern const BFSubstitutionSet SubSet_002_462_005_000_000;
   extern const BFSubstitutionSet SubSet_002_462_007_000_000;
   extern const BFSubstitutionSet SubSet_002_462_008_000_000;
   extern const BFSubstitutionSet SubSet_002_462_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_462( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_462_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_462_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_462_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_462_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_462_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_462_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_462_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BrokerFeaturesSearchPayToEntityUsingSet.
   extern const BFSubstitutionSet SubSet_002_463_001_000_000;
   extern const BFSubstitutionSet SubSet_002_463_003_000_000;
   extern const BFSubstitutionSet SubSet_002_463_005_000_000;
   extern const BFSubstitutionSet SubSet_002_463_007_000_000;
   extern const BFSubstitutionSet SubSet_002_463_008_000_000;
   extern const BFSubstitutionSet SubSet_002_463_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_463( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_463_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_463_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_463_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_463_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_463_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_463_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_463_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BrokerFeaturesSearchPaymentInstructionsUsingSet.
   extern const BFSubstitutionSet SubSet_002_464_001_000_000;
   extern const BFSubstitutionSet SubSet_002_464_003_000_000;
   extern const BFSubstitutionSet SubSet_002_464_005_000_000;
   extern const BFSubstitutionSet SubSet_002_464_007_000_000;
   extern const BFSubstitutionSet SubSet_002_464_008_000_000;
   extern const BFSubstitutionSet SubSet_002_464_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_464( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_464_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_464_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_464_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_464_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_464_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_464_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_464_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BrokerFeaturesSearchLabelsSet.
   extern const BFSubstitutionSet SubSet_002_465_001_000_000;
   extern const BFSubstitutionSet SubSet_002_465_003_000_000;
   extern const BFSubstitutionSet SubSet_002_465_005_000_000;
   extern const BFSubstitutionSet SubSet_002_465_007_000_000;
   extern const BFSubstitutionSet SubSet_002_465_008_000_000;
   extern const BFSubstitutionSet SubSet_002_465_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_465( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_465_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_465_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_465_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_465_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_465_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_465_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_465_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BrokerFeaturesSearchCriteriaNoSet.
   extern const BFSubstitutionSet SubSet_002_466_001_000_000;
   extern const BFSubstitutionSet SubSet_002_466_003_000_000;
   extern const BFSubstitutionSet SubSet_002_466_005_000_000;
   extern const BFSubstitutionSet SubSet_002_466_007_000_000;
   extern const BFSubstitutionSet SubSet_002_466_008_000_000;
   extern const BFSubstitutionSet SubSet_002_466_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_466( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_466_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_466_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_466_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_466_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_466_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_466_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_466_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set MainSearchCriteriaNoSet.
   extern const BFSubstitutionSet SubSet_002_467_001_000_000;
   extern const BFSubstitutionSet SubSet_002_467_003_000_000;
   extern const BFSubstitutionSet SubSet_002_467_005_000_000;
   extern const BFSubstitutionSet SubSet_002_467_007_000_000;
   extern const BFSubstitutionSet SubSet_002_467_008_000_000;
   extern const BFSubstitutionSet SubSet_002_467_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_467( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_467_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_467_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_467_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_467_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_467_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_467_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_467_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BrokerFeaturesSearchBankingUsingSet.
   extern const BFSubstitutionSet SubSet_002_468_001_000_000;
   extern const BFSubstitutionSet SubSet_002_468_003_000_000;
   extern const BFSubstitutionSet SubSet_002_468_005_000_000;
   extern const BFSubstitutionSet SubSet_002_468_007_000_000;
   extern const BFSubstitutionSet SubSet_002_468_008_000_000;
   extern const BFSubstitutionSet SubSet_002_468_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_468( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_468_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_468_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_468_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_468_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_468_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_468_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_468_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set PayToEntitySet.
   extern const BFSubstitutionSet SubSet_002_469_001_000_000;
   extern const BFSubstitutionSet SubSet_002_469_003_000_000;
   extern const BFSubstitutionSet SubSet_002_469_005_000_000;
   extern const BFSubstitutionSet SubSet_002_469_007_000_000;
   extern const BFSubstitutionSet SubSet_002_469_008_000_000;
   extern const BFSubstitutionSet SubSet_002_469_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_469( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_469_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_469_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_469_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_469_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_469_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_469_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_469_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set PayToEntityNoAllSet.
   extern const BFSubstitutionSet SubSet_002_470_001_000_000;
   extern const BFSubstitutionSet SubSet_002_470_003_000_000;
   extern const BFSubstitutionSet SubSet_002_470_005_000_000;
   extern const BFSubstitutionSet SubSet_002_470_007_000_000;
   extern const BFSubstitutionSet SubSet_002_470_008_000_000;
   extern const BFSubstitutionSet SubSet_002_470_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_470( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_470_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_470_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_470_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_470_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_470_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_470_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_470_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set PaymentForSet.
   extern const BFSubstitutionSet SubSet_002_471_001_000_000;
   extern const BFSubstitutionSet SubSet_002_471_003_000_000;
   extern const BFSubstitutionSet SubSet_002_471_005_000_000;
   extern const BFSubstitutionSet SubSet_002_471_007_000_000;
   extern const BFSubstitutionSet SubSet_002_471_008_000_000;
   extern const BFSubstitutionSet SubSet_002_471_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_471( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_471_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_471_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_471_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_471_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_471_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_471_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_471_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set LV_PayToEntityListHeadingSet.
   extern const BFSubstitutionSet SubSet_002_472_001_000_000;
   extern const BFSubstitutionSet SubSet_002_472_003_000_000;
   extern const BFSubstitutionSet SubSet_002_472_005_000_000;
   extern const BFSubstitutionSet SubSet_002_472_007_000_000;
   extern const BFSubstitutionSet SubSet_002_472_008_000_000;
   extern const BFSubstitutionSet SubSet_002_472_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_472( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_472_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_472_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_472_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_472_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_472_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_472_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_472_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set AddressStatusSet.
   extern const BFSubstitutionSet SubSet_002_473_001_000_000;
   extern const BFSubstitutionSet SubSet_002_473_003_000_000;
   extern const BFSubstitutionSet SubSet_002_473_005_000_000;
   extern const BFSubstitutionSet SubSet_002_473_007_000_000;
   extern const BFSubstitutionSet SubSet_002_473_008_000_000;
   extern const BFSubstitutionSet SubSet_002_473_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_473( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_473_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_473_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_473_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_473_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_473_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_473_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_473_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set CurrencyOptionSet.
   extern const BFSubstitutionSet SubSet_002_474_001_000_000;
   extern const BFSubstitutionSet SubSet_002_474_003_000_000;
   extern const BFSubstitutionSet SubSet_002_474_005_000_000;
   extern const BFSubstitutionSet SubSet_002_474_007_000_000;
   extern const BFSubstitutionSet SubSet_002_474_008_000_000;
   extern const BFSubstitutionSet SubSet_002_474_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_474( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_474_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_474_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_474_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_474_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_474_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_474_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_474_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set LV_PaymentInstructionsListHeadingSet.
   extern const BFSubstitutionSet SubSet_002_475_001_000_000;
   extern const BFSubstitutionSet SubSet_002_475_003_000_000;
   extern const BFSubstitutionSet SubSet_002_475_005_000_000;
   extern const BFSubstitutionSet SubSet_002_475_007_000_000;
   extern const BFSubstitutionSet SubSet_002_475_008_000_000;
   extern const BFSubstitutionSet SubSet_002_475_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_475( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_475_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_475_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_475_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_475_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_475_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_475_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_475_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BrokerFeaturesSearchHistoricalInfoUsingSet.
   extern const BFSubstitutionSet SubSet_002_476_001_000_000;
   extern const BFSubstitutionSet SubSet_002_476_003_000_000;
   extern const BFSubstitutionSet SubSet_002_476_005_000_000;
   extern const BFSubstitutionSet SubSet_002_476_007_000_000;
   extern const BFSubstitutionSet SubSet_002_476_008_000_000;
   extern const BFSubstitutionSet SubSet_002_476_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_476( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_476_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_476_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_476_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_476_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_476_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_476_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_476_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set PaymentIntructionsPayTypeSet.
   extern const BFSubstitutionSet SubSet_002_477_001_000_000;
   extern const BFSubstitutionSet SubSet_002_477_003_000_000;
   extern const BFSubstitutionSet SubSet_002_477_005_000_000;
   extern const BFSubstitutionSet SubSet_002_477_007_000_000;
   extern const BFSubstitutionSet SubSet_002_477_008_000_000;
   extern const BFSubstitutionSet SubSet_002_477_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_477( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_477_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_477_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_477_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_477_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_477_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_477_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_477_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set BAFFFileProcessorSet.
   extern const BFSubstitutionSet SubSet_002_478_001_000_000;
   extern const BFSubstitutionSet SubSet_002_478_003_000_000;
   extern const BFSubstitutionSet SubSet_002_478_005_000_000;
   extern const BFSubstitutionSet SubSet_002_478_007_000_000;
   extern const BFSubstitutionSet SubSet_002_478_008_000_000;
   extern const BFSubstitutionSet SubSet_002_478_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_478( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_478_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_478_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_478_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_478_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_478_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_478_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_478_001_000_000; // defined in ifast_substitutions_15.cpp
   }

   // Chooser function for Substitution set AddressLineSet.
   extern const BFSubstitutionSet SubSet_002_479_001_000_000;
   extern const BFSubstitutionSet SubSet_002_479_003_000_000;
   extern const BFSubstitutionSet SubSet_002_479_005_000_000;
   extern const BFSubstitutionSet SubSet_002_479_007_000_000;
   extern const BFSubstitutionSet SubSet_002_479_008_000_000;
   extern const BFSubstitutionSet SubSet_002_479_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_479( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_479_001_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_479_003_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_479_005_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_479_007_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_479_008_000_000; // defined in ifast_substitutions_15.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_479_010_000_000; // defined in ifast_substitutions_15.cpp
      }
      return SubSet_002_479_001_000_000; // defined in ifast_substitutions_15.cpp
   }

}
