// BFSubstitution objects
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:58 2015


#include "stdafx.h"
#include <commonport.h>
#include <clientlocale.hpp>

namespace ifds
{
   extern const BFSubstitutionSet SubSet_Empty;
   // Chooser function for Substitution set LV_FinancialInstitutionsHeadingSet.
   extern const BFSubstitutionSet SubSet_002_510_001_000_000;
   extern const BFSubstitutionSet SubSet_002_510_003_000_000;
   extern const BFSubstitutionSet SubSet_002_510_005_000_000;
   extern const BFSubstitutionSet SubSet_002_510_007_000_000;
   extern const BFSubstitutionSet SubSet_002_510_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_510( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_510_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_510_003_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_510_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_510_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_510_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_510_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set LV_TransitsHeadingSet.
   extern const BFSubstitutionSet SubSet_002_511_001_000_000;
   extern const BFSubstitutionSet SubSet_002_511_003_000_000;
   extern const BFSubstitutionSet SubSet_002_511_005_000_000;
   extern const BFSubstitutionSet SubSet_002_511_007_000_000;
   extern const BFSubstitutionSet SubSet_002_511_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_511( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_511_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_511_003_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_511_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_511_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_511_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_511_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set DTATypeSet.
   extern const BFSubstitutionSet SubSet_002_512_001_000_000;
   extern const BFSubstitutionSet SubSet_002_512_003_000_000;
   extern const BFSubstitutionSet SubSet_002_512_005_000_000;
   extern const BFSubstitutionSet SubSet_002_512_007_000_000;
   extern const BFSubstitutionSet SubSet_002_512_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_512( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_512_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_512_003_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_512_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_512_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_512_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_512_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set LV_DTABANKHEADERSET.
   extern const BFSubstitutionSet SubSet_002_513_001_000_000;
   extern const BFSubstitutionSet SubSet_002_513_003_000_000;
   extern const BFSubstitutionSet SubSet_002_513_005_000_000;
   extern const BFSubstitutionSet SubSet_002_513_007_000_000;
   extern const BFSubstitutionSet SubSet_002_513_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_513( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_513_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_513_003_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_513_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_513_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_513_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_513_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set BankInstrComboSetDirectTrading.
   extern const BFSubstitutionSet SubSet_002_514_001_000_000;
   extern const BFSubstitutionSet SubSet_002_514_003_000_000;
   extern const BFSubstitutionSet SubSet_002_514_005_000_000;
   extern const BFSubstitutionSet SubSet_002_514_007_000_000;
   extern const BFSubstitutionSet SubSet_002_514_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_514( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_514_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_514_003_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_514_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_514_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_514_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_514_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set DTATypeCommercialSet.
   extern const BFSubstitutionSet SubSet_002_515_001_000_000;
   extern const BFSubstitutionSet SubSet_002_515_003_000_000;
   extern const BFSubstitutionSet SubSet_002_515_005_000_000;
   extern const BFSubstitutionSet SubSet_002_515_007_000_000;
   extern const BFSubstitutionSet SubSet_002_515_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_515( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_515_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_515_003_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_515_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_515_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_515_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_515_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set DTATypeNonCommercialSet.
   extern const BFSubstitutionSet SubSet_002_516_001_000_000;
   extern const BFSubstitutionSet SubSet_002_516_003_000_000;
   extern const BFSubstitutionSet SubSet_002_516_005_000_000;
   extern const BFSubstitutionSet SubSet_002_516_007_000_000;
   extern const BFSubstitutionSet SubSet_002_516_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_516( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_516_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_516_003_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_516_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_516_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_516_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_516_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set LV_DTA_HEADERSET.
   extern const BFSubstitutionSet SubSet_002_517_001_000_000;
   extern const BFSubstitutionSet SubSet_002_517_005_000_000;
   extern const BFSubstitutionSet SubSet_002_517_007_000_000;
   extern const BFSubstitutionSet SubSet_002_517_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_517( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_517_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_517_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_517_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_517_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_517_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set CodePageSet.
   extern const BFSubstitutionSet SubSet_002_518_001_000_000;
   extern const BFSubstitutionSet SubSet_002_518_005_000_000;
   extern const BFSubstitutionSet SubSet_002_518_007_000_000;
   extern const BFSubstitutionSet SubSet_002_518_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_518( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_518_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_518_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_518_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_518_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_518_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set StatusCodeActiveSet.
   extern const BFSubstitutionSet SubSet_002_519_001_000_000;
   extern const BFSubstitutionSet SubSet_002_519_005_000_000;
   extern const BFSubstitutionSet SubSet_002_519_007_000_000;
   extern const BFSubstitutionSet SubSet_002_519_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_519( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_519_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_519_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_519_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_519_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_519_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set InstRoleSet.
   extern const BFSubstitutionSet SubSet_002_520_001_000_000;
   extern const BFSubstitutionSet SubSet_002_520_005_000_000;
   extern const BFSubstitutionSet SubSet_002_520_007_000_000;
   extern const BFSubstitutionSet SubSet_002_520_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_520( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_520_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_520_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_520_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_520_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_520_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set InstCategorySet.
   extern const BFSubstitutionSet SubSet_002_522_001_000_000;
   extern const BFSubstitutionSet SubSet_002_522_005_000_000;
   extern const BFSubstitutionSet SubSet_002_522_007_000_000;
   extern const BFSubstitutionSet SubSet_002_522_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_522( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_522_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_522_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_522_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_522_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_522_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set TransitsCategorySet.
   extern const BFSubstitutionSet SubSet_002_523_001_000_000;
   extern const BFSubstitutionSet SubSet_002_523_005_000_000;
   extern const BFSubstitutionSet SubSet_002_523_007_000_000;
   extern const BFSubstitutionSet SubSet_002_523_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_523( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_523_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_523_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_523_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_523_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_523_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set YesNoSet2.
   extern const BFSubstitutionSet SubSet_002_524_001_000_000;
   extern const BFSubstitutionSet SubSet_002_524_005_000_000;
   extern const BFSubstitutionSet SubSet_002_524_007_000_000;
   extern const BFSubstitutionSet SubSet_002_524_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_524( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_524_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_524_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_524_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_524_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_524_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set FIFeaturesSearchTransitsUsingSet.
   extern const BFSubstitutionSet SubSet_002_525_001_000_000;
   extern const BFSubstitutionSet SubSet_002_525_005_000_000;
   extern const BFSubstitutionSet SubSet_002_525_007_000_000;
   extern const BFSubstitutionSet SubSet_002_525_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_525( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_525_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_525_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_525_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_525_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_525_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set PensionLegCodeSet.
   extern const BFSubstitutionSet SubSet_002_526_001_000_000;
   extern const BFSubstitutionSet SubSet_002_526_005_000_000;
   extern const BFSubstitutionSet SubSet_002_526_007_000_000;
   extern const BFSubstitutionSet SubSet_002_526_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_526( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_526_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_526_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_526_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_526_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_526_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set LV_SettleLocationAcctLvlHeadingSet.
   extern const BFSubstitutionSet SubSet_002_527_001_000_000;
   extern const BFSubstitutionSet SubSet_002_527_005_000_000;
   extern const BFSubstitutionSet SubSet_002_527_007_000_000;
   extern const BFSubstitutionSet SubSet_002_527_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_527( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_527_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_527_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_527_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_527_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_527_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set LV_SettleLocationSysLvlHeadingSet.
   extern const BFSubstitutionSet SubSet_002_528_001_000_000;
   extern const BFSubstitutionSet SubSet_002_528_005_000_000;
   extern const BFSubstitutionSet SubSet_002_528_007_000_000;
   extern const BFSubstitutionSet SubSet_002_528_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_528( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_528_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_528_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_528_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_528_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_528_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set LV_FreeAmountHeadingSet.
   extern const BFSubstitutionSet SubSet_002_529_001_000_000;
   extern const BFSubstitutionSet SubSet_002_529_005_000_000;
   extern const BFSubstitutionSet SubSet_002_529_007_000_000;
   extern const BFSubstitutionSet SubSet_002_529_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_529( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_529_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_529_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_529_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_529_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_529_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set ClearingMethodSet.
   extern const BFSubstitutionSet SubSet_002_530_001_000_000;
   extern const BFSubstitutionSet SubSet_002_530_005_000_000;
   extern const BFSubstitutionSet SubSet_002_530_007_000_000;
   extern const BFSubstitutionSet SubSet_002_530_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_530( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_530_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_530_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_530_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_530_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_530_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set ClearingIDSet.
   extern const BFSubstitutionSet SubSet_002_533_001_000_000;
   extern const BFSubstitutionSet SubSet_002_533_005_000_000;
   extern const BFSubstitutionSet SubSet_002_533_007_000_000;
   extern const BFSubstitutionSet SubSet_002_533_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_533( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_533_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_533_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_533_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_533_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_533_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set PurchasePayTypeSet.
   extern const BFSubstitutionSet SubSet_002_534_001_003_000;
   extern const BFSubstitutionSet SubSet_002_534_001_004_000;
   extern const BFSubstitutionSet SubSet_002_534_001_000_000;
   extern const BFSubstitutionSet SubSet_002_534_003_004_000;
   extern const BFSubstitutionSet SubSet_002_534_004_004_000;
   extern const BFSubstitutionSet SubSet_002_534_005_003_000;
   extern const BFSubstitutionSet SubSet_002_534_005_004_000;
   extern const BFSubstitutionSet SubSet_002_534_005_000_000;
   extern const BFSubstitutionSet SubSet_002_534_006_004_000;
   extern const BFSubstitutionSet SubSet_002_534_007_003_000;
   extern const BFSubstitutionSet SubSet_002_534_007_004_000;
   extern const BFSubstitutionSet SubSet_002_534_007_000_000;
   extern const BFSubstitutionSet SubSet_002_534_008_004_000;
   extern const BFSubstitutionSet SubSet_002_534_009_004_000;
   extern const BFSubstitutionSet SubSet_002_534_010_003_000;
   extern const BFSubstitutionSet SubSet_002_534_010_004_000;
   extern const BFSubstitutionSet SubSet_002_534_010_000_000;
   extern const BFSubstitutionSet SubSet_002_534_011_004_000;
   extern const BFSubstitutionSet SubSet_002_534_012_004_000;
   const BFSubstitutionSet& chooser_ss_002_534( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_534_001_003_000; // defined in ifast_substitutions_17.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_001_004_000; // defined in ifast_substitutions_17.cpp
         }
         return SubSet_002_534_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_003_004_000; // defined in ifast_substitutions_17.cpp
         }
      }
      if ( locale.getLocale() == I_("frFR") ) {
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_004_004_000; // defined in ifast_substitutions_17.cpp
         }
      }
      if ( locale.getLocale() == I_("frCA") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_534_005_003_000; // defined in ifast_substitutions_17.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_005_004_000; // defined in ifast_substitutions_17.cpp
         }
         return SubSet_002_534_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_006_004_000; // defined in ifast_substitutions_17.cpp
         }
      }
      if ( locale.getLocale() == I_("deDE") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_534_007_003_000; // defined in ifast_substitutions_17.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_007_004_000; // defined in ifast_substitutions_17.cpp
         }
         return SubSet_002_534_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_008_004_000; // defined in ifast_substitutions_17.cpp
         }
      }
      if ( locale.getLocale() == I_("enGB") ) {
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_009_004_000; // defined in ifast_substitutions_17.cpp
         }
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_534_010_003_000; // defined in ifast_substitutions_17.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_010_004_000; // defined in ifast_substitutions_17.cpp
         }
         return SubSet_002_534_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("itIT") ) {
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_011_004_000; // defined in ifast_substitutions_17.cpp
         }
      }
      if ( locale.getLocale() == I_("thTH") ) {
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_534_012_004_000; // defined in ifast_substitutions_17.cpp
         }
      }
      return SubSet_002_534_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set FireFighterDescSet.
   extern const BFSubstitutionSet SubSet_002_535_001_000_000;
   extern const BFSubstitutionSet SubSet_002_535_005_000_000;
   extern const BFSubstitutionSet SubSet_002_535_007_000_000;
   extern const BFSubstitutionSet SubSet_002_535_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_535( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_535_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_535_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_535_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_535_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_535_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set LV_TradingAttributesSplitCommSet.
   extern const BFSubstitutionSet SubSet_002_536_001_000_000;
   extern const BFSubstitutionSet SubSet_002_536_005_000_000;
   extern const BFSubstitutionSet SubSet_002_536_007_000_000;
   extern const BFSubstitutionSet SubSet_002_536_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_536( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_536_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_536_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_536_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_536_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_536_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set DTFFeaturesSearchDailyTransactionsFeesUsingSet.
   extern const BFSubstitutionSet SubSet_002_537_001_000_000;
   extern const BFSubstitutionSet SubSet_002_537_005_000_000;
   extern const BFSubstitutionSet SubSet_002_537_007_000_000;
   extern const BFSubstitutionSet SubSet_002_537_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_537( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_537_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_537_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_537_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_537_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_537_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set DTFFeaturesSearchLabelsSet.
   extern const BFSubstitutionSet SubSet_002_538_001_000_000;
   extern const BFSubstitutionSet SubSet_002_538_005_000_000;
   extern const BFSubstitutionSet SubSet_002_538_007_000_000;
   extern const BFSubstitutionSet SubSet_002_538_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_538( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_538_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_538_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_538_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_538_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_538_001_000_000; // defined in ifast_substitutions_17.cpp
   }

   // Chooser function for Substitution set DTFFeaturesSearchCriteriaSet.
   extern const BFSubstitutionSet SubSet_002_539_001_000_000;
   extern const BFSubstitutionSet SubSet_002_539_005_000_000;
   extern const BFSubstitutionSet SubSet_002_539_007_000_000;
   extern const BFSubstitutionSet SubSet_002_539_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_539( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_539_001_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_539_005_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_539_007_000_000; // defined in ifast_substitutions_17.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_539_010_000_000; // defined in ifast_substitutions_17.cpp
      }
      return SubSet_002_539_001_000_000; // defined in ifast_substitutions_17.cpp
   }

}
