// FieldIds
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 16:00:00 2015

#include "stdafx.h"




#include <bfdata/bffieldid.hpp>

namespace ifds
{
   extern CLASS_EXPORT const BFDecimalFieldId DistribFundLvlVer( 40002600 , I_("DistribFundLvlVer") );
   extern CLASS_EXPORT const BFTextFieldId ExchInFeeExist( 40002601 , I_("ExchInFeeExist") );
   extern CLASS_EXPORT const BFDecimalFieldId ExchInFeeDefault( 40002603 , I_("ExchInFeeDefault") );
   extern CLASS_EXPORT const BFTextFieldId ExchInFeeDefType( 40002604 , I_("ExchInFeeDefType") );
   extern CLASS_EXPORT const BFDecimalFieldId ExchInFeeMax( 40002605 , I_("ExchInFeeMax") );
   extern CLASS_EXPORT const BFDecimalFieldId ExchInFeeMin( 40002606 , I_("ExchInFeeMin") );
   extern CLASS_EXPORT const BFTextFieldId SortByFundName( 40002607 , I_("SortByFundName") );
   extern CLASS_EXPORT const BFTextFieldId AmountTypeSettleCurr( 40002613 , I_("AmountTypeSettleCurr") );
   extern CLASS_EXPORT const BFTextFieldId AmountTypeSystematic( 40002614 , I_("AmountTypeSystematic") );
   extern CLASS_EXPORT const BFTextFieldId EntityTypeDofB( 40002615 , I_("EntityTypeDofB") );
   extern CLASS_EXPORT const BFTextFieldId OwnerFirstName( 40002624 , I_("OwnerFirstName") );
   extern CLASS_EXPORT const BFTextFieldId OwnerLastName( 40002625 , I_("OwnerLastName") );
   extern CLASS_EXPORT const BFTextFieldId SponsorName( 40002626 , I_("SponsorName") );
   extern CLASS_EXPORT const BFTextFieldId SponsorCode( 40002627 , I_("SponsorCode") );
   extern CLASS_EXPORT const BFTextFieldId DistribPayType( 40002628 , I_("DistribPayType") );
   extern CLASS_EXPORT const BFTextFieldId TradingAvailable( 40002633 , I_("TradingAvailable") );
   extern CLASS_EXPORT const BFTextFieldId BatchOrdType( 40002634 , I_("BatchOrdType") );
   extern CLASS_EXPORT const BFTextFieldId ManualSettleDates( 40002635 , I_("ManualSettleDates") );
   extern CLASS_EXPORT const BFTextFieldId ExactDate( 40002636 , I_("ExactDate") );
   extern CLASS_EXPORT const BFTextFieldId SortBySpName( 40002637 , I_("SortBySpName") );
   extern CLASS_EXPORT const BFTextFieldId Sponsor( 40002652 , I_("Sponsor") );
   extern CLASS_EXPORT const BFNumericFieldId FundIdx( 40002653 , I_("FundIdx") );
   extern CLASS_EXPORT const BFNumericFieldId ClassStartIdx( 40002654 , I_("ClassStartIdx") );
   extern CLASS_EXPORT const BFNumericFieldId ClassEndIdx( 40002655 , I_("ClassEndIdx") );
   extern CLASS_EXPORT const BFNumericFieldId ClassIndex( 40002656 , I_("ClassIndex") );
   extern CLASS_EXPORT const BFTextFieldId NewMoney( 40002657 , I_("NewMoney") );
   extern CLASS_EXPORT const BFTextFieldId ACHSavingsPlan( 40002659 , I_("ACHSavingsPlan") );
   extern CLASS_EXPORT const BFTextFieldId AmtTypeMultiCurrency( 40002660 , I_("AmtTypeMultiCurrency") );
   extern CLASS_EXPORT const BFTextFieldId ACHPAC( 40002661 , I_("ACHPAC") );
   extern CLASS_EXPORT const BFTextFieldId PACSWPFrequency( 40002662 , I_("PACSWPFrequency") );
   extern CLASS_EXPORT const BFTextFieldId VUBCrossedit( 40002684 , I_("VUBCrossedit") );
   extern CLASS_EXPORT const BFDecimalFieldId PolicyTerm( 40002685 , I_("PolicyTerm") );
   extern CLASS_EXPORT const BFDateFieldId MaturDate( 40002689 , I_("MaturDate") );
   extern CLASS_EXPORT const BFTextFieldId IFASNumber( 40002697 , I_("IFASNumber") );
   extern CLASS_EXPORT const BFDateFieldId InitPurchDate( 40002698 , I_("InitPurchDate") );
   extern CLASS_EXPORT const BFDateFieldId InitInvestDate( 40002699 , I_("InitInvestDate") );
   extern CLASS_EXPORT const BFDateFieldId ContStartDate( 40002700 , I_("ContStartDate") );
   extern CLASS_EXPORT const BFDateFieldId ContEndDate( 40002701 , I_("ContEndDate") );
   extern CLASS_EXPORT const BFTextFieldId AutoCreate( 40002705 , I_("AutoCreate") );
   extern CLASS_EXPORT const BFTextFieldId ESoPStatus( 40002706 , I_("ESoPStatus") );
   extern CLASS_EXPORT const BFDateFieldId InactiveDate( 40002707 , I_("InactiveDate") );
   extern CLASS_EXPORT const BFDateFieldId BlockStartDate( 40002708 , I_("BlockStartDate") );
   extern CLASS_EXPORT const BFDateFieldId BlockEndDate( 40002709 , I_("BlockEndDate") );
   extern CLASS_EXPORT const BFDateFieldId ContExpireDate( 40002710 , I_("ContExpireDate") );
   extern CLASS_EXPORT const BFDateFieldId InterruptDate( 40002711 , I_("InterruptDate") );
   extern CLASS_EXPORT const BFTextFieldId InterruptCode( 40002712 , I_("InterruptCode") );
   extern CLASS_EXPORT const BFDateFieldId BankEffectiveDate( 40002713 , I_("BankEffectiveDate") );
   extern CLASS_EXPORT const BFTextFieldId AddressMailingColumnSet( 40002715 , I_("AddressMailingColumnSet") );
   extern CLASS_EXPORT const BFTextFieldId Market( 40002718 , I_("Market") );
   extern CLASS_EXPORT const BFDecimalFieldId ContribYear( 40002719 , I_("ContribYear") );
   extern CLASS_EXPORT const BFDecimalFieldId First60days( 40002720 , I_("First60days") );
   extern CLASS_EXPORT const BFDecimalFieldId Remaining( 40002721 , I_("Remaining") );
   extern CLASS_EXPORT const BFDecimalFieldId TaxYear( 40002722 , I_("TaxYear") );
   extern CLASS_EXPORT const BFDecimalFieldId RcptNum( 40002723 , I_("RcptNum") );
   extern CLASS_EXPORT const BFTextFieldId RcptStatus( 40002724 , I_("RcptStatus") );
   extern CLASS_EXPORT const BFDecimalFieldId RcptAmount( 40002725 , I_("RcptAmount") );
   extern CLASS_EXPORT const BFDecimalFieldId Duplicates( 40002726 , I_("Duplicates") );
   extern CLASS_EXPORT const BFTextFieldId AmountTypeAT( 40002734 , I_("AmountTypeAT") );
   extern CLASS_EXPORT const BFTextFieldId SlsRepListHeading1( 40002736 , I_("SlsRepListHeading1") );
   extern CLASS_EXPORT const BFTextFieldId RSPContributionHeadingSet( 40002737 , I_("RSPContributionHeadingSet") );
   extern CLASS_EXPORT const BFTextFieldId RSPReceiptsHeadingSet( 40002738 , I_("RSPReceiptsHeadingSet") );
   extern CLASS_EXPORT const BFTextFieldId ExchInFeeFlatPercent( 40002739 , I_("ExchInFeeFlatPercent") );
   extern CLASS_EXPORT const BFTextFieldId RemarksLine( 40002740 , I_("RemarksLine") );
   extern CLASS_EXPORT const BFTextFieldId MatchTransferHeading( 40002741 , I_("MatchTransferHeading") );
   extern CLASS_EXPORT const BFTextFieldId MatchTransferAttrTop( 40002742 , I_("MatchTransferAttrTop") );
   extern CLASS_EXPORT const BFTextFieldId MatchTransferAttrLeft( 40002743 , I_("MatchTransferAttrLeft") );
   extern CLASS_EXPORT const BFTextFieldId ClientID( 40002744 , I_("ClientID") );
   extern CLASS_EXPORT const BFTextFieldId ForeignContent( 40002748 , I_("ForeignContent") );
   extern CLASS_EXPORT const BFTextFieldId AsPensionEligibleQ4( 40002750 , I_("AsPensionEligibleQ4") );
   extern CLASS_EXPORT const BFTextFieldId AsPensionEligibleOth( 40002751 , I_("AsPensionEligibleOth") );
   extern CLASS_EXPORT const BFDecimalFieldId rxTransId( 40002752 , I_("rxTransId") );
   extern CLASS_EXPORT const BFTextFieldId ESoPEligible( 40002753 , I_("ESoPEligible") );
   extern CLASS_EXPORT const BFTextFieldId ASStatus( 40002755 , I_("ASStatus") );
   extern CLASS_EXPORT const BFTextFieldId ASStatusDesc( 40002756 , I_("ASStatusDesc") );
   extern CLASS_EXPORT const BFNumericFieldId TransferTransId( 40002765 , I_("TransferTransId") );
   extern CLASS_EXPORT const BFTextFieldId AgencyCode( 40002769 , I_("AgencyCode") );
   extern CLASS_EXPORT const BFTextFieldId AgentCode( 40002770 , I_("AgentCode") );
   extern CLASS_EXPORT const BFTextFieldId EntityName( 40002771 , I_("EntityName") );
   extern CLASS_EXPORT const BFDecimalFieldId SplCommRid( 40002772 , I_("SplCommRid") );
   extern CLASS_EXPORT const BFTextFieldId InTrustJointName( 40002776 , I_("InTrustJointName") );
   extern CLASS_EXPORT const BFTextFieldId AcctSplitCommDateHeadingSet( 40002777 , I_("AcctSplitCommDateHeadingSet") );
   extern CLASS_EXPORT const BFTextFieldId AcctSplitCommRepHeadingSet( 40002778 , I_("AcctSplitCommRepHeadingSet") );
   extern CLASS_EXPORT const BFDecimalFieldId EsopVersion( 40002779 , I_("EsopVersion") );
   extern CLASS_EXPORT const BFDecimalFieldId EsopRid( 40002781 , I_("EsopRid") );
   extern CLASS_EXPORT const BFTextFieldId ProdCode( 40002782 , I_("ProdCode") );
   extern CLASS_EXPORT const BFTextFieldId AcctSplitCommCEF1( 40002783 , I_("AcctSplitCommCEF1") );
   extern CLASS_EXPORT const BFTextFieldId AllowUnitsPurchase( 40002784 , I_("AllowUnitsPurchase") );
   extern CLASS_EXPORT const BFTextFieldId MultiCurrEFTUnitPurch( 40002785 , I_("MultiCurrEFTUnitPurch") );
   extern CLASS_EXPORT const BFTextFieldId DisAllowPayTypeUnitPurch( 40002786 , I_("DisAllowPayTypeUnitPurch") );
   extern CLASS_EXPORT const BFTextFieldId AllowCashDistrib( 40002787 , I_("AllowCashDistrib") );
   extern CLASS_EXPORT const BFTextFieldId PACCalendar( 40002788 , I_("PACCalendar") );
   extern CLASS_EXPORT const BFTextFieldId AcctCommExists( 40002789 , I_("AcctCommExists") );
   extern CLASS_EXPORT const BFDateFieldId LastNightRun( 40002790 , I_("LastNightRun") );
   extern CLASS_EXPORT const BFDateFieldId NextNightRun( 40002791 , I_("NextNightRun") );
   extern CLASS_EXPORT const BFTextFieldId PayIntOn( 40002792 , I_("PayIntOn") );
   extern CLASS_EXPORT const BFTextFieldId PayIntOnDesc( 40002793 , I_("PayIntOnDesc") );
   extern CLASS_EXPORT const BFTextFieldId FieldName( 40002798 , I_("FieldName") );
}
