// BFSubstitution objects
// TIMBUK3: This file was generated by Timbuk3 - Version 2.4.1
// TIMBUK3: Generated on : Mon Aug 24 15:59:58 2015


#include "stdafx.h"
#include <commonport.h>
#include <clientlocale.hpp>

namespace ifds
{
   extern const BFSubstitutionSet SubSet_Empty;
   // Chooser function for Substitution set ShareholderAddress.
   extern const BFSubstitutionSet SubSet_002_120_001_000_000;
   extern const BFSubstitutionSet SubSet_002_120_003_000_000;
   extern const BFSubstitutionSet SubSet_002_120_004_000_000;
   extern const BFSubstitutionSet SubSet_002_120_005_000_000;
   extern const BFSubstitutionSet SubSet_002_120_006_000_000;
   extern const BFSubstitutionSet SubSet_002_120_007_000_000;
   extern const BFSubstitutionSet SubSet_002_120_008_000_000;
   extern const BFSubstitutionSet SubSet_002_120_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_120( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_120_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_120_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_120_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_120_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_120_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_120_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_120_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_120_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_120_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set kShareholderAddress.
   extern const BFSubstitutionSet SubSet_002_121_001_000_000;
   extern const BFSubstitutionSet SubSet_002_121_003_000_000;
   extern const BFSubstitutionSet SubSet_002_121_004_000_000;
   extern const BFSubstitutionSet SubSet_002_121_005_000_000;
   extern const BFSubstitutionSet SubSet_002_121_006_000_000;
   extern const BFSubstitutionSet SubSet_002_121_007_000_000;
   extern const BFSubstitutionSet SubSet_002_121_008_000_000;
   extern const BFSubstitutionSet SubSet_002_121_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_121( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_121_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_121_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_121_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_121_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_121_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_121_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_121_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_121_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_121_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set EntityAddress.
   extern const BFSubstitutionSet SubSet_002_122_001_000_000;
   extern const BFSubstitutionSet SubSet_002_122_003_000_000;
   extern const BFSubstitutionSet SubSet_002_122_004_000_000;
   extern const BFSubstitutionSet SubSet_002_122_005_000_000;
   extern const BFSubstitutionSet SubSet_002_122_006_000_000;
   extern const BFSubstitutionSet SubSet_002_122_007_000_000;
   extern const BFSubstitutionSet SubSet_002_122_008_000_000;
   extern const BFSubstitutionSet SubSet_002_122_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_122( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_122_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_122_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_122_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_122_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_122_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_122_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_122_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_122_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_122_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set LV_BankListHeadingSet.
   extern const BFSubstitutionSet SubSet_002_123_001_000_000;
   extern const BFSubstitutionSet SubSet_002_123_003_000_000;
   extern const BFSubstitutionSet SubSet_002_123_004_000_000;
   extern const BFSubstitutionSet SubSet_002_123_005_000_000;
   extern const BFSubstitutionSet SubSet_002_123_006_000_000;
   extern const BFSubstitutionSet SubSet_002_123_007_000_000;
   extern const BFSubstitutionSet SubSet_002_123_008_000_000;
   extern const BFSubstitutionSet SubSet_002_123_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_123( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_123_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_123_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_123_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_123_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_123_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_123_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_123_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_123_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_123_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set LV_DefaultAllocShrHeadingSet.
   extern const BFSubstitutionSet SubSet_002_124_001_000_000;
   extern const BFSubstitutionSet SubSet_002_124_003_000_000;
   extern const BFSubstitutionSet SubSet_002_124_004_000_000;
   extern const BFSubstitutionSet SubSet_002_124_005_000_000;
   extern const BFSubstitutionSet SubSet_002_124_006_000_000;
   extern const BFSubstitutionSet SubSet_002_124_007_000_000;
   extern const BFSubstitutionSet SubSet_002_124_008_000_000;
   extern const BFSubstitutionSet SubSet_002_124_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_124( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_124_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_124_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_124_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_124_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_124_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_124_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_124_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_124_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_124_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set LV_DefaultAllocAcctHeadingSet.
   extern const BFSubstitutionSet SubSet_002_125_001_000_000;
   extern const BFSubstitutionSet SubSet_002_125_003_000_000;
   extern const BFSubstitutionSet SubSet_002_125_004_000_000;
   extern const BFSubstitutionSet SubSet_002_125_005_000_000;
   extern const BFSubstitutionSet SubSet_002_125_006_000_000;
   extern const BFSubstitutionSet SubSet_002_125_007_000_000;
   extern const BFSubstitutionSet SubSet_002_125_008_000_000;
   extern const BFSubstitutionSet SubSet_002_125_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_125( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_125_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_125_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_125_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_125_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_125_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_125_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_125_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_125_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_125_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set GrossNetSet.
   extern const BFSubstitutionSet SubSet_002_126_001_000_000;
   extern const BFSubstitutionSet SubSet_002_126_003_000_000;
   extern const BFSubstitutionSet SubSet_002_126_004_000_000;
   extern const BFSubstitutionSet SubSet_002_126_005_000_000;
   extern const BFSubstitutionSet SubSet_002_126_006_000_000;
   extern const BFSubstitutionSet SubSet_002_126_007_000_000;
   extern const BFSubstitutionSet SubSet_002_126_008_000_000;
   extern const BFSubstitutionSet SubSet_002_126_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_126( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_126_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_126_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_126_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_126_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_126_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_126_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_126_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_126_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_126_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set FrequencySet.
   extern const BFSubstitutionSet SubSet_002_127_001_002_000;
   extern const BFSubstitutionSet SubSet_002_127_001_000_000;
   extern const BFSubstitutionSet SubSet_002_127_003_002_000;
   extern const BFSubstitutionSet SubSet_002_127_003_000_000;
   extern const BFSubstitutionSet SubSet_002_127_004_002_000;
   extern const BFSubstitutionSet SubSet_002_127_004_000_000;
   extern const BFSubstitutionSet SubSet_002_127_005_002_000;
   extern const BFSubstitutionSet SubSet_002_127_005_000_000;
   extern const BFSubstitutionSet SubSet_002_127_006_002_000;
   extern const BFSubstitutionSet SubSet_002_127_006_000_000;
   extern const BFSubstitutionSet SubSet_002_127_007_002_000;
   extern const BFSubstitutionSet SubSet_002_127_007_000_000;
   extern const BFSubstitutionSet SubSet_002_127_008_002_000;
   extern const BFSubstitutionSet SubSet_002_127_008_000_000;
   extern const BFSubstitutionSet SubSet_002_127_010_002_000;
   extern const BFSubstitutionSet SubSet_002_127_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_127( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_127_001_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_127_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_127_003_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_127_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_127_004_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_127_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_127_005_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_127_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_127_006_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_127_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_127_007_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_127_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_127_008_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_127_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enGB") ) {
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_127_010_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_127_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("itIT") ) {
      }
      if ( locale.getLocale() == I_("thTH") ) {
      }
      return SubSet_002_127_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set SysStatusSet.
   extern const BFSubstitutionSet SubSet_002_128_001_000_000;
   extern const BFSubstitutionSet SubSet_002_128_003_000_000;
   extern const BFSubstitutionSet SubSet_002_128_004_000_000;
   extern const BFSubstitutionSet SubSet_002_128_005_000_000;
   extern const BFSubstitutionSet SubSet_002_128_006_000_000;
   extern const BFSubstitutionSet SubSet_002_128_007_000_000;
   extern const BFSubstitutionSet SubSet_002_128_008_000_000;
   extern const BFSubstitutionSet SubSet_002_128_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_128( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_128_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_128_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_128_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_128_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_128_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_128_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_128_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_128_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_128_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set AcctTypeSetX.
   extern const BFSubstitutionSet SubSet_002_129_001_000_000;
   extern const BFSubstitutionSet SubSet_002_129_003_000_000;
   extern const BFSubstitutionSet SubSet_002_129_004_000_000;
   extern const BFSubstitutionSet SubSet_002_129_005_000_000;
   extern const BFSubstitutionSet SubSet_002_129_006_000_000;
   extern const BFSubstitutionSet SubSet_002_129_007_000_000;
   extern const BFSubstitutionSet SubSet_002_129_008_000_000;
   extern const BFSubstitutionSet SubSet_002_129_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_129( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_129_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_129_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_129_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_129_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_129_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_129_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_129_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_129_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_129_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set LV_BranchListHeading.
   extern const BFSubstitutionSet SubSet_002_130_001_000_000;
   extern const BFSubstitutionSet SubSet_002_130_003_000_000;
   extern const BFSubstitutionSet SubSet_002_130_004_000_000;
   extern const BFSubstitutionSet SubSet_002_130_005_000_000;
   extern const BFSubstitutionSet SubSet_002_130_006_000_000;
   extern const BFSubstitutionSet SubSet_002_130_007_000_000;
   extern const BFSubstitutionSet SubSet_002_130_008_000_000;
   extern const BFSubstitutionSet SubSet_002_130_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_130( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_130_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_130_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_130_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_130_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_130_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_130_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_130_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_130_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_130_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set LV_SlsRepListHeading.
   extern const BFSubstitutionSet SubSet_002_131_001_003_000;
   extern const BFSubstitutionSet SubSet_002_131_001_004_000;
   extern const BFSubstitutionSet SubSet_002_131_001_000_000;
   extern const BFSubstitutionSet SubSet_002_131_003_003_000;
   extern const BFSubstitutionSet SubSet_002_131_003_004_000;
   extern const BFSubstitutionSet SubSet_002_131_003_000_000;
   extern const BFSubstitutionSet SubSet_002_131_004_003_000;
   extern const BFSubstitutionSet SubSet_002_131_004_004_000;
   extern const BFSubstitutionSet SubSet_002_131_004_000_000;
   extern const BFSubstitutionSet SubSet_002_131_005_003_000;
   extern const BFSubstitutionSet SubSet_002_131_005_004_000;
   extern const BFSubstitutionSet SubSet_002_131_005_000_000;
   extern const BFSubstitutionSet SubSet_002_131_006_003_000;
   extern const BFSubstitutionSet SubSet_002_131_006_004_000;
   extern const BFSubstitutionSet SubSet_002_131_006_000_000;
   extern const BFSubstitutionSet SubSet_002_131_007_003_000;
   extern const BFSubstitutionSet SubSet_002_131_007_004_000;
   extern const BFSubstitutionSet SubSet_002_131_007_000_000;
   extern const BFSubstitutionSet SubSet_002_131_008_003_000;
   extern const BFSubstitutionSet SubSet_002_131_008_004_000;
   extern const BFSubstitutionSet SubSet_002_131_008_000_000;
   extern const BFSubstitutionSet SubSet_002_131_009_004_000;
   extern const BFSubstitutionSet SubSet_002_131_010_003_000;
   extern const BFSubstitutionSet SubSet_002_131_010_004_000;
   extern const BFSubstitutionSet SubSet_002_131_010_000_000;
   extern const BFSubstitutionSet SubSet_002_131_011_004_000;
   extern const BFSubstitutionSet SubSet_002_131_012_004_000;
   const BFSubstitutionSet& chooser_ss_002_131( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_131_001_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_001_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_131_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_131_003_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_003_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_131_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_131_004_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_004_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_131_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_131_005_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_005_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_131_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_131_006_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_006_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_131_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_131_007_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_007_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_131_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_131_008_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_008_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_131_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enGB") ) {
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_009_004_000; // defined in ifast_substitutions_4.cpp
         }
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_131_010_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_010_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_131_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("itIT") ) {
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_011_004_000; // defined in ifast_substitutions_4.cpp
         }
      }
      if ( locale.getLocale() == I_("thTH") ) {
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_131_012_004_000; // defined in ifast_substitutions_4.cpp
         }
      }
      return SubSet_002_131_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set LV_DistributionToHeadingSet.
   extern const BFSubstitutionSet SubSet_002_132_001_002_000;
   extern const BFSubstitutionSet SubSet_002_132_001_000_000;
   extern const BFSubstitutionSet SubSet_002_132_003_002_000;
   extern const BFSubstitutionSet SubSet_002_132_003_000_000;
   extern const BFSubstitutionSet SubSet_002_132_004_002_000;
   extern const BFSubstitutionSet SubSet_002_132_004_000_000;
   extern const BFSubstitutionSet SubSet_002_132_005_002_000;
   extern const BFSubstitutionSet SubSet_002_132_005_000_000;
   extern const BFSubstitutionSet SubSet_002_132_006_002_000;
   extern const BFSubstitutionSet SubSet_002_132_006_000_000;
   extern const BFSubstitutionSet SubSet_002_132_007_002_000;
   extern const BFSubstitutionSet SubSet_002_132_007_000_000;
   extern const BFSubstitutionSet SubSet_002_132_008_002_000;
   extern const BFSubstitutionSet SubSet_002_132_008_000_000;
   extern const BFSubstitutionSet SubSet_002_132_010_002_000;
   extern const BFSubstitutionSet SubSet_002_132_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_132( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_132_001_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_132_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_132_003_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_132_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_132_004_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_132_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_132_005_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_132_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_132_006_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_132_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_132_007_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_132_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_132_008_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_132_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enGB") ) {
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_132_010_002_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_132_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("itIT") ) {
      }
      if ( locale.getLocale() == I_("thTH") ) {
      }
      return SubSet_002_132_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set AddressSet.
   extern const BFSubstitutionSet SubSet_002_133_001_000_000;
   extern const BFSubstitutionSet SubSet_002_133_003_000_000;
   extern const BFSubstitutionSet SubSet_002_133_004_000_000;
   extern const BFSubstitutionSet SubSet_002_133_005_000_000;
   extern const BFSubstitutionSet SubSet_002_133_006_000_000;
   extern const BFSubstitutionSet SubSet_002_133_007_000_000;
   extern const BFSubstitutionSet SubSet_002_133_008_000_000;
   extern const BFSubstitutionSet SubSet_002_133_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_133( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_133_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_133_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_133_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_133_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_133_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_133_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_133_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_133_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_133_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set DistributionTransTypeSet.
   extern const BFSubstitutionSet SubSet_002_134_001_000_000;
   extern const BFSubstitutionSet SubSet_002_134_003_000_000;
   extern const BFSubstitutionSet SubSet_002_134_004_000_000;
   extern const BFSubstitutionSet SubSet_002_134_005_000_000;
   extern const BFSubstitutionSet SubSet_002_134_006_000_000;
   extern const BFSubstitutionSet SubSet_002_134_007_000_000;
   extern const BFSubstitutionSet SubSet_002_134_008_000_000;
   extern const BFSubstitutionSet SubSet_002_134_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_134( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_134_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_134_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_134_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_134_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_134_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_134_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_134_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_134_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_134_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set DistributionPayTypeSet.
   extern const BFSubstitutionSet SubSet_002_135_001_000_000;
   extern const BFSubstitutionSet SubSet_002_135_003_000_000;
   extern const BFSubstitutionSet SubSet_002_135_004_000_000;
   extern const BFSubstitutionSet SubSet_002_135_005_000_000;
   extern const BFSubstitutionSet SubSet_002_135_006_000_000;
   extern const BFSubstitutionSet SubSet_002_135_007_000_000;
   extern const BFSubstitutionSet SubSet_002_135_008_000_000;
   extern const BFSubstitutionSet SubSet_002_135_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_135( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_135_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_135_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_135_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_135_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_135_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_135_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_135_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_135_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_135_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set MorganTaxTypeSet.
   extern const BFSubstitutionSet SubSet_002_136_001_000_000;
   extern const BFSubstitutionSet SubSet_002_136_003_000_000;
   extern const BFSubstitutionSet SubSet_002_136_004_000_000;
   extern const BFSubstitutionSet SubSet_002_136_005_000_000;
   extern const BFSubstitutionSet SubSet_002_136_006_000_000;
   extern const BFSubstitutionSet SubSet_002_136_007_000_000;
   extern const BFSubstitutionSet SubSet_002_136_008_000_000;
   extern const BFSubstitutionSet SubSet_002_136_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_136( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_136_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_136_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_136_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_136_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_136_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_136_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_136_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_136_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_136_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set MorganAcctTypeSetForT.
   extern const BFSubstitutionSet SubSet_002_137_001_000_000;
   extern const BFSubstitutionSet SubSet_002_137_003_000_000;
   extern const BFSubstitutionSet SubSet_002_137_004_000_000;
   extern const BFSubstitutionSet SubSet_002_137_005_000_000;
   extern const BFSubstitutionSet SubSet_002_137_006_000_000;
   extern const BFSubstitutionSet SubSet_002_137_007_000_000;
   extern const BFSubstitutionSet SubSet_002_137_008_000_000;
   extern const BFSubstitutionSet SubSet_002_137_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_137( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_137_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_137_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_137_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_137_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_137_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_137_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_137_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_137_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_137_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set MorganAcctTypeSetForX.
   extern const BFSubstitutionSet SubSet_002_138_001_000_000;
   extern const BFSubstitutionSet SubSet_002_138_003_000_000;
   extern const BFSubstitutionSet SubSet_002_138_004_000_000;
   extern const BFSubstitutionSet SubSet_002_138_005_000_000;
   extern const BFSubstitutionSet SubSet_002_138_006_000_000;
   extern const BFSubstitutionSet SubSet_002_138_007_000_000;
   extern const BFSubstitutionSet SubSet_002_138_008_000_000;
   extern const BFSubstitutionSet SubSet_002_138_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_138( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_138_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_138_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_138_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_138_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_138_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_138_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_138_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_138_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_138_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set LV_BrokerListHeading.
   extern const BFSubstitutionSet SubSet_002_139_001_000_000;
   extern const BFSubstitutionSet SubSet_002_139_003_000_000;
   extern const BFSubstitutionSet SubSet_002_139_004_000_000;
   extern const BFSubstitutionSet SubSet_002_139_005_000_000;
   extern const BFSubstitutionSet SubSet_002_139_006_000_000;
   extern const BFSubstitutionSet SubSet_002_139_007_000_000;
   extern const BFSubstitutionSet SubSet_002_139_008_000_000;
   extern const BFSubstitutionSet SubSet_002_139_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_139( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_139_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_139_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_139_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_139_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_139_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_139_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_139_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_139_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_139_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set BankInstrComboSet3.
   extern const BFSubstitutionSet SubSet_002_140_001_000_000;
   extern const BFSubstitutionSet SubSet_002_140_003_000_000;
   extern const BFSubstitutionSet SubSet_002_140_004_000_000;
   extern const BFSubstitutionSet SubSet_002_140_005_000_000;
   extern const BFSubstitutionSet SubSet_002_140_006_000_000;
   extern const BFSubstitutionSet SubSet_002_140_007_000_000;
   extern const BFSubstitutionSet SubSet_002_140_008_000_000;
   extern const BFSubstitutionSet SubSet_002_140_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_140( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_140_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_140_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_140_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_140_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_140_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_140_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_140_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_140_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_140_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set SearchBrokerSet.
   extern const BFSubstitutionSet SubSet_002_141_001_000_000;
   extern const BFSubstitutionSet SubSet_002_141_003_000_000;
   extern const BFSubstitutionSet SubSet_002_141_004_000_000;
   extern const BFSubstitutionSet SubSet_002_141_005_000_000;
   extern const BFSubstitutionSet SubSet_002_141_006_000_000;
   extern const BFSubstitutionSet SubSet_002_141_007_000_000;
   extern const BFSubstitutionSet SubSet_002_141_008_000_000;
   extern const BFSubstitutionSet SubSet_002_141_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_141( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_141_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_141_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_141_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_141_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_141_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_141_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_141_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_141_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_141_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set SearchBrokerUsingSet.
   extern const BFSubstitutionSet SubSet_002_142_001_000_000;
   extern const BFSubstitutionSet SubSet_002_142_003_000_000;
   extern const BFSubstitutionSet SubSet_002_142_004_000_000;
   extern const BFSubstitutionSet SubSet_002_142_005_000_000;
   extern const BFSubstitutionSet SubSet_002_142_006_000_000;
   extern const BFSubstitutionSet SubSet_002_142_007_000_000;
   extern const BFSubstitutionSet SubSet_002_142_008_000_000;
   extern const BFSubstitutionSet SubSet_002_142_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_142( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_142_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_142_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_142_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_142_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_142_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_142_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_142_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_142_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_142_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set RIFSrcOfFundSet.
   extern const BFSubstitutionSet SubSet_002_143_001_000_000;
   extern const BFSubstitutionSet SubSet_002_143_003_000_000;
   extern const BFSubstitutionSet SubSet_002_143_004_000_000;
   extern const BFSubstitutionSet SubSet_002_143_005_000_000;
   extern const BFSubstitutionSet SubSet_002_143_006_000_000;
   extern const BFSubstitutionSet SubSet_002_143_007_000_000;
   extern const BFSubstitutionSet SubSet_002_143_008_000_000;
   extern const BFSubstitutionSet SubSet_002_143_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_143( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_143_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_143_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_143_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_143_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_143_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_143_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_143_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_143_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_143_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set RecTypeSet.
   extern const BFSubstitutionSet SubSet_002_144_001_000_000;
   extern const BFSubstitutionSet SubSet_002_144_003_000_000;
   extern const BFSubstitutionSet SubSet_002_144_004_000_000;
   extern const BFSubstitutionSet SubSet_002_144_005_000_000;
   extern const BFSubstitutionSet SubSet_002_144_006_000_000;
   extern const BFSubstitutionSet SubSet_002_144_007_000_000;
   extern const BFSubstitutionSet SubSet_002_144_008_000_000;
   extern const BFSubstitutionSet SubSet_002_144_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_144( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_144_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_144_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_144_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_144_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_144_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_144_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_144_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_144_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_144_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set RatePUDSet.
   extern const BFSubstitutionSet SubSet_002_145_001_000_000;
   extern const BFSubstitutionSet SubSet_002_145_003_000_000;
   extern const BFSubstitutionSet SubSet_002_145_004_000_000;
   extern const BFSubstitutionSet SubSet_002_145_005_000_000;
   extern const BFSubstitutionSet SubSet_002_145_006_000_000;
   extern const BFSubstitutionSet SubSet_002_145_007_000_000;
   extern const BFSubstitutionSet SubSet_002_145_008_000_000;
   extern const BFSubstitutionSet SubSet_002_145_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_145( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_145_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_145_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_145_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_145_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_145_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_145_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_145_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_145_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_145_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set PayOptionSet.
   extern const BFSubstitutionSet SubSet_002_146_001_000_000;
   extern const BFSubstitutionSet SubSet_002_146_003_000_000;
   extern const BFSubstitutionSet SubSet_002_146_004_000_000;
   extern const BFSubstitutionSet SubSet_002_146_005_000_000;
   extern const BFSubstitutionSet SubSet_002_146_006_000_000;
   extern const BFSubstitutionSet SubSet_002_146_007_000_000;
   extern const BFSubstitutionSet SubSet_002_146_008_000_000;
   extern const BFSubstitutionSet SubSet_002_146_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_146( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         return SubSet_002_146_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         return SubSet_002_146_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         return SubSet_002_146_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         return SubSet_002_146_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         return SubSet_002_146_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         return SubSet_002_146_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         return SubSet_002_146_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         return SubSet_002_146_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      return SubSet_002_146_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set TradesPayTypeSet.
   extern const BFSubstitutionSet SubSet_002_147_001_002_000;
   extern const BFSubstitutionSet SubSet_002_147_001_003_003;
   extern const BFSubstitutionSet SubSet_002_147_001_003_011;
   extern const BFSubstitutionSet SubSet_002_147_001_003_014;
   extern const BFSubstitutionSet SubSet_002_147_001_003_000;
   extern const BFSubstitutionSet SubSet_002_147_001_004_000;
   extern const BFSubstitutionSet SubSet_002_147_001_000_000;
   extern const BFSubstitutionSet SubSet_002_147_003_002_000;
   extern const BFSubstitutionSet SubSet_002_147_003_003_003;
   extern const BFSubstitutionSet SubSet_002_147_003_003_011;
   extern const BFSubstitutionSet SubSet_002_147_003_003_014;
   extern const BFSubstitutionSet SubSet_002_147_003_003_000;
   extern const BFSubstitutionSet SubSet_002_147_003_004_000;
   extern const BFSubstitutionSet SubSet_002_147_003_000_000;
   extern const BFSubstitutionSet SubSet_002_147_004_002_000;
   extern const BFSubstitutionSet SubSet_002_147_004_003_003;
   extern const BFSubstitutionSet SubSet_002_147_004_003_011;
   extern const BFSubstitutionSet SubSet_002_147_004_003_014;
   extern const BFSubstitutionSet SubSet_002_147_004_003_000;
   extern const BFSubstitutionSet SubSet_002_147_004_004_000;
   extern const BFSubstitutionSet SubSet_002_147_004_000_000;
   extern const BFSubstitutionSet SubSet_002_147_005_002_000;
   extern const BFSubstitutionSet SubSet_002_147_005_003_003;
   extern const BFSubstitutionSet SubSet_002_147_005_003_011;
   extern const BFSubstitutionSet SubSet_002_147_005_003_014;
   extern const BFSubstitutionSet SubSet_002_147_005_003_000;
   extern const BFSubstitutionSet SubSet_002_147_005_004_000;
   extern const BFSubstitutionSet SubSet_002_147_005_000_000;
   extern const BFSubstitutionSet SubSet_002_147_006_002_000;
   extern const BFSubstitutionSet SubSet_002_147_006_003_003;
   extern const BFSubstitutionSet SubSet_002_147_006_003_011;
   extern const BFSubstitutionSet SubSet_002_147_006_003_014;
   extern const BFSubstitutionSet SubSet_002_147_006_003_000;
   extern const BFSubstitutionSet SubSet_002_147_006_004_000;
   extern const BFSubstitutionSet SubSet_002_147_006_000_000;
   extern const BFSubstitutionSet SubSet_002_147_007_002_000;
   extern const BFSubstitutionSet SubSet_002_147_007_003_003;
   extern const BFSubstitutionSet SubSet_002_147_007_003_011;
   extern const BFSubstitutionSet SubSet_002_147_007_003_014;
   extern const BFSubstitutionSet SubSet_002_147_007_003_000;
   extern const BFSubstitutionSet SubSet_002_147_007_004_000;
   extern const BFSubstitutionSet SubSet_002_147_007_000_000;
   extern const BFSubstitutionSet SubSet_002_147_008_002_000;
   extern const BFSubstitutionSet SubSet_002_147_008_003_003;
   extern const BFSubstitutionSet SubSet_002_147_008_003_011;
   extern const BFSubstitutionSet SubSet_002_147_008_003_014;
   extern const BFSubstitutionSet SubSet_002_147_008_003_000;
   extern const BFSubstitutionSet SubSet_002_147_008_004_000;
   extern const BFSubstitutionSet SubSet_002_147_008_000_000;
   extern const BFSubstitutionSet SubSet_002_147_009_003_003;
   extern const BFSubstitutionSet SubSet_002_147_009_003_011;
   extern const BFSubstitutionSet SubSet_002_147_009_003_014;
   extern const BFSubstitutionSet SubSet_002_147_009_003_000;
   extern const BFSubstitutionSet SubSet_002_147_009_004_000;
   extern const BFSubstitutionSet SubSet_002_147_010_002_000;
   extern const BFSubstitutionSet SubSet_002_147_010_003_003;
   extern const BFSubstitutionSet SubSet_002_147_010_003_011;
   extern const BFSubstitutionSet SubSet_002_147_010_003_014;
   extern const BFSubstitutionSet SubSet_002_147_010_003_000;
   extern const BFSubstitutionSet SubSet_002_147_010_004_000;
   extern const BFSubstitutionSet SubSet_002_147_010_000_000;
   extern const BFSubstitutionSet SubSet_002_147_011_003_003;
   extern const BFSubstitutionSet SubSet_002_147_011_003_011;
   extern const BFSubstitutionSet SubSet_002_147_011_003_014;
   extern const BFSubstitutionSet SubSet_002_147_011_003_000;
   extern const BFSubstitutionSet SubSet_002_147_011_004_000;
   extern const BFSubstitutionSet SubSet_002_147_012_003_003;
   extern const BFSubstitutionSet SubSet_002_147_012_003_011;
   extern const BFSubstitutionSet SubSet_002_147_012_003_014;
   extern const BFSubstitutionSet SubSet_002_147_012_003_000;
   extern const BFSubstitutionSet SubSet_002_147_012_004_000;
   const BFSubstitutionSet& chooser_ss_002_147( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_147_001_002_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_001_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_001_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_001_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_001_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_001_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_147_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_147_003_002_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_003_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_003_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_003_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_003_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_003_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_147_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_147_004_002_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_004_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_004_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_004_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_004_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_004_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_147_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_147_005_002_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_005_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_005_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_005_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_005_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_005_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_147_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_147_006_002_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_006_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_006_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_006_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_006_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_006_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_147_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_147_007_002_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_007_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_007_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_007_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_007_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_007_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_147_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_147_008_002_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_008_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_008_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_008_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_008_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_008_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_147_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enGB") ) {
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_009_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_009_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_009_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_009_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_009_004_000; // defined in ifast_substitutions_4.cpp
         }
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         if ( locale.getMarketIndex() == 2 ) {
            return SubSet_002_147_010_002_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_010_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_010_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_010_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_010_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_010_004_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_147_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("itIT") ) {
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_011_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_011_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_011_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_011_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_011_004_000; // defined in ifast_substitutions_4.cpp
         }
      }
      if ( locale.getLocale() == I_("thTH") ) {
         if ( locale.getMarketIndex() == 3 ) {
            if ( locale.getClientIndex() == 3 ) {
               return SubSet_002_147_012_003_003; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 11 ) {
               return SubSet_002_147_012_003_011; // defined in ifast_substitutions_4.cpp
            }
            if ( locale.getClientIndex() == 14 ) {
               return SubSet_002_147_012_003_014; // defined in ifast_substitutions_4.cpp
            }
            return SubSet_002_147_012_003_000; // defined in ifast_substitutions_4.cpp
         }
         if ( locale.getMarketIndex() == 4 ) {
            return SubSet_002_147_012_004_000; // defined in ifast_substitutions_4.cpp
         }
      }
      return SubSet_002_147_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set TradesTransTypeSet.
   extern const BFSubstitutionSet SubSet_002_148_001_003_000;
   extern const BFSubstitutionSet SubSet_002_148_001_000_000;
   extern const BFSubstitutionSet SubSet_002_148_003_003_000;
   extern const BFSubstitutionSet SubSet_002_148_003_000_000;
   extern const BFSubstitutionSet SubSet_002_148_004_003_000;
   extern const BFSubstitutionSet SubSet_002_148_004_000_000;
   extern const BFSubstitutionSet SubSet_002_148_005_003_000;
   extern const BFSubstitutionSet SubSet_002_148_005_000_000;
   extern const BFSubstitutionSet SubSet_002_148_006_003_000;
   extern const BFSubstitutionSet SubSet_002_148_006_000_000;
   extern const BFSubstitutionSet SubSet_002_148_007_003_000;
   extern const BFSubstitutionSet SubSet_002_148_007_000_000;
   extern const BFSubstitutionSet SubSet_002_148_008_003_000;
   extern const BFSubstitutionSet SubSet_002_148_008_000_000;
   extern const BFSubstitutionSet SubSet_002_148_010_003_000;
   extern const BFSubstitutionSet SubSet_002_148_010_000_000;
   const BFSubstitutionSet& chooser_ss_002_148( const ClientLocale& locale )
   {
      if ( locale.getLocale() == I_("enUS") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_148_001_003_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_148_001_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enCA") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_148_003_003_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_148_003_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frFR") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_148_004_003_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_148_004_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("frCA") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_148_005_003_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_148_005_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enIE") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_148_006_003_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_148_006_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("deDE") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_148_007_003_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_148_007_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("esEs") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_148_008_003_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_148_008_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("enGB") ) {
      }
      if ( locale.getLocale() == I_("nlNL") ) {
         if ( locale.getMarketIndex() == 3 ) {
            return SubSet_002_148_010_003_000; // defined in ifast_substitutions_4.cpp
         }
         return SubSet_002_148_010_000_000; // defined in ifast_substitutions_4.cpp
      }
      if ( locale.getLocale() == I_("itIT") ) {
      }
      if ( locale.getLocale() == I_("thTH") ) {
      }
      return SubSet_002_148_001_000_000; // defined in ifast_substitutions_4.cpp
   }

   // Chooser function for Substitution set EmptySubst.
   const BFSubstitutionSet& chooser_ss_002_149( const ClientLocale& locale )
   {
      return SubSet_Empty;
   }

}
