// Computer Generated Condition File for Module: ifastbp


#pragma message("including "__FILE__ )
#ifndef PLATFORM_H
#include "platform.h"
#endif


namespace CND
{
  CLASS_EXPORT const I_CHAR *IFASTBP_CONDITION = I_( "IFASTBP" );

  //extern CLASS_EXPORT const long BP_NO_ACCESS_TO_ACCTDETAILS = 40000193;
  //extern CLASS_EXPORT const long BP_ERR_NOT_ALLOW_SETFOCUS = 40000241;
  //extern CLASS_EXPORT const long ERR_BRANCH_LIST_EMPTY = 40000329;
  //extern CLASS_EXPORT const long ERR_AGENT_LIST_EMPTY = 40000330;
  //extern CLASS_EXPORT const long BP_ERR_NO_SEARCH_CRITERIA = 40000335;
  //extern CLASS_EXPORT const long ERR_NO_VALID_SHAREHOLDER_OR_ACCOUNT = 40000397;
  //extern CLASS_EXPORT const long BP_ERR_RESP_BENEFICIARY = 40000651;
  //extern CLASS_EXPORT const long ERR_BROKER_NAME_EMPTY = 40000652;
  //extern CLASS_EXPORT const long ERR_BROKER_LIST_EMPTY = 40000653;
  //extern CLASS_EXPORT const long BP_ERR_ACCOUNT_WAS_NOT_ACTIVE = 40000654;
  //extern CLASS_EXPORT const long BP_ERR_SEL_BROKER_FIRST = 40000747;
  //extern CLASS_EXPORT const long BP_ERR_SEL_BROKER_BRANCH_FIRST = 40000748;
  //extern CLASS_EXPORT const long ERR_RRIF_INFO_NOT_APPLICABLE = 40000837;
  //extern CLASS_EXPORT const long BP_ERR_BROKER_OR_BRANCH_EMPTY = 40000899;
  //extern CLASS_EXPORT const long BP_ERR_BROKER_OR_BRANCH_OR_SLSREP_EMPTY = 40000900;
  //extern CLASS_EXPORT const long BP_ERR_CANNOT_DELETE_ACTIVE_INDEX = 40000950;
  //extern CLASS_EXPORT const long BP_ERR_INVALID_TRADE_TYPE = 40001009;
  //extern CLASS_EXPORT const long BP_ERR_MULTIMATCH_ACCOUNTNUMBER = 40001149;
  //extern CLASS_EXPORT const long BP_ERR_DATA_NOT_FOUND = 40001160;
  //extern CLASS_EXPORT const long BP_ERR_INVALID_DATE_FORMAT = 40001178;
  //extern CLASS_EXPORT const long BP_ERR_FUND_EMPTY = 40001253;
  //extern CLASS_EXPORT const long BP_ERR_INVALID_FUND = 40001254;
  //extern CLASS_EXPORT const long BP_ERR_BROKER_EMPTY = 40001639;
  //extern CLASS_EXPORT const long BP_ERR_INVALID_FUND_AND_CLASS = 40001647;
  //extern CLASS_EXPORT const long BP_ERR_CLASS_EMPTY = 40001648;
  //extern CLASS_EXPORT const long IFASTBP_CND_VERSION = 40001877;
  //extern CLASS_EXPORT const long BP_ERR_INVALID_FUND_GROUP = 40001955;
  //extern CLASS_EXPORT const long BP_ERR_EMPTY_FUND_GROUP = 40001958;
  //extern CLASS_EXPORT const long BP_WRN_NO_CLIENT_SETTLE_INSTR = 40002020;
  //extern CLASS_EXPORT const long BP_ERR_CLIENT_SETTLE_INSTR_MANDATORY = 40002021;
  //extern CLASS_EXPORT const long BP_ERR_MULTI_AGGREGATED_ORDER = 40002087;
  //extern CLASS_EXPORT const long BP_ERR_AGGREGATED_ORDER_NOT_FOUND = 40002088;
  //extern CLASS_EXPORT const long BP_ERR_MORE_THAN_ONE_RECORD_FOUND = 40002112;
  //extern CLASS_EXPORT const long BP_WRN_MORE_THAN_ONE_RECORD_FOUND = 40002114;
  //extern CLASS_EXPORT const long BP_ERR_ENTITY_ADDRESS_LIST_INVALID = 40002180;
  //extern CLASS_EXPORT const long ERR_ACTIVE_BATCH = 40002599;
  //extern CLASS_EXPORT const long ERR_FUND_BROKER_CODE_EMPTY = 40002735;
  //extern CLASS_EXPORT const long ERR_FUND_BROKER_NAME_EMPTY = 40002736;
  //extern CLASS_EXPORT const long ERR_FUND_BROKER_NAME_NOT_EXISTING = 40002737;
  //extern CLASS_EXPORT const long BP_ERR_DEMOGRAPHICS_DATA_REQUIRED = 40002746;
  //extern CLASS_EXPORT const long BP_WARN_DEMOGRAPHICS_DATA_REQUIRED = 40002747;
  //extern CLASS_EXPORT const long BP_ERR_DOCUMENT_LIST_DATA_REQUIRED = 40002748;
  //extern CLASS_EXPORT const long BP_WARN_DOCUMENT_LIST_DATA_REQUIRED = 40002749;
  //extern CLASS_EXPORT const long BP_WARN_SIBLING_ONLY_BLANK_OR_NO = 40002917;
  //extern CLASS_EXPORT const long ERR_FAMILY_CODE_EMPTY = 40003210;
  //extern CLASS_EXPORT const long ERR_FAMILY_NAME_EMPTY = 40003211;
  //extern CLASS_EXPORT const long ERR_FAMILY_CODE_OR_NAME_NOT_EXISTING = 40003212;

	extern CLASS_EXPORT const long BP_ERR_ACCOUNT_WAS_NOT_ACTIVE = 1600001;
	extern CLASS_EXPORT const long BP_ERR_AGGREGATED_ORDER_NOT_FOUND = 1600002;
	extern CLASS_EXPORT const long BP_ERR_BROKER_EMPTY = 1600003;
	extern CLASS_EXPORT const long BP_ERR_BROKER_OR_BRANCH_EMPTY = 1600004;
	extern CLASS_EXPORT const long BP_ERR_BROKER_OR_BRANCH_OR_SLSREP_EMPTY = 1600005;
	extern CLASS_EXPORT const long BP_ERR_CANNOT_DELETE_ACTIVE_INDEX = 1600006;
	extern CLASS_EXPORT const long BP_ERR_CLASS_EMPTY = 1600007;
	extern CLASS_EXPORT const long BP_ERR_CLIENT_SETTLE_INSTR_MANDATORY = 1600008;
	extern CLASS_EXPORT const long BP_ERR_DATA_NOT_FOUND = 1600009;
	extern CLASS_EXPORT const long BP_ERR_DEMOGRAPHICS_DATA_REQUIRED = 1600010;
	extern CLASS_EXPORT const long BP_ERR_DOCUMENT_LIST_DATA_REQUIRED = 1600011;
	extern CLASS_EXPORT const long BP_ERR_EMPTY_FUND_GROUP = 1600012;
	extern CLASS_EXPORT const long BP_ERR_ENTITY_ADDRESS_LIST_INVALID = 1600013;
	extern CLASS_EXPORT const long BP_ERR_FUND_EMPTY = 1600014;
	extern CLASS_EXPORT const long BP_ERR_INVALID_DATE_FORMAT = 1600015;
	extern CLASS_EXPORT const long BP_ERR_INVALID_FUND = 1600016;
	extern CLASS_EXPORT const long BP_ERR_INVALID_FUND_AND_CLASS = 1600017;
	extern CLASS_EXPORT const long BP_ERR_INVALID_FUND_GROUP = 1600018;
	extern CLASS_EXPORT const long BP_ERR_INVALID_TRADE_TYPE = 1600019;
	extern CLASS_EXPORT const long BP_ERR_MORE_THAN_ONE_RECORD_FOUND = 1600020;
	extern CLASS_EXPORT const long BP_ERR_MULTI_AGGREGATED_ORDER = 1600021;
	extern CLASS_EXPORT const long BP_ERR_MULTIMATCH_ACCOUNTNUMBER = 1600022;
	extern CLASS_EXPORT const long BP_ERR_NO_SEARCH_CRITERIA = 1600023;
	extern CLASS_EXPORT const long BP_ERR_NOT_ALLOW_SETFOCUS = 1600024;
	extern CLASS_EXPORT const long BP_ERR_RESP_BENEFICIARY = 1600025;
	extern CLASS_EXPORT const long BP_ERR_SEL_BROKER_BRANCH_FIRST = 1600026;
	extern CLASS_EXPORT const long BP_ERR_SEL_BROKER_FIRST = 1600027;
	extern CLASS_EXPORT const long BP_NO_ACCESS_TO_ACCTDETAILS = 1600028;
	extern CLASS_EXPORT const long BP_WARN_DEMOGRAPHICS_DATA_REQUIRED = 1600029;
	extern CLASS_EXPORT const long BP_WARN_DOCUMENT_LIST_DATA_REQUIRED = 1600030;
	extern CLASS_EXPORT const long BP_WARN_SIBLING_ONLY_BLANK_OR_NO = 1600031;
	extern CLASS_EXPORT const long BP_WRN_MORE_THAN_ONE_RECORD_FOUND = 1600032;
	extern CLASS_EXPORT const long BP_WRN_NO_CLIENT_SETTLE_INSTR = 1600033;
	extern CLASS_EXPORT const long ERR_ACTIVE_BATCH = 1600034;
	extern CLASS_EXPORT const long ERR_AGENT_LIST_EMPTY = 1600035;
	extern CLASS_EXPORT const long ERR_BRANCH_LIST_EMPTY = 1600036;
	extern CLASS_EXPORT const long ERR_BROKER_LIST_EMPTY = 1600037;
	extern CLASS_EXPORT const long ERR_BROKER_NAME_EMPTY = 1600038;
	extern CLASS_EXPORT const long ERR_FAMILY_CODE_EMPTY = 1600039;
	extern CLASS_EXPORT const long ERR_FAMILY_CODE_OR_NAME_NOT_EXISTING = 1600040;
	extern CLASS_EXPORT const long ERR_FAMILY_NAME_EMPTY = 1600041;
	extern CLASS_EXPORT const long ERR_FUND_BROKER_CODE_EMPTY = 1600042;
	extern CLASS_EXPORT const long ERR_FUND_BROKER_NAME_EMPTY = 1600043;
	extern CLASS_EXPORT const long ERR_FUND_BROKER_NAME_NOT_EXISTING = 1600044;
	extern CLASS_EXPORT const long ERR_NO_VALID_SHAREHOLDER_OR_ACCOUNT = 1600045;
	extern CLASS_EXPORT const long ERR_RRIF_INFO_NOT_APPLICABLE = 1600046;
	extern CLASS_EXPORT const long IFASTBP_CND_VERSION = 1600047;
}

