// Computer Generated Condition File for Module: diawdi


#pragma message("including "__FILE__ )
#ifndef PLATFORM_H
   #include <win32\platform.h>
#endif


namespace CND_DIAWDI
{
   CLASS_EXPORT const I_CHAR *DIAWDI_CONDITION = I_( "DIAWDI" );

   //extern CLASS_EXPORT const long DIAWDI_INVALID_DATE_TIME_PASSED = 20000217;
   //extern CLASS_EXPORT const long DIAWDI_LOAD_MODULE_FAIL = 20000237;
   //extern CLASS_EXPORT const long DIAWDI_LOAD_PROC_FAIL = 20000238;
   //extern CLASS_EXPORT const long DIAWDI_LOGON_INVALID_PASSWORD = 20000239;
   //extern CLASS_EXPORT const long DIAWDI_LOGON_USER_ALREADY_LOGGED_ON = 20000240;
   //extern CLASS_EXPORT const long DIAWDI_LOGON_PASSWORD_EXPIRED = 20000241;
   //extern CLASS_EXPORT const long DIAWDI_LOGON_NEW_PASSWORD_SAMEAS_OLD = 20000242;
   //extern CLASS_EXPORT const long DIAWDI_LOGON_INVALID_OPID = 20000243;
   //extern CLASS_EXPORT const long DIAWDI_LOGON_USER_DISABLED = 20000244;
   //extern CLASS_EXPORT const long DIAWDI_LOGON_INVALID_NEW_PASSWORD = 20000245;
   //extern CLASS_EXPORT const long DIAWDI_LOGON_OTHER_ERROR = 20000246;
   //extern CLASS_EXPORT const long DIAWDI_LOGON_NO_ERROR = 20000247;

	extern CLASS_EXPORT const long DIAWDI_INVALID_DATE_TIME_PASSED = 700001;
	extern CLASS_EXPORT const long DIAWDI_LOAD_MODULE_FAIL = 700002;
	extern CLASS_EXPORT const long DIAWDI_LOAD_PROC_FAIL = 700003;
	extern CLASS_EXPORT const long DIAWDI_LOGON_INVALID_NEW_PASSWORD = 700004;
	extern CLASS_EXPORT const long DIAWDI_LOGON_INVALID_OPID = 700005;
	extern CLASS_EXPORT const long DIAWDI_LOGON_INVALID_PASSWORD = 700006;
	extern CLASS_EXPORT const long DIAWDI_LOGON_NEW_PASSWORD_SAMEAS_OLD = 700007;
	extern CLASS_EXPORT const long DIAWDI_LOGON_NO_ERROR = 700008;
	extern CLASS_EXPORT const long DIAWDI_LOGON_OTHER_ERROR = 700009;
	extern CLASS_EXPORT const long DIAWDI_LOGON_PASSWORD_EXPIRED = 700010;
	extern CLASS_EXPORT const long DIAWDI_LOGON_USER_ALREADY_LOGGED_ON = 700011;
	extern CLASS_EXPORT const long DIAWDI_LOGON_USER_DISABLED = 700012;
}

