#pragma once
#include <commonport.h>

#undef BFAWDI_LINKAGE
#ifdef BFAWDI_DLL
   #define BFAWDI_LINKAGE CLASS_EXPORT
#else
   #define BFAWDI_LINKAGE CLASS_IMPORT
#endif

namespace CND_DIAWDI
{
   extern BFAWDI_LINKAGE const I_CHAR * DIAWDI_CONDITION;


   extern BFAWDI_LINKAGE const long DIAWDI_INVALID_DATE_TIME_PASSED;
   extern BFAWDI_LINKAGE const long DIAWDI_LOAD_MODULE_FAIL;
   extern BFAWDI_LINKAGE const long DIAWDI_LOAD_PROC_FAIL;
   extern BFAWDI_LINKAGE const long DIAWDI_LOGON_INVALID_PASSWORD;
   extern BFAWDI_LINKAGE const long DIAWDI_LOGON_USER_ALREADY_LOGGED_ON;
   extern BFAWDI_LINKAGE const long DIAWDI_LOGON_PASSWORD_EXPIRED;
   extern BFAWDI_LINKAGE const long DIAWDI_LOGON_NEW_PASSWORD_SAMEAS_OLD;
   extern BFAWDI_LINKAGE const long DIAWDI_LOGON_INVALID_OPID;
   extern BFAWDI_LINKAGE const long DIAWDI_LOGON_USER_DISABLED;
   extern BFAWDI_LINKAGE const long DIAWDI_LOGON_INVALID_NEW_PASSWORD;
   extern BFAWDI_LINKAGE const long DIAWDI_LOGON_OTHER_ERROR;
   extern BFAWDI_LINKAGE const long DIAWDI_LOGON_NO_ERROR;
}

using namespace CND_DIAWDI;

