// Computer Generated Condition File for Module: didbrkr


#pragma message("including "__FILE__ )

#include <DString.hpp>

#ifndef PLATFORM_H
#include "platform.h"
#endif


namespace CND_DIDBRKR
{
  CLASS_EXPORT const I_CHAR *DIDBRKR_CONDITION = I_( "DIDBRKR" );

  extern CLASS_EXPORT const long DIDBRKR_CANT_SET_VALUES = 20000141;
  extern CLASS_EXPORT const long DIDBRKR_COMPONENT_NOT_FOUND = 20000142;
  extern CLASS_EXPORT const long DIDBRKR_DATA_HAS_NO_REPEATS = 20000143;
  extern CLASS_EXPORT const long DIDBRKR_INDEX_OUT_OF_RANGE = 20000144;
  extern CLASS_EXPORT const long DIDBRKR_CANNOT_ASSIGN_DATA_OBJECTS = 20000145;
  extern CLASS_EXPORT const long DIDBRKR_ELEMENT_NOT_FOUND = 20000146;
  extern CLASS_EXPORT const long DIDBRKR_REPEAT_COUNT_ELEMENT_NOT_FOUND = 20000147;
  extern CLASS_EXPORT const long DIDBRKR_KEY_NOT_FOUND = 20000148;
  extern CLASS_EXPORT const long DIDBRKR_NOT_A_DATA_OBJECT = 20000149;
  extern CLASS_EXPORT const long DIDBRKR_NOT_A_DATAELEMENT_OBJECT = 20000150;
  extern CLASS_EXPORT const long DIDBRKR_REPEAT_INDEX_OUT_OF_RANGE = 20000151;
  extern CLASS_EXPORT const long DIDBRKR_CANNOT_ASSIGN_DATAELEMENT_OBJECTS = 20000152;
  extern CLASS_EXPORT const long DIDBRKR_PROPERTIES_DONT_MATCH = 20000153;
  extern CLASS_EXPORT const long DIDBRKR_PROPERTY_DOES_NOT_EXIST = 20000154;
  extern CLASS_EXPORT const long DIDBRKR_PROPERTY_DOES_NOT_EXIST_AT_INDEX = 20000155;
  extern CLASS_EXPORT const long DIDBRKR_CANT_OPEN_PROPERTIES_FILE = 20000156;
  extern CLASS_EXPORT const long DIDBRKR_NO_PATH_TO_PROPERTIES_FILE = 20000157;
  extern CLASS_EXPORT const long DIDBRKR_BAD_FORMAT_IN_STREAM_FILE = 20000158;
  extern CLASS_EXPORT const long DIDBRKR_ERROR_READING_STREAM_FILE = 20000159;
  extern CLASS_EXPORT const long DIDBRKR_UNEXPECTED_END_OF_STREAM_FILE = 20000160;
  extern CLASS_EXPORT const long DIDBRKR_INVALID_LINE_LENGTH = 20000161;
  extern CLASS_EXPORT const long DIDBRKR_INVALID_PROPERTY_POINTER = 20000162;
  extern CLASS_EXPORT const long DIDBRKR_NOT_REPEATABLE = 20000163;
  extern CLASS_EXPORT const long DIDBRKR_DUPLICATE_PROPERTIES = 20000164;
  extern CLASS_EXPORT const long DIDBRKR_EXTRA_LINES_IN_PROPERTIES_FILE = 20000165;
  extern CLASS_EXPORT const long DIDBRKR_LOCALE_NOT_FOUND = 20000166;
  extern CLASS_EXPORT const long DIDBRKR_DATASET_NOT_FOUND = 20000167;
  extern CLASS_EXPORT const long DIDBRKR_FILE_SEEK_FAILED = 20000168;
  extern CLASS_EXPORT const long DIDBRKR_I18N_MASK_FORMAT_ERROR = 20000250;
  extern CLASS_EXPORT const long DIDBRKR_INVALID_REDEFINE = 20000252;
  extern CLASS_EXPORT const long DIDBRKR_REDEFINE_HAS_DUPLICATE = 20000253;
  extern CLASS_EXPORT const long DIDBRKR_REDEFINE_LENGTH_MISMATCH = 20000344;
  extern CLASS_EXPORT const long DIDBRKR_REDEFINE_REPEATS_NOT_ALLOWED = 20000345;
  extern CLASS_EXPORT const long DIDBRKR_READ_SIZE_FAILED = 20000730;
  extern CLASS_EXPORT const long DIDBRKR_TARGET_LOCALE_MISSING = 20000731;
}

