// Computer Generated Condition File for Module: xparser


#pragma message("including "__FILE__ )
#ifndef PLATFORM_H
#include "platform.h"
#endif


namespace CND
{
  CLASS_EXPORT const I_CHAR *XPARSER_CONDITION = I_( "XPARSER" );

  //extern CLASS_EXPORT const long ERR_DELETE_PARSER = 40000204;
  //extern CLASS_EXPORT const long ERR_CREATE_PARSER = 40000205;
  //extern CLASS_EXPORT const long ERR_NO_REQUEST_NAME = 40000206;
  //extern CLASS_EXPORT const long ERR_NO_ACTION_TYPE = 40000207;
  //extern CLASS_EXPORT const long ERR_TOO_MANY_WKSID_TAGS = 40000208;
  //extern CLASS_EXPORT const long ERR_TOO_MANY_USID_TAGS = 40000209;
  //extern CLASS_EXPORT const long ERR_FIELDDETAILS_TAG = 40000210;
  //extern CLASS_EXPORT const long ERR_TOO_MANY_FIELDKEY_TAGS = 40000211;
  //extern CLASS_EXPORT const long ERR_TOO_MANY_CNTID_TAGS = 40000212;
  //extern CLASS_EXPORT const long ERR_NO_SUCH_ELEMENT = 40000241;
  //extern CLASS_EXPORT const long ERR_INVALID_ROOT_ELEMENT_NAME = 40000242;
  //extern CLASS_EXPORT const long ERR_INVALID_RECORD_COUNT_ATTRIBUTE = 40000243;
  //extern CLASS_EXPORT const long ERR_NEGATIVE_RECORD_COUNT_ATTRIBUTE = 40000244;
  //extern CLASS_EXPORT const long ERR_INVALID_PROCESS_ACTION_ATTRIBUTE = 40000245;
  //extern CLASS_EXPORT const long ERR_INVALID_CBO_ACTION_ATTRIBUTE = 40000246;
  //extern CLASS_EXPORT const long ERR_INVALID_ELEMENT_CLASS_ATTRIBUTE = 40000247;
  //extern CLASS_EXPORT const long ERR_ELEMENT_CLASS_ATTRIBUTE_NOT_SPECIFIED = 40000248;
  //extern CLASS_EXPORT const long ERR_INVALID_CACHE_ATTRIBUTE = 40000249;
  //extern CLASS_EXPORT const long ERR_INVALID_BOOLEAN_ATTRIBUTE = 40000250;
  //extern CLASS_EXPORT const long ERR_FIELD_NOT_DEFINED = 40000251;
  //extern CLASS_EXPORT const long ERR_ELEMENT_CANNOT_CONTAIN_CLASS = 40000252;
  //extern CLASS_EXPORT const long ERR_CBO_NOT_DEFINED = 40000253;
  //extern CLASS_EXPORT const long ERR_CBO_NOT_FOUND_FOR_KEY = 40000254;
  //extern CLASS_EXPORT const long ERR_KEY_SPECIFIED_FOR_NONLIST = 40000255;
  //extern CLASS_EXPORT const long ERR_KEY_NOT_SPECIFIED_FOR_LIST = 40000256;
  //extern CLASS_EXPORT const long ERR_MULTIPLE_KEYS_NOT_ALLOWED = 40000257;
  //extern CLASS_EXPORT const long XP_UNKNOWN_EXCEPTION = 40000258;
  //extern CLASS_EXPORT const long XP_REQUEST_UNPARSABLE = 40000268;
  //extern CLASS_EXPORT const long XP_SAX_PARSE_EXCEPTION = 40000269;
  //extern CLASS_EXPORT const long XPARSER_CND_VERSION = 40000279;

	extern CLASS_EXPORT const long ERR_CBO_NOT_DEFINED = 2300001;
	extern CLASS_EXPORT const long ERR_CBO_NOT_FOUND_FOR_KEY = 2300002;
	extern CLASS_EXPORT const long ERR_CREATE_PARSER = 2300003;
	extern CLASS_EXPORT const long ERR_DELETE_PARSER = 2300004;
	extern CLASS_EXPORT const long ERR_ELEMENT_CANNOT_CONTAIN_CLASS = 2300005;
	extern CLASS_EXPORT const long ERR_ELEMENT_CLASS_ATTRIBUTE_NOT_SPECIFIED = 2300006;
	extern CLASS_EXPORT const long ERR_FIELD_NOT_DEFINED = 2300007;
	extern CLASS_EXPORT const long ERR_FIELDDETAILS_TAG = 2300008;
	extern CLASS_EXPORT const long ERR_INVALID_BOOLEAN_ATTRIBUTE = 2300009;
	extern CLASS_EXPORT const long ERR_INVALID_CACHE_ATTRIBUTE = 2300010;
	extern CLASS_EXPORT const long ERR_INVALID_CBO_ACTION_ATTRIBUTE = 2300011;
	extern CLASS_EXPORT const long ERR_INVALID_ELEMENT_CLASS_ATTRIBUTE = 2300012;
	extern CLASS_EXPORT const long ERR_INVALID_PROCESS_ACTION_ATTRIBUTE = 2300013;
	extern CLASS_EXPORT const long ERR_INVALID_RECORD_COUNT_ATTRIBUTE = 2300014;
	extern CLASS_EXPORT const long ERR_INVALID_ROOT_ELEMENT_NAME = 2300015;
	extern CLASS_EXPORT const long ERR_KEY_NOT_SPECIFIED_FOR_LIST = 2300016;
	extern CLASS_EXPORT const long ERR_KEY_SPECIFIED_FOR_NONLIST = 2300017;
	extern CLASS_EXPORT const long ERR_MULTIPLE_KEYS_NOT_ALLOWED = 2300018;
	extern CLASS_EXPORT const long ERR_NEGATIVE_RECORD_COUNT_ATTRIBUTE = 2300019;
	extern CLASS_EXPORT const long ERR_NO_ACTION_TYPE = 2300020;
	extern CLASS_EXPORT const long ERR_NO_REQUEST_NAME = 2300021;
	extern CLASS_EXPORT const long ERR_NO_SUCH_ELEMENT = 2300022;
	extern CLASS_EXPORT const long ERR_TOO_MANY_CNTID_TAGS = 2300023;
	extern CLASS_EXPORT const long ERR_TOO_MANY_FIELDKEY_TAGS = 2300024;
	extern CLASS_EXPORT const long ERR_TOO_MANY_USID_TAGS = 2300025;
	extern CLASS_EXPORT const long ERR_TOO_MANY_WKSID_TAGS = 2300026;
	extern CLASS_EXPORT const long XP_REQUEST_UNPARSABLE = 2300027;
	extern CLASS_EXPORT const long XP_SAX_PARSE_EXCEPTION = 2300028;
	extern CLASS_EXPORT const long XP_UNKNOWN_EXCEPTION = 2300029;
	extern CLASS_EXPORT const long XPARSER_CND_VERSION = 2300030;
}

